/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"

#include "EntitiesMP/StdH/StdH.h"
#include "ModelsMP/Enemies/Mental/Mental.h"

#include <EntitiesMP/BigHead.h>
#include <EntitiesMP/BigHead_tables.h>
#line 31 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"

// info structure
static EntityInfo eiMental = {
  EIBT_FLESH, 200.0f,
  0.0f, 1.5f, 0.0f,     // source (eyes)
  0.0f, 1.0f, 0.0f,     // target (body)
};

#define GREET_SENSE_RANGE 10.0f
#define GREET_SENSE_DELAY 30.0f


void CBigHead::SetDefaultProperties(void) {
  m_fnmHeadTex = CTString("");
  m_fnmNameSnd = CTString("");
  m_tmLastGreetTime = -100.0f;
  m_bhtType = BHT_NORMAL ;
  m_bIgnorePlayer = FALSE ;
  m_bPlayingWalkSound = FALSE ;
  m_bSleeping = FALSE ;
  m_tmLastWalkingSoundTime = -100.0f;
  m_tmWalkingSound = 5.0f;
  CEnemyBase::SetDefaultProperties();
}
  
#line 87 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
BOOL CBigHead::HandleEvent(const CEntityEvent & ee) 
#line 88 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
{
#line 89 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(m_bIgnorePlayer ){
#line 90 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(ee  . ee_slEvent  == EVENTCODE_ETouch ){
#line 91 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
ETouch  & et  = (ETouch  &) ee ;
#line 92 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(IsOfClass  (et  . penOther  , "Player")){
#line 93 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return TRUE ;
#line 94 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 95 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 96 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 97 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return CEnemyBase  :: HandleEvent  (ee );
#line 98 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 101 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
void * CBigHead::GetEntityInfo(void) 
#line 102 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
{
#line 103 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return & eiMental ;
#line 104 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 106 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
void CBigHead::Precache(void) 
#line 107 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
{
#line 108 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
CEnemyBase  :: Precache  ();
#line 109 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PrecacheSound  (SOUND_SIGHT );
#line 110 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PrecacheSound  (SOUND_IDLE );
#line 111 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PrecacheSound  (SOUND_WOUND );
#line 112 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PrecacheSound  (SOUND_DEATH );
#line 113 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PrecacheSound  (SOUND_WALKZOMBIE );
#line 114 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PrecacheSound  (SOUND_WALKSAINT );
#line 115 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_aps  . Precache  (m_fnmNameSnd );
#line 116 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_apt  . Precache  (m_fnmHeadTex );
#line 117 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 119 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
INDEX CBigHead::GetWalkAnim(void) 
#line 120 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
{
#line 121 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(m_bhtType  == BHT_ZOMBIE ){
#line 122 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return MENTAL_ANIM_WALKZOMBIE ;
#line 123 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}else if(m_bhtType  == BHT_SAINT ){
#line 124 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return MENTAL_ANIM_WALKANGEL ;
#line 125 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}else {
#line 126 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return MENTAL_ANIM_RUN ;
#line 127 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 128 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 131 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
INDEX CBigHead::AnimForDamage(FLOAT fDamage) {
#line 132 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
INDEX iAnim ;
#line 133 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
iAnim  = MENTAL_ANIM_PANIC ;
#line 134 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
StartModelAnim  (iAnim  , 0);
#line 135 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return iAnim ;
#line 136 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 139 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
INDEX CBigHead::AnimForDeath(void) {
#line 140 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
INDEX iAnim ;
#line 141 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
iAnim  = MENTAL_ANIM_DEATH ;
#line 142 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
StartModelAnim  (iAnim  , 0);
#line 143 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return iAnim ;
#line 144 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 146 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
void CBigHead::DeathNotify(void) {
#line 148 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
en_fDensity  = 500.0f;
#line 149 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 152 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
void CBigHead::StandingAnim(void) {
#line 153 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
StartModelAnim  (MENTAL_ANIM_GROUNDREST  , AOF_LOOPING  | AOF_NORESTART );
#line 154 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 155 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
void CBigHead::WalkingAnim(void) {
#line 156 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PlayWalkSound  ();
#line 157 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
StartModelAnim  (GetWalkAnim  () , AOF_LOOPING  | AOF_NORESTART );
#line 159 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(! m_bIgnorePlayer  && _pTimer  -> CurrentTick  () > m_tmLastGreetTime  + GREET_SENSE_DELAY ){
#line 160 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fSenseRange  = GREET_SENSE_RANGE ;
#line 161 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bDeaf  = FALSE ;
#line 162 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 163 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 164 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
void CBigHead::RunningAnim(void) 
#line 165 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
{
#line 166 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PlayWalkSound  ();
#line 167 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
StartModelAnim  (GetWalkAnim  () , AOF_LOOPING  | AOF_NORESTART );
#line 168 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 169 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
void CBigHead::RotatingAnim(void) {
#line 170 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
RunningAnim  ();
#line 171 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 173 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
void CBigHead::PlayWalkSound(void) 
#line 174 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
{
#line 175 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
INDEX iSound  = SOUND_WALKZOMBIE ;
#line 176 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(m_bhtType  == BHT_ZOMBIE ){
#line 177 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
iSound  = SOUND_WALKZOMBIE ;
#line 178 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}else if(m_bhtType  == BHT_SAINT ){
#line 179 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
iSound  = SOUND_WALKSAINT ;
#line 180 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}else {
#line 181 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return ;
#line 182 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 183 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(! m_bPlayingWalkSound  || _pTimer  -> CurrentTick  () - m_tmLastWalkingSoundTime  > m_tmWalkingSound ){
#line 184 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bPlayingWalkSound  = TRUE ;
#line 185 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_tmLastWalkingSoundTime  = _pTimer  -> CurrentTick  ();
#line 186 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PlaySound  (m_soSound  , iSound  , SOF_3D );
#line 187 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 188 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 191 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
void CBigHead::IdleSound(void) {
#line 192 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(m_bIgnorePlayer ){
#line 193 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return ;
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 195 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PlaySound  (m_soSound  , SOUND_IDLE  , SOF_3D );
#line 196 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bPlayingWalkSound  = FALSE ;
#line 197 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 199 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
void CBigHead::SightSound(void) {
#line 200 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PlaySound  (m_soSound  , SOUND_SIGHT  , SOF_3D );
#line 201 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bPlayingWalkSound  = FALSE ;
#line 202 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 203 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
void CBigHead::WoundSound(void) {
#line 204 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PlaySound  (m_soSound  , SOUND_WOUND  , SOF_3D );
#line 205 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bPlayingWalkSound  = FALSE ;
#line 206 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
  
#line 207 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
void CBigHead::DeathSound(void) {
#line 208 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PlaySound  (m_soSound  , SOUND_DEATH  , SOF_3D );
#line 209 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bPlayingWalkSound  = FALSE ;
#line 210 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
BOOL CBigHead::
#line 213 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBigHead_Fire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBigHead::Fire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 215 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(!(CalcDist  (m_penEnemy ) <= m_fStopDistance  * 1.1f)){ Jump(STATE_CURRENT,0x01540003, FALSE, EInternal());return TRUE;}
#line 216 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(m_fnmNameSnd  != ""){
#line 217 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PlaySound  (m_soSound  , m_fnmNameSnd  , SOF_3D );
#line 218 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bPlayingWalkSound  = FALSE ;
#line 219 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 220 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bBlind  = TRUE ;
#line 221 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bDeaf  = TRUE ;
#line 222 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fSenseRange  = 0.0f;
#line 223 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_tmLastGreetTime  = _pTimer  -> CurrentTick  ();
#line 224 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
SetTargetNone  ();
#line 225 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
StartModelAnim  (MENTAL_ANIM_GREET  , 0);
#line 226 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
SetTimerAfter(GetModelObject  () -> GetCurrentAnimLength  ());
Jump(STATE_CURRENT, 0x01540001, FALSE, EBegin());return TRUE;}BOOL CBigHead::H0x01540001_Fire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01540001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01540002, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBigHead::H0x01540002_Fire_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01540002
;
#line 227 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
StandingAnim  ();
#line 228 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
Return(STATE_CURRENT,EReconsiderBehavior  ());
#line 228 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return TRUE;Jump(STATE_CURRENT,0x01540003, FALSE, EInternal());return TRUE;}BOOL CBigHead::H0x01540003_Fire_03(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01540003

#line 230 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
Return(STATE_CURRENT,EReturn  ());
#line 230 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBigHead::
#line 233 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
Sleep(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBigHead_Sleep
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBigHead::Sleep expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 236 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
StartModelAnim  (MENTAL_ANIM_SNORE  , AOF_LOOPING );
#line 238 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x01540005, FALSE, EBegin());return TRUE;}BOOL CBigHead::H0x01540005_Sleep_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01540005
switch(__eeInput.ee_slEvent){case(EVENTCODE_ETrigger):{const ETrigger&eTrigger= (ETrigger&)__eeInput;

#line 244 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
Jump(STATE_CURRENT, STATE_CBigHead_WakeUp, TRUE, EVoid());return TRUE;
#line 245 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}ASSERT(FALSE);break;default:{
#line 253 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return TRUE;
#line 254 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}ASSERT(FALSE);break;
#line 255 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}return TRUE;}BOOL CBigHead::H0x01540006_Sleep_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01540006
 ASSERT(FALSE); return TRUE;};BOOL CBigHead::
#line 258 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
WakeUp(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBigHead_WakeUp
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBigHead::WakeUp expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 261 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
SightSound  ();
#line 262 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
StartModelAnim  (MENTAL_ANIM_GETUP  , 0);
#line 263 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
SetTimerAfter(GetModelObject  () -> GetCurrentAnimLength  ());
Jump(STATE_CURRENT, 0x01540008, FALSE, EBegin());return TRUE;}BOOL CBigHead::H0x01540008_WakeUp_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01540008
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01540009, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBigHead::H0x01540009_WakeUp_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01540009
;
#line 268 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
Return(STATE_CURRENT,EReturn  ());
#line 268 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBigHead::
#line 272 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
PreMainLoop(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBigHead_PreMainLoop
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBigHead::PreMainLoop expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 275 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(!(m_bSleeping )){ Jump(STATE_CURRENT,0x0154000d, FALSE, EInternal());return TRUE;}
#line 276 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bSleeping  = FALSE ;
#line 278 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x0154000b, FALSE, EBegin());return TRUE;}BOOL CBigHead::H0x0154000b_PreMainLoop_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0154000b
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;

#line 280 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
Call(STATE_CURRENT, STATE_CBigHead_Sleep, TRUE, EVoid());return TRUE;
#line 281 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}ASSERT(FALSE);break;case(EVENTCODE_EReturn):{const EReturn&e= (EReturn&)__eeInput;

#line 283 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
UnsetTimer();Jump(STATE_CURRENT,0x0154000c, FALSE, EInternal());return TRUE;
#line 284 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&eDeath= (EDeath&)__eeInput;

#line 288 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_Die, FALSE, eDeath );return TRUE;
#line 289 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 290 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}return TRUE;}BOOL CBigHead::H0x0154000c_PreMainLoop_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0154000c
Jump(STATE_CURRENT,0x0154000d, FALSE, EInternal());return TRUE;}BOOL CBigHead::H0x0154000d_PreMainLoop_03(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0154000d

#line 292 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
Return(STATE_CURRENT,EReturn  ());
#line 292 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBigHead::
#line 298 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBigHead_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBigHead::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 300 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
InitAsModel  ();
#line 301 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
SetPhysicsFlags  (EPF_MODEL_WALKING  | EPF_HASLUNGS );
#line 302 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
SetCollisionFlags  (ECF_MODEL );
#line 303 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 304 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
SetHealth  (20.0f);
#line 305 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fMaxHealth  = 20.0f;
#line 306 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
en_tmMaxHoldBreath  = 5.0f;
#line 307 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
en_fDensity  = 2000.0f;
#line 308 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fBlowUpSize  = 2.0f;
#line 311 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
SetModel  (MODEL_MENTAL );
#line 312 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
SetModelMainTexture  (TEXTURE_MENTAL );
#line 313 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
AddAttachment  (0 , MODEL_HEAD  , TEXTURE_MENTAL );
#line 314 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(m_fnmHeadTex  != ""){
#line 316 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
try {
#line 317 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
CAttachmentModelObject  * pamoHead  = GetModelObject  () -> GetAttachmentModel  (0);
#line 318 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(pamoHead  != NULL ){
#line 319 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
pamoHead  -> amo_moModelObject  . mo_toTexture  . SetData_t  (m_fnmHeadTex );
#line 320 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 322 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}catch  (const char  * strError ){
#line 324 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
CPrintF  ("%s\n" , (const char  *) strError );
#line 325 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
AddAttachment  (0 , MODEL_HEAD  , TEXTURE_MENTAL );
#line 326 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 327 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 328 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(m_bhtType  == BHT_ZOMBIE ){
#line 329 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
AddAttachment  (MENTAL_ATTACHMENT_HORNS  , MODEL_HORNS  , TEXTURE_HORNS );
#line 330 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}else if(m_bhtType  == BHT_SAINT ){
#line 331 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
AddAttachment  (MENTAL_ATTACHMENT_AURA  , MODEL_AURA  , TEXTURE_AURA );
#line 332 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 335 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fWalkSpeed  = FRnd  () + 1.5f;
#line 336 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 10.0f + 500.0f);
#line 337 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fAttackRunSpeed  = FRnd  () * 2.0f + 6.0f;
#line 338 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_aAttackRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 339 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fCloseRunSpeed  = FRnd  () * 2.0f + 6.0f;
#line 340 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 342 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fAttackDistance  = 50.0f;
#line 343 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fCloseDistance  = 0.0f;
#line 344 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fStopDistance  = 5.0f;
#line 345 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fAttackFireTime  = 0.1f;
#line 346 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fCloseFireTime  = 0.1f;
#line 347 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fIgnoreRange  = 200.0f;
#line 349 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fBlowUpAmount  = 65.0f;
#line 350 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fBodyParts  = 4;
#line 351 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fDamageWounded  = 1.0f;
#line 352 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_iScore  = 0;
#line 353 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
if(m_bIgnorePlayer ){
#line 354 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bBlind  = TRUE ;
#line 355 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bDeaf  = TRUE ;
#line 356 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fSenseRange  = 0;
#line 357 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}else {
#line 358 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_bBlind  = TRUE ;
#line 359 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
m_fSenseRange  = GREET_SENSE_RANGE ;
#line 360 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
}
#line 363 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
const FLOAT fSize  = 0.6f;
#line 364 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
GetModelObject  () -> StretchModel  (FLOAT3D (fSize  , fSize  , fSize ));
#line 365 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
ModelChangeNotify  ();
#line 366 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
StandingAnim  ();
#line 369 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/BigHead.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};