/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"

#include "EntitiesMP/StdH/StdH.h"
#include "ModelsMP/Enemies/CannonStatic/Turret.h"


#include <EntitiesMP/CannonStatic.h>
#include <EntitiesMP/CannonStatic_tables.h>
#line 29 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"

#define CANNONS_SIZE 2.0f
  
// info structure
static EntityInfo eiCannonStatic = {
  EIBT_WOOD, 10000.0f,
  0.0f, 1.5f*CANNONS_SIZE, 0.0f,     // source (eyes)
  0.0f, 0.5f*CANNONS_SIZE, 0.0f,     // target (body)
};

#define FIRING_POSITION_MUZZLE FLOAT3D(0.0f, 0.4f, -1.0f)
#define MUZZLE_ROTATION_SPEED 45.0f //deg/sec


void CCannonStatic::SetDefaultProperties(void) {
  m_fHealth = 100.0f;
  m_fFiringRangeClose = 50.0f;
  m_fFiringRangeFar = 150.0f;
  m_fShootingPeriod = 5.0f;
  m_fSize = CANNONS_SIZE ;
  m_fMaxPitch = 20.0f;
  m_fViewAngle = 2.5f;
  m_bActive = TRUE ;
  m_fRotSpeedMuzzle = ANGLE3D(0.0f , 0.0f , 0.0f);
  m_fDistanceToPlayer = 0.0f;
  m_fDesiredMuzzlePitch = 0.0f;
  m_iMuzzleDir = 1;
  m_vFiringPos = FLOAT3D(0.0f , 0.0f , 0.0f);
  m_vTarget = FLOAT3D(0.0f , 0.0f , 0.0f);
  m_aBeginMuzzleRotation = ANGLE3D(0.0f , 0.0f , 0.0f);
  m_aEndMuzzleRotation = ANGLE3D(0.0f , 0.0f , 0.0f);
  CEnemyBase::SetDefaultProperties();
}
  CTString CCannonStatic::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 95 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
{
#line 96 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CTString str ;
#line 97 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
str  . PrintF  (TRANSV  ("A Cannon killed %s") , (const char  *) strPlayerName );
#line 98 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return str ;
#line 99 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 102 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
void * CCannonStatic::GetEntityInfo(void) {
#line 103 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return & eiCannonStatic ;
#line 104 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  const CTFileName & CCannonStatic::GetComputerMessageName(void)const {
#line 107 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
static DECLARE_CTFILENAME  (fnmCannon  , "DataMP\\Messages\\Enemies\\CannonStatic.txt");
#line 108 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return fnmCannon ;
#line 109 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 111 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
void CCannonStatic::Precache(void) {
#line 112 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CEnemyBase  :: Precache  ();
#line 113 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
PrecacheModel  (MODEL_DEBRIS_MUZZLE );
#line 114 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
PrecacheModel  (MODEL_DEBRIS_WHEEL );
#line 115 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
PrecacheModel  (MODEL_DEBRIS_WOOD );
#line 116 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
PrecacheModel  (MODEL_BALL );
#line 118 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
PrecacheTexture  (TEXTURE_BALL );
#line 120 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
PrecacheSound  (SOUND_FIRE );
#line 122 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
PrecacheClass  (CLASS_CANNONBALL );
#line 123 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 126 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
void CCannonStatic::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 127 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 128 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
{
#line 130 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(dmtType  == DMT_BULLET  && fDamageAmmount  > 100.0f)
#line 131 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
{
#line 132 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
fDamageAmmount  *= 0.5f;
#line 133 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 135 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , 
#line 136 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
vHitPoint  , vDirection );
#line 137 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 140 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
INDEX CCannonStatic::AnimForDamage(FLOAT fDamage) {
#line 141 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return 0;
#line 142 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 145 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
INDEX CCannonStatic::AnimForDeath(void) {
#line 146 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return 0;
#line 147 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 150 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
BOOL CCannonStatic::IsVisible(CEntity * penEntity) 
#line 151 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
{
#line 152 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
ASSERT  (penEntity  != NULL );
#line 154 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vSource  , vTarget ;
#line 155 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
GetPositionCastRay  (this  , penEntity  , vSource  , vTarget );
#line 158 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CCastRay  crRay  (this  , vSource  , vTarget );
#line 159 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
crRay  . cr_ttHitModels  = CCastRay  :: TT_NONE ;
#line 160 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
crRay  . cr_bHitTranslucentPortals  = FALSE ;
#line 161 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
en_pwoWorld  -> CastRay  (crRay );
#line 164 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return (crRay  . cr_penHit  == NULL );
#line 165 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 167 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
BOOL CCannonStatic::IsInTheLineOfFire(CEntity * penEntity,FLOAT fAngle) 
#line 168 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
{
#line 169 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
ASSERT  (penEntity  != NULL );
#line 171 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT fCosAngle ;
#line 172 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vHeading ;
#line 173 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vToPlayer ;
#line 175 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vSide  = FLOAT3D (1.0f , 0.0f , 0.0f) * GetRotationMatrix  ();
#line 176 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vFront  = FLOAT3D (0.0f , 0.0f , - 1.0f) * GetRotationMatrix  ();
#line 177 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
vToPlayer  = penEntity  -> GetPlacement  () . pl_PositionVector  - GetPlacement  () . pl_PositionVector ;
#line 178 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
vToPlayer  . Normalize  ();
#line 180 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
fCosAngle  = vToPlayer  % vSide ;
#line 183 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(Abs  (fCosAngle ) < CosFast  (90.0f - fAngle )){
#line 185 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if((vToPlayer  % vFront ) > 0.0f){
#line 186 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return TRUE ;
#line 187 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 188 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 189 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return FALSE ;
#line 190 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 192 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CPlayer * CCannonStatic::AcquireTarget() {
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
INDEX ctMaxPlayers  = GetMaxPlayers  ();
#line 195 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CEntity  * penPlayer ;
#line 197 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
for(INDEX i  = 0;i  < ctMaxPlayers ;i  ++){
#line 198 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
penPlayer  = GetPlayerEntity  (i );
#line 199 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(penPlayer  != NULL  && DistanceTo  (this  , penPlayer ) < m_fFiringRangeFar ){
#line 201 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(IsInTheLineOfFire  (penPlayer  , m_fViewAngle )){
#line 203 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(IsVisible  (penPlayer )){
#line 204 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return (CPlayer  *) penPlayer ;
#line 205 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 206 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 207 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 208 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 209 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return NULL ;
#line 210 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 213 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
void CCannonStatic::CannonBlowUp(void) 
#line 214 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
{
#line 215 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vNormalizedDamage  = m_vDamage  - m_vDamage  * (m_fBlowUpAmount  / m_vDamage  . Length  ());
#line 216 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
vNormalizedDamage  /= Sqrt  (vNormalizedDamage  . Length  ());
#line 217 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
vNormalizedDamage  *= 0.75f;
#line 218 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
vNormalizedDamage  += FLOAT3D (0.0f , 10.0f + FRnd  () * 10.0f , 0.0f);
#line 220 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vBodySpeed  = en_vCurrentTranslationAbsolute  - en_vGravityDir  * (en_vGravityDir  % en_vCurrentTranslationAbsolute );
#line 223 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Debris_Begin  (EIBT_WOOD  , DPT_NONE  , BET_NONE  , 1.0f , vNormalizedDamage  , vBodySpeed  , 5.0f , 2.0f);
#line 225 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Debris_Spawn  (this  , this  , MODEL_DEBRIS_MUZZLE  , TEXTURE_CANNON  , 0 , 0 , 0 , 0 , m_fSize  , 
#line 226 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D (FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f));
#line 227 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Debris_Spawn  (this  , this  , MODEL_DEBRIS_WHEEL  , TEXTURE_TURRET  , 0 , 0 , 0 , 0 , m_fSize  , 
#line 228 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D (FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f));
#line 229 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Debris_Spawn  (this  , this  , MODEL_DEBRIS_WHEEL  , TEXTURE_TURRET  , 0 , 0 , 0 , 0 , m_fSize  , 
#line 230 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D (FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f));
#line 231 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Debris_Spawn  (this  , this  , MODEL_DEBRIS_WOOD  , TEXTURE_TURRET  , 0 , 0 , 0 , 0 , m_fSize  , 
#line 232 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D (FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f));
#line 233 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Debris_Spawn  (this  , this  , MODEL_DEBRIS_WOOD  , TEXTURE_TURRET  , 0 , 0 , 0 , 0 , m_fSize  , 
#line 234 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D (FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f));
#line 235 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Debris_Spawn  (this  , this  , MODEL_BALL  , TEXTURE_BALL  , 0 , 0 , 0 , 0 , m_fSize  / 2.0f , 
#line 236 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D (FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f));
#line 239 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CPlacement3D plExplosion  = GetPlacement  ();
#line 240 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CEntityPointer penExplosion  = CreateEntity  (plExplosion  , CLASS_BASIC_EFFECT );
#line 241 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
ESpawnEffect  eSpawnEffect ;
#line 242 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
eSpawnEffect  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 243 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
eSpawnEffect  . betType  = BET_CANNON ;
#line 244 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT fSize  = m_fBlowUpSize  * 1.0f;
#line 245 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
eSpawnEffect  . vStretch  = FLOAT3D (fSize  , fSize  , fSize );
#line 246 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
penExplosion  -> Initialize  (eSpawnEffect );
#line 249 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
plExplosion  = GetPlacement  ();
#line 250 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
penExplosion  = CreateEntity  (plExplosion  , CLASS_BASIC_EFFECT );
#line 251 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
eSpawnEffect  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 252 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
eSpawnEffect  . betType  = BET_CANNONSHOCKWAVE ;
#line 253 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
fSize  = m_fBlowUpSize  * 1.0f;
#line 254 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
eSpawnEffect  . vStretch  = FLOAT3D (fSize  , fSize  , fSize );
#line 255 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
penExplosion  -> Initialize  (eSpawnEffect );
#line 258 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SwitchToEditorModel  ();
#line 259 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 260 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 261 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 263 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
void CCannonStatic::PreMoving() {
#line 265 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
UpdateAttachmentRotations  ();
#line 266 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CEnemyBase  :: PreMoving  ();
#line 267 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 269 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
void CCannonStatic::PostMoving() {
#line 270 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CEnemyBase  :: PostMoving  ();
#line 272 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetFlags  (GetFlags  () & ~ ENF_INRENDERING );
#line 273 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 275 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
BOOL CCannonStatic::AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient) {
#line 276 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CAttachmentModelObject  & amo0  = * GetModelObject  () -> GetAttachmentModel  (TURRET_ATTACHMENT_CANNON );
#line 278 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
amo0  . amo_plRelative  . pl_OrientationAngle  = Lerp  (m_aBeginMuzzleRotation  , m_aEndMuzzleRotation  , _pTimer  -> GetLerpFactor  ());
#line 279 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return CEnemyBase  :: AdjustShadingParameters  (vLightDirection  , colLight  , colAmbient );
#line 280 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 282 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
void CCannonStatic::UpdateAttachmentRotations(void) 
#line 283 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
{
#line 285 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_aBeginMuzzleRotation  = m_aEndMuzzleRotation ;
#line 286 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_aEndMuzzleRotation  += m_fRotSpeedMuzzle  * _pTimer  -> TickQuantum ;
#line 287 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
  
#line 289 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
void CCannonStatic::UpdateFiringPos() {
#line 290 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOATmatrix3D m ;
#line 292 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_vFiringPos  = FIRING_POSITION_MUZZLE  * m_fSize ;
#line 295 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
MakeRotationMatrixFast  (m  , m_aBeginMuzzleRotation );
#line 296 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_vFiringPos  = m_vFiringPos  * m ;
#line 299 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CAttachmentModelObject  & amo0  = * GetModelObject  () -> GetAttachmentModel  (TURRET_ATTACHMENT_CANNON );
#line 300 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_vFiringPos  += amo0  . amo_plRelative  . pl_PositionVector ;
#line 301 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
BOOL CCannonStatic::
#line 305 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
MainLoop(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CCannonStatic_MainLoop
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CCannonStatic::MainLoop expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 306 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x01590001, FALSE, EBegin());return TRUE;}BOOL CCannonStatic::H0x01590001_MainLoop_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590001
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;

#line 308 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Call(STATE_CURRENT, STATE_CCannonStatic_WatchPlayers, TRUE, EVoid());return TRUE;
#line 309 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return TRUE;
#line 310 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}ASSERT(FALSE);break;case(EVENTCODE_EDeactivate):{const EDeactivate&e= (EDeactivate&)__eeInput;

#line 312 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Jump(STATE_CURRENT, STATE_CCannonStatic_Inactive, TRUE, EVoid());return TRUE;
#line 313 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&eDeath= (EDeath&)__eeInput;

#line 315 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Jump(STATE_CURRENT, STATE_CCannonStatic_Die, TRUE, eDeath );return TRUE;
#line 316 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 317 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}return TRUE;}BOOL CCannonStatic::H0x01590002_MainLoop_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590002
;
#line 318 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Return(STATE_CURRENT,EVoid());
#line 318 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CCannonStatic::
#line 322 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Die(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CCannonStatic_Die
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EDeath, "CCannonStatic::Die expects 'EDeath' as input!");  const EDeath &eDeath = (const EDeath &)__eeInput;
#line 324 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetFlags  (GetFlags  () & ~ ENF_ALIVE );
#line 327 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CEntityPointer penKiller  = eDeath  . eLastDamage  . penInflictor ;
#line 328 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(penKiller  == NULL  || ! IsOfClass  (penKiller  , "Player")){
#line 329 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
penKiller  = m_penEnemy ;
#line 330 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 332 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(penKiller  == NULL  || ! IsOfClass  (penKiller  , "Player")){
#line 333 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
penKiller  = FixupCausedToPlayer  (this  , penKiller  , FALSE );
#line 334 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 337 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(penKiller  != NULL ){
#line 339 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
EReceiveScore  eScore ;
#line 340 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
eScore  . iPoints  = (INDEX) m_iScore ;
#line 341 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
penKiller  -> SendEvent  (eScore );
#line 342 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(CountAsKill  ())
#line 343 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
{
#line 344 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
penKiller  -> SendEvent  (EKilledEnemy  ());
#line 345 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 347 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
EComputerMessage  eMsg ;
#line 348 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
eMsg  . fnmMessage  = GetComputerMessageName  ();
#line 349 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(eMsg  . fnmMessage  != ""){
#line 350 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
penKiller  -> SendEvent  (eMsg );
#line 351 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 352 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 355 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SendToTarget  (m_penDeathTarget  , m_eetDeathType  , penKiller );
#line 358 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(m_penSpawnerTarget ){
#line 359 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SendToTarget  (m_penSpawnerTarget  , EET_TRIGGER  , this );
#line 360 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 363 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CannonBlowUp  ();
#line 364 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Destroy  ();
#line 365 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Return(STATE_CURRENT,EVoid());
#line 365 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CCannonStatic::
#line 369 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
RotateMuzzle(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CCannonStatic_RotateMuzzle
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CCannonStatic::RotateMuzzle expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 371 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT fDeltaP  = m_fDesiredMuzzlePitch  - m_aBeginMuzzleRotation  (2);
#line 374 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(Abs  (fDeltaP ) < 5.0f){Return(STATE_CURRENT,EReturn  ());return TRUE;}
#line 376 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fRotSpeedMuzzle  = ANGLE3D (0.0f , MUZZLE_ROTATION_SPEED  * Sgn  (fDeltaP ) , 0.0f);
#line 377 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetTimerAfter(Abs  (fDeltaP  / MUZZLE_ROTATION_SPEED ));
Jump(STATE_CURRENT, 0x01590005, FALSE, EBegin());return TRUE;}BOOL CCannonStatic::H0x01590005_RotateMuzzle_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590005
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01590006, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CCannonStatic::H0x01590006_RotateMuzzle_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590006
;
#line 378 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fRotSpeedMuzzle  = ANGLE3D (0.0f , 0.0f , 0.0f);
#line 379 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
UpdateFiringPos  ();
#line 381 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Return(STATE_CURRENT,EReturn  ());
#line 381 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CCannonStatic::
#line 384 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FireCannon(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CCannonStatic_FireCannon
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CCannonStatic::FireCannon expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 386 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vToTarget  = m_penEnemy  -> GetPlacement  () . pl_PositionVector  - 
#line 387 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
GetPlacement  () . pl_PositionVector  + m_vFiringPos ;
#line 388 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
vToTarget  . Normalize  ();
#line 391 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vCannonFront  = FLOAT3D (0.0f , 0.0f , - 1.0f) * GetRotationMatrix  ();
#line 392 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
ANGLE aToPlayer  = ACos  (vToTarget  % vCannonFront );
#line 394 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT fPitch  = aToPlayer  + 5.0f;
#line 395 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vCannonUp  = FLOAT3D (0.0 , 1.0f , 0.0f) * GetRotationMatrix  ();
#line 398 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(m_fDistanceToPlayer  > m_fFiringRangeFar ){
#line 399 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Return(STATE_CURRENT,EReturn  ());
#line 399 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return TRUE;
#line 401 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}else if(vToTarget  % vCannonUp  < 0.0f){
#line 402 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
fPitch  = 5.0f;
#line 404 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}else if(m_fDistanceToPlayer  > m_fFiringRangeClose ){
#line 405 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(aToPlayer  < m_fMaxPitch ){
#line 406 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
fPitch  = aToPlayer  + m_fMaxPitch  * (m_fDistanceToPlayer  - m_fFiringRangeClose ) / (m_fFiringRangeFar  - m_fFiringRangeClose );
#line 407 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}else if(TRUE ){
#line 408 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
fPitch  = aToPlayer  + 10.0f + m_fMaxPitch  * (m_fDistanceToPlayer  - m_fFiringRangeClose ) / (m_fFiringRangeFar  - m_fFiringRangeClose );
#line 409 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 411 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
fPitch  = Clamp  (fPitch  , 1.0f , 80.0f);
#line 412 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}
#line 414 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_vTarget  = m_penEnemy  -> GetPlacement  () . pl_PositionVector ;
#line 416 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fDesiredMuzzlePitch  = fPitch ;
#line 417 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
STATE_CCannonStatic_RotateMuzzle, TRUE;
Jump(STATE_CURRENT, 0x01590008, FALSE, EBegin());return TRUE;}BOOL CCannonStatic::H0x01590008_FireCannon_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590008
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CCannonStatic_RotateMuzzle, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01590009, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CCannonStatic::H0x01590009_FireCannon_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590009
const EReturn&__e= (EReturn&)__eeInput;
;
#line 419 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vShooting  = GetPlacement  () . pl_PositionVector  + m_vFiringPos ;
#line 420 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vSpeedDest  = FLOAT3D (0.0f , 0.0f , 0.0f);
#line 421 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT fLaunchSpeed ;
#line 422 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT fRelativeHdg ;
#line 425 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
EntityInfo  * peiTarget  = (EntityInfo  *) (m_penEnemy  -> GetEntityInfo  ());
#line 426 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CalculateAngularLaunchParams  (vShooting  , peiTarget  -> vTargetCenter  [ 1 ] - 6.0f / 3.0f , m_vTarget  , 
#line 427 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
vSpeedDest  , m_fDesiredMuzzlePitch  , fLaunchSpeed  , fRelativeHdg );
#line 430 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
FLOAT3D vShootTarget ;
#line 431 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
GetEntityInfoPosition  (m_penEnemy  , peiTarget  -> vTargetCenter  , vShootTarget );
#line 433 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CPlacement3D pl ;
#line 434 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
PrepareFreeFlyingProjectile  (pl  , vShootTarget  , m_vFiringPos  , ANGLE3D (fRelativeHdg  , m_fDesiredMuzzlePitch  , 0));
#line 435 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CEntityPointer penBall  = CreateEntity  (pl  , CLASS_CANNONBALL );
#line 436 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
ELaunchCannonBall  eLaunch ;
#line 437 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
eLaunch  . penLauncher  = this ;
#line 438 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
eLaunch  . fLaunchPower  = fLaunchSpeed ;
#line 439 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
eLaunch  . cbtType  = CBT_IRON ;
#line 440 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
eLaunch  . fSize  = 1.0f;
#line 441 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
penBall  -> Initialize  (eLaunch );
#line 443 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Return(STATE_CURRENT,EReturn  ());
#line 443 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CCannonStatic::
#line 447 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
WatchPlayers(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CCannonStatic_WatchPlayers
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CCannonStatic::WatchPlayers expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 451 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Jump(STATE_CURRENT,0x01590013, FALSE, EInternal());return TRUE;}BOOL CCannonStatic::H0x01590013_WatchPlayers_09(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590013
if(!(TRUE )){ Jump(STATE_CURRENT,0x01590014, FALSE, EInternal());return TRUE;}
#line 452 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetTimerAfter(0.20f);
Jump(STATE_CURRENT, 0x0159000b, FALSE, EBegin());return TRUE;}BOOL CCannonStatic::H0x0159000b_WatchPlayers_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0159000b
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0159000c, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CCannonStatic::H0x0159000c_WatchPlayers_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0159000c
;
#line 453 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
CPlayer  * pTarget  = AcquireTarget  ();
#line 454 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(!(pTarget )){ Jump(STATE_CURRENT,0x01590012, FALSE, EInternal());return TRUE;}
#line 455 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(!((pTarget  -> GetFlags  () & ENF_ALIVE ) && ! (pTarget  -> GetFlags  () & ENF_DELETED ))){ Jump(STATE_CURRENT,0x01590011, FALSE, EInternal());return TRUE;}
#line 456 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_penEnemy  = pTarget ;
#line 457 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fDistanceToPlayer  = DistanceTo  (this  , pTarget );
#line 458 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
STATE_CCannonStatic_FireCannon, TRUE;
Jump(STATE_CURRENT, 0x0159000d, FALSE, EBegin());return TRUE;}BOOL CCannonStatic::H0x0159000d_WatchPlayers_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0159000d
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CCannonStatic_FireCannon, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x0159000e, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CCannonStatic::H0x0159000e_WatchPlayers_04(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x0159000e
const EReturn&__e= (EReturn&)__eeInput;
;
#line 459 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetTimerAfter(m_fShootingPeriod );
Jump(STATE_CURRENT, 0x0159000f, FALSE, EBegin());return TRUE;}BOOL CCannonStatic::H0x0159000f_WatchPlayers_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0159000f
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01590010, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CCannonStatic::H0x01590010_WatchPlayers_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590010
;Jump(STATE_CURRENT,0x01590011, FALSE, EInternal());return TRUE;}BOOL CCannonStatic::H0x01590011_WatchPlayers_07(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590011
Jump(STATE_CURRENT,0x01590012, FALSE, EInternal());return TRUE;}BOOL CCannonStatic::H0x01590012_WatchPlayers_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590012
Jump(STATE_CURRENT,0x01590013, FALSE, EInternal());return TRUE;
#line 462 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}BOOL CCannonStatic::H0x01590014_WatchPlayers_10(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590014
 ASSERT(FALSE); return TRUE;};BOOL CCannonStatic::
#line 465 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Inactive(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CCannonStatic_Inactive
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CCannonStatic::Inactive expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 467 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fRotSpeedMuzzle  = ANGLE3D (0.0f , 0.0f , 0.0f);
#line 468 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x01590016, FALSE, EBegin());return TRUE;}BOOL CCannonStatic::H0x01590016_Inactive_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590016
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EActivate):{const EActivate&e= (EActivate&)__eeInput;

#line 471 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Jump(STATE_CURRENT, STATE_CCannonStatic_MainLoop, TRUE, EVoid());return TRUE;
#line 472 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&eDeath= (EDeath&)__eeInput;

#line 474 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Jump(STATE_CURRENT, STATE_CCannonStatic_Die, TRUE, eDeath );return TRUE;
#line 475 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 477 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
}return TRUE;}BOOL CCannonStatic::H0x01590017_Inactive_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590017
 ASSERT(FALSE); return TRUE;};BOOL CCannonStatic::
#line 480 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CCannonStatic_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CCannonStatic::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 482 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
InitAsModel  ();
#line 483 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetPhysicsFlags  (EPF_MODEL_WALKING  | EPF_HASLUNGS );
#line 484 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetCollisionFlags  (ECF_MODEL );
#line 485 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 486 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
en_fDensity  = 2000.0f;
#line 489 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetModel  (MODEL_TURRET );
#line 490 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetModelMainTexture  (TEXTURE_TURRET );
#line 492 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
AddAttachment  (TURRET_ATTACHMENT_CANNON  , MODEL_CANNON  , TEXTURE_CANNON );
#line 494 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fWalkSpeed  = 0.0f;
#line 495 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_aWalkRotateSpeed  = 0.0f;
#line 496 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fAttackRunSpeed  = 0.0f;
#line 497 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_aAttackRotateSpeed  = 0.0f;
#line 498 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fCloseRunSpeed  = 0.0f;
#line 499 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_aCloseRotateSpeed  = 0.0f;
#line 501 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fStopDistance  = 100.0f;
#line 503 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fBlowUpAmount  = 100.0f;
#line 504 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fBodyParts  = 4;
#line 505 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fDamageWounded  = 0.0f;
#line 506 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_iScore  = 750;
#line 507 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_sptType  = SPT_WOOD ;
#line 510 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(m_fHealth  <= 0.0f){m_fHealth  = 1.0f;}
#line 511 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
m_fCloseFireTime  = m_fAttackFireTime  = m_fShootingPeriod ;
#line 512 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetHealth  (m_fHealth );m_fMaxHealth  = m_fHealth ;
#line 513 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(m_fFiringRangeFar  < m_fFiringRangeClose ){m_fFiringRangeFar  = m_fFiringRangeClose  + 1.0f;}
#line 516 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
GetModelObject  () -> StretchModel  (FLOAT3D (m_fSize  , m_fSize  , m_fSize ));
#line 518 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
ModelChangeNotify  ();
#line 519 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
StandingAnim  ();
#line 523 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetTimerAfter(0.05f);
Jump(STATE_CURRENT, 0x01590018, FALSE, EBegin());return TRUE;}BOOL CCannonStatic::H0x01590018_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590018
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01590019, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CCannonStatic::H0x01590019_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01590019
;
#line 524 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
SetDesiredTranslation  (FLOAT3D (0.0f , 0.0f , 0.0f));
#line 525 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
UpdateFiringPos  ();
#line 527 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
if(! m_bActive ){Jump(STATE_CURRENT, STATE_CCannonStatic_Inactive, TRUE, EVoid());return TRUE;}
#line 528 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CannonStatic.es"
Jump(STATE_CURRENT, STATE_CCannonStatic_MainLoop, TRUE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};