/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"

#include "EntitiesMP/StdH/StdH.h"
#include "Models/Enemies/Mental/Mental.h"
#include "Models/CutSequences/CrateRider/Crate.h"

#include <EntitiesMP/CrateRider.h>
#include <EntitiesMP/CrateRider_tables.h>
#line 26 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"

// info structure
static EntityInfo eiCrate = {
  EIBT_FLESH, 500.0f,
  0.0f, 1.5f, 0.0f,     // source (eyes)
  0.0f, 1.0f, 0.0f,     // target (body)
};

#define GREET_SENSE_RANGE 10.0f
#define GREET_SENSE_DELAY 10.0f


void CCrateRider::SetDefaultProperties(void) {
  m_fnmHeadTex1 = CTString("");
  m_fnmHeadTex2 = CTString("");
  m_fnmDriveSnd = CTString("");
  CEnemyBase::SetDefaultProperties();
}
  
#line 71 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
void * CCrateRider::GetEntityInfo(void) 
#line 72 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
{
#line 73 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
return & eiCrate ;
#line 74 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 76 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::Precache(void) 
#line 77 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
{
#line 78 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
CEnemyBase  :: Precache  ();
#line 80 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
PrecacheClass  (CLASS_DEBRIS );
#line 82 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_apt1  . Precache  (m_fnmHeadTex1 );
#line 83 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_apt2  . Precache  (m_fnmHeadTex2 );
#line 84 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_aps  . Precache  (m_fnmDriveSnd );
#line 85 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 88 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
INDEX CCrateRider::AnimForDamage(FLOAT fDamage) {
#line 89 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
INDEX iAnim ;
#line 90 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
iAnim  = 0;
#line 91 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
StartModelAnim  (iAnim  , 0);
#line 92 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
return iAnim ;
#line 93 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 96 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
INDEX CCrateRider::AnimForDeath(void) {
#line 97 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
INDEX iAnim ;
#line 98 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
iAnim  = 0;
#line 99 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
StartModelAnim  (iAnim  , 0);
#line 100 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
return iAnim ;
#line 101 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 103 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::DeathNotify(void) {
#line 105 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
en_fDensity  = 500.0f;
#line 106 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 109 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::StandingAnim(void) {
#line 110 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
StartModelAnim  (CRATE_ANIM_DEFAULT  , AOF_LOOPING  | AOF_NORESTART  | AOF_SMOOTHCHANGE );
#line 112 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
CModelObject * pmo0  = & (GetModelObject  () -> GetAttachmentModel  (0) -> amo_moModelObject );
#line 113 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
pmo0  -> PlayAnim  (MENTAL_ANIM_CRATEANIMLEFTSEATING  , AOF_LOOPING  | AOF_NORESTART  | AOF_SMOOTHCHANGE );
#line 114 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
CModelObject * pmo1  = & (GetModelObject  () -> GetAttachmentModel  (1) -> amo_moModelObject );
#line 115 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
pmo1  -> PlayAnim  (MENTAL_ANIM_CRATEANIMRIGHTSEATING  , AOF_LOOPING  | AOF_NORESTART  | AOF_SMOOTHCHANGE );
#line 117 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_soSound  . Stop  ();
#line 118 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 119 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::WalkingAnim(void) {
#line 120 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
RunningAnim  ();
#line 121 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
StartModelAnim  (CRATE_ANIM_DRIVE  , AOF_LOOPING  | AOF_NORESTART );
#line 122 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 123 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::RunningAnim(void) 
#line 124 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
{
#line 125 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
if(m_fnmDriveSnd  != ""){
#line 126 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
PlaySound  (m_soSound  , m_fnmDriveSnd  , SOF_3D );
#line 127 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
#line 128 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
CModelObject * pmo0  = & (GetModelObject  () -> GetAttachmentModel  (0) -> amo_moModelObject );
#line 129 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
pmo0  -> PlayAnim  (MENTAL_ANIM_CRATEANIMLEFT  , AOF_LOOPING  | AOF_NORESTART );
#line 130 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
CModelObject * pmo1  = & (GetModelObject  () -> GetAttachmentModel  (1) -> amo_moModelObject );
#line 131 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
pmo1  -> PlayAnim  (MENTAL_ANIM_CRATEANIMRIGHT  , AOF_LOOPING  | AOF_NORESTART );
#line 133 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
StartModelAnim  (CRATE_ANIM_DRIVE  , AOF_LOOPING  | AOF_NORESTART );
#line 134 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 135 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::RotatingAnim(void) {
#line 136 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
RunningAnim  ();
#line 137 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 140 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::IdleSound(void) {
#line 142 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 144 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::SightSound(void) {
#line 146 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 147 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::WoundSound(void) {
#line 149 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 150 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::DeathSound(void) {
#line 152 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
  
#line 154 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::AddRider(INDEX i,const CTFileName & fnmHead) 
#line 155 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
{
#line 156 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
AddAttachment  (i  , MODEL_MENTAL  , TEXTURE_MENTAL );
#line 157 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
CModelObject * pmoMain  = & (GetModelObject  () -> GetAttachmentModel  (i ) -> amo_moModelObject );
#line 159 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
pmoMain  -> PlayAnim  (i  == 0 ? MENTAL_ANIM_CRATEANIMLEFT  : MENTAL_ANIM_CRATEANIMRIGHT  , AOF_LOOPING );
#line 160 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
AddAttachmentToModel  (this  , * pmoMain  , 0 , MODEL_HEAD  , TEXTURE_MENTAL  , 0 , 0 , 0);
#line 161 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
CModelObject * pmoHead  = & (pmoMain  -> GetAttachmentModel  (0) -> amo_moModelObject );
#line 162 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
if(fnmHead  != ""){
#line 164 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
try {
#line 165 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
pmoHead  -> mo_toTexture  . SetData_t  (fnmHead );
#line 167 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}catch  (const char  * strError ){
#line 169 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
CPrintF  ("%s\n" , (const char  *) strError );
#line 170 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
#line 171 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
#line 172 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
}
BOOL CCrateRider::
#line 179 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CCrateRider_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CCrateRider::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 181 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
InitAsModel  ();
#line 182 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
SetPhysicsFlags  (EPF_MODEL_WALKING  | EPF_HASLUNGS );
#line 183 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
SetCollisionFlags  (ECF_MODEL );
#line 184 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 185 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
SetHealth  (1.0f);
#line 186 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fMaxHealth  = 1.0f;
#line 187 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
en_tmMaxHoldBreath  = 5.0f;
#line 188 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
en_fDensity  = 2000.0f;
#line 189 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fBlowUpSize  = 2.0f;
#line 192 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
SetModel  (MODEL_CRATE );
#line 193 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
SetModelMainTexture  (TEXTURE_CRATE );
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
AddRider  (0 , m_fnmHeadTex1 );
#line 195 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
AddRider  (1 , m_fnmHeadTex2 );
#line 198 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fWalkSpeed  = 
#line 199 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fAttackRunSpeed  = 
#line 200 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fCloseRunSpeed  = 1.0f;
#line 201 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_aWalkRotateSpeed  = AngleDeg  (30.0f);
#line 202 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_aAttackRotateSpeed  = AngleDeg  (30);
#line 203 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_aCloseRotateSpeed  = AngleDeg  (30);
#line 205 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fAttackDistance  = 50.0f;
#line 206 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fCloseDistance  = 0.0f;
#line 207 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fStopDistance  = 5.0f;
#line 208 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fAttackFireTime  = 2.0f;
#line 209 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fCloseFireTime  = 1.0f;
#line 210 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fIgnoreRange  = 200.0f;
#line 212 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fBlowUpAmount  = 0.0f;
#line 213 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fBodyParts  = 4;
#line 214 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_fDamageWounded  = 1.0f;
#line 215 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_iScore  = 0;
#line 216 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_bBlind  = TRUE ;
#line 217 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
m_bRobotBlowup  = TRUE ;
#line 221 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
const FLOAT fSize  = 0.6f;
#line 222 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
GetModelObject  () -> StretchModel  (FLOAT3D (fSize  , fSize  , fSize ));
#line 223 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
ModelChangeNotify  ();
#line 224 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
StandingAnim  ();
#line 227 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CrateRider.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};