/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"

#include "EntitiesMP/StdH/StdH.h"
#include "EntitiesMP/WorldSettingsController.h"
#include "EntitiesMP/BackgroundViewer.h"

#include <EntitiesMP/CreditsHolder.h>
#include <EntitiesMP/CreditsHolder_tables.h>
#line 23 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"


#define CTA_LEFT 1
#define CTA_RIGHT 2
#define CTA_CENTER 3

class CCreditEntry {
public:
  CTString strTitle;
  CTString strName;
  CTString strQuote;
  INDEX    iAlign;
  INDEX    iX, iY;
  FLOAT    fRelSize;
  FLOAT    fWait;
};
  
static CStaticStackArray<CCreditEntry> _acceEntries;
#define BLANK_TIME 1.0f

void CCreditsHolder::SetDefaultProperties(void) {
  m_strName = "Credits holder";
  m_strDescription = "";
  m_fnmMessage = CTString("");
  m_fMyTimer = 0.0f;
  m_fMyTimerLast = 0.0f;
  m_iTotalEntries = 0;
  m_bEnd = FALSE ;
  m_penEndCreditsTrigger = NULL;
  m_bDataError = FALSE ;
  CRationalEntity::SetDefaultProperties();
}
  
#line 72 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
const CTString & CCreditsHolder::GetDescription(void)const {
#line 73 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
((CTString &) m_strDescription ) . PrintF  ("%s" , (const char  *) m_fnmMessage  . FileName  ());
#line 74 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return m_strDescription ;
#line 75 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
   CCreditsHolder::CCreditsHolder(void) 
#line 78 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 79 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
bDataLoaded  = FALSE ;
#line 80 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
  
#line 82 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
BOOL CCreditsHolder::ReloadData(void) 
#line 83 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 84 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
m_bDataError  = FALSE ;
#line 85 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(! Credits_On  (m_fnmMessage ))
#line 86 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 87 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
Credits_Off  ();
#line 88 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return FALSE ;
#line 89 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 90 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(! LoadFont  ())
#line 91 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 92 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
Credits_Off  ();
#line 93 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return FALSE ;
#line 94 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 95 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return TRUE ;
#line 96 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
  
#line 99 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
BOOL CCreditsHolder::LoadOneFile(const CTFileName & fnm) 
#line 100 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 101 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(fnm  == ""){return FALSE ;}
#line 103 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
try 
#line 104 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 106 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CTFileStream  strm ;
#line 107 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . Open_t  (fnm );
#line 109 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CTString strCheck ;
#line 110 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . GetLine_t  (strCheck );
#line 111 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strCheck  . TrimSpacesRight  ();
#line 112 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(strCheck  != "CREDITS"){return FALSE ;};
#line 114 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
m_iTotalEntries  = 0;
#line 115 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
while(! strm  . AtEOF  ())
#line 116 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 117 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CTString strLine ;
#line 118 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CTString strArgs ;
#line 119 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CTString strTmp ;
#line 120 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CCreditEntry  cceEntry ;
#line 122 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . GetLine_t  (strLine );
#line 123 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . GetLine_t  (strLine );
#line 124 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strLine  . TrimSpacesRight  ();
#line 125 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(strLine  == "END"){
#line 126 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . Close  ();
#line 127 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return TRUE ;
#line 128 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}else if(strLine  != "ENTRY"){
#line 129 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  . PopAll  ();
#line 130 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return FALSE ;
#line 131 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 132 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . GetLine_t  (strArgs );
#line 133 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strArgs  . ScanF  ("%d,%d" , & cceEntry  . iX  , & cceEntry  . iY );
#line 134 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . GetLine_t  (strArgs );
#line 135 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strArgs  . ScanF  ("%f" , & cceEntry  . fRelSize );
#line 136 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . GetLine_t  (strArgs );
#line 137 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strArgs  . TrimSpacesRight  ();
#line 138 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(strArgs  == "CENTER"){cceEntry  . iAlign  = CTA_CENTER ;}
#line 139 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
else if(strArgs  == "RIGHT"){cceEntry  . iAlign  = CTA_RIGHT ;}
#line 140 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
else if(TRUE ){cceEntry  . iAlign  = CTA_LEFT ;}
#line 141 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . GetLine_t  (cceEntry  . strTitle );
#line 142 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . GetLine_t  (cceEntry  . strName );
#line 143 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . GetLine_t  (cceEntry  . strQuote );
#line 144 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . GetLine_t  (strArgs );
#line 145 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strArgs  . ScanF  ("%f" , & cceEntry  . fWait );
#line 146 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  . Push  () = cceEntry ;
#line 147 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
m_iTotalEntries  ++;
#line 148 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 150 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
strm  . Close  ();
#line 151 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return TRUE ;
#line 152 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 153 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
catch  (const char  * strError )
#line 154 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 155 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CPrintF  ("%s\n" , (const char  *) strError );
#line 156 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return FALSE ;
#line 157 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 158 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
  
#line 160 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
BOOL CCreditsHolder::LoadFont() 
#line 161 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 162 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
try 
#line 163 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 164 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_fdMedium  . Load_t  (CTFILENAME  ("Fonts\\Display3-normal.fnt"));
#line 165 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 166 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
catch  (const char  * strError )
#line 167 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 168 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CPrintF  ("%s\n" , (const char  *) strError );
#line 169 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return FALSE ;
#line 170 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 171 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return TRUE ;
#line 172 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
  
#line 175 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
BOOL CCreditsHolder::Credits_On(CTFileName fnCreditsText) 
#line 176 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 177 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  . PopAll  ();
#line 178 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return LoadOneFile  (fnCreditsText );
#line 179 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
  
#line 182 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
void CCreditsHolder::Credits_Off(void) 
#line 183 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 184 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  . Clear  ();
#line 185 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
  
#line 188 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT CCreditsHolder::Credits_Render(CCreditsHolder * penThis,CDrawPort * pdp) 
#line 189 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 190 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(m_bDataError ){return 0;}
#line 192 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(! bDataLoaded ){
#line 193 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(! ReloadData  ()){
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
m_bDataError  = TRUE ;
#line 195 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return 0;
#line 196 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 197 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
bDataLoaded  = TRUE ;
#line 198 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return 1;
#line 199 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 202 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
PIX  pixH  = 0;
#line 204 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CTString strEmpty ;
#line 206 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fTime  = Lerp  (m_fMyTimerLast  , m_fMyTimer  , _pTimer  -> GetLerpFactor  ());
#line 207 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CDrawPort  * pdpCurr  = pdp ;
#line 209 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> Unlock  ();
#line 210 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdpCurr  -> Lock  ();
#line 213 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pixH  = pdpCurr  -> GetHeight  ();
#line 215 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fResFactor  = pixH  / 480.0f;
#line 217 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdpCurr  -> SetFont  (_pfdDisplayFont );
#line 220 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
BOOL bOver  = FALSE ;
#line 222 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fPassed  = 0.0f;
#line 223 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fStart  = 0.0f;
#line 224 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
INDEX iNextItem  = 0;
#line 226 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
for(INDEX i  = 0;i  < _acceEntries  . Count  ();i  ++){
#line 227 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(_acceEntries  [ i  ] . fWait  != 0.0f){
#line 228 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
fPassed  += _acceEntries  [ i  ] . fWait ;
#line 229 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(fPassed  > fTime ){
#line 230 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
break ;
#line 231 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}else {
#line 232 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
iNextItem  = i  + 1;
#line 233 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
fStart  = fPassed ;
#line 234 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(iNextItem  >= _acceEntries  . Count  ())
#line 235 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 236 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
bOver  = TRUE ;
#line 237 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 238 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 239 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 240 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 242 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(! bOver ){
#line 243 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
while(TRUE ){
#line 244 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
BOOL bLast  = FALSE ;
#line 245 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(_acceEntries  [ iNextItem  ] . fWait  != 0.0f){bLast  = TRUE ;};
#line 246 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fFade  = CalculateRatio  (fTime  , fStart  , fPassed  - BLANK_TIME  , 0.2f , 0.2f);
#line 247 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> SetFont  (_pfdDisplayFont );
#line 248 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> SetTextAspect  (1.0f);
#line 250 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fTextSize01  = 1.2f * _acceEntries  [ iNextItem  ] . fRelSize ;
#line 251 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fTextSize02  = 2.0f * _acceEntries  [ iNextItem  ] . fRelSize ;
#line 252 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fTextSize03  = 0.75f * _acceEntries  [ iNextItem  ] . fRelSize ;
#line 253 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fTextHeight  = 15.0f;
#line 254 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fSpacing01  = 1.2f;
#line 255 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fSpacing02  = 1.1f;
#line 257 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(_acceEntries  [ iNextItem  ] . iAlign  == CTA_CENTER ){
#line 258 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fYY  = _acceEntries  [ iNextItem  ] . iY  * fResFactor ;
#line 260 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> SetTextScaling  (fTextSize01  * fResFactor );
#line 261 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> PutTextC  (_acceEntries  [ iNextItem  ] . strTitle  , 
#line 262 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  [ iNextItem  ] . iX  * fResFactor  , fYY  , 
#line 263 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
C_WHITE  | (INDEX) (fFade  * 255));
#line 264 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
fYY  += fTextSize01  * fResFactor  * fTextHeight  * fSpacing01 ;
#line 266 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> SetFont  (& _fdMedium );
#line 267 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> SetTextScaling  (fTextSize02  * fResFactor );
#line 268 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> PutTextC  (_acceEntries  [ iNextItem  ] . strName  , 
#line 269 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  [ iNextItem  ] . iX  * fResFactor  , fYY  , 
#line 270 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
C_WHITE  | (INDEX) (fFade  * 255));
#line 271 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
fYY  += fTextSize02  * fResFactor  * fTextHeight  * fSpacing02 ;
#line 273 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> SetTextScaling  (fTextSize03  * fResFactor );
#line 274 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> PutTextC  (_acceEntries  [ iNextItem  ] . strQuote  , 
#line 275 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  [ iNextItem  ] . iX  * fResFactor  , fYY  , 
#line 276 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
C_WHITE  | (INDEX) (fFade  * 255));
#line 278 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}else if(_acceEntries  [ iNextItem  ] . iAlign  == CTA_RIGHT ){
#line 279 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fYY  = _acceEntries  [ iNextItem  ] . iY  * fResFactor ;
#line 281 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> SetTextScaling  (fTextSize01  * fResFactor );
#line 282 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> PutTextR  (_acceEntries  [ iNextItem  ] . strTitle  , 
#line 283 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  [ iNextItem  ] . iX  * fResFactor  , fYY  , 
#line 284 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
C_WHITE  | (INDEX) (fFade  * 255));
#line 285 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
fYY  += fTextSize01  * fResFactor  * fTextHeight  * fSpacing01 ;
#line 287 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> SetTextScaling  (fTextSize02  * fResFactor );
#line 288 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> PutTextR  (_acceEntries  [ iNextItem  ] . strName  , 
#line 289 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  [ iNextItem  ] . iX  * fResFactor  , fYY  , 
#line 290 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
C_WHITE  | (INDEX) (fFade  * 255));
#line 291 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
fYY  += fTextSize02  * fResFactor  * fTextHeight  * fSpacing02 ;
#line 293 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> SetTextScaling  (fTextSize03  * fResFactor );
#line 294 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> PutTextR  (_acceEntries  [ iNextItem  ] . strQuote  , 
#line 295 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  [ iNextItem  ] . iX  * fResFactor  , fYY  , 
#line 296 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
C_WHITE  | (INDEX) (fFade  * 255));
#line 298 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}else if(TRUE ){
#line 299 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
FLOAT fYY  = _acceEntries  [ iNextItem  ] . iY  * fResFactor ;
#line 301 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> SetTextScaling  (fTextSize01  * fResFactor );
#line 302 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> PutText  (_acceEntries  [ iNextItem  ] . strTitle  , 
#line 303 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  [ iNextItem  ] . iX  * fResFactor  , fYY  , 
#line 304 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
C_WHITE  | (INDEX) (fFade  * 255));
#line 305 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
fYY  += fTextSize01  * fResFactor  * fTextHeight  * fSpacing01 ;
#line 307 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> SetTextScaling  (fTextSize02  * fResFactor );
#line 308 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> PutText  (_acceEntries  [ iNextItem  ] . strName  , 
#line 309 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  [ iNextItem  ] . iX  * fResFactor  , fYY  , 
#line 310 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
C_WHITE  | (INDEX) (fFade  * 255));
#line 311 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
fYY  += fTextSize02  * fResFactor  * fTextHeight  * fSpacing02 ;
#line 313 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> SetTextScaling  (fTextSize03  * fResFactor );
#line 314 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> PutText  (_acceEntries  [ iNextItem  ] . strQuote  , 
#line 315 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
_acceEntries  [ iNextItem  ] . iX  * fResFactor  , fYY  , 
#line 316 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
C_WHITE  | (INDEX) (fFade  * 255));
#line 318 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 320 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
iNextItem  ++;
#line 321 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(iNextItem  >= _acceEntries  . Count  () || bLast ){
#line 322 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
bOver  = TRUE ;
#line 323 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
break ;
#line 324 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 325 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 326 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 328 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdpCurr  -> Unlock  ();
#line 329 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pdp  -> Lock  ();
#line 331 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(bOver ){
#line 332 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return 0;
#line 333 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}else {
#line 334 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return 1;
#line 335 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 336 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
BOOL CCreditsHolder::
#line 340 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
WaitScrollingToEnd(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CCreditsHolder_WaitScrollingToEnd
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CCreditsHolder::WaitScrollingToEnd expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 342 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
Jump(STATE_CURRENT,0x00f00003, FALSE, EInternal());return TRUE;}BOOL CCreditsHolder::H0x00f00003_WaitScrollingToEnd_03(const CEntityEvent &__eeInput)
#line 343 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f00003
if(!(! m_bEnd )){ Jump(STATE_CURRENT,0x00f00004, FALSE, EInternal());return TRUE;}
#line 344 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
SetTimerAfter(_pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x00f00001, FALSE, EBegin());return TRUE;}BOOL CCreditsHolder::H0x00f00001_WaitScrollingToEnd_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f00001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x00f00002, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CCreditsHolder::H0x00f00002_WaitScrollingToEnd_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f00002
;
#line 345 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
m_fMyTimerLast  = m_fMyTimer ;
#line 346 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
m_fMyTimer  += _pTimer  -> TickQuantum  / _pNetwork  -> GetRealTimeFactor  ();Jump(STATE_CURRENT,0x00f00003, FALSE, EInternal());return TRUE;
#line 347 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}BOOL CCreditsHolder::H0x00f00004_WaitScrollingToEnd_04(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f00004

#line 348 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
Return(STATE_CURRENT,EStop  ());
#line 348 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CCreditsHolder::
#line 351 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CCreditsHolder_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CCreditsHolder::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 353 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
InitAsEditorModel  ();
#line 354 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 355 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 358 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
SetModel  (MODEL_HOLDER );
#line 359 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
SetModelMainTexture  (TEXTURE_HOLDER );
#line 361 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
SetTimerAfter(0.05f);
Jump(STATE_CURRENT, 0x00f00005, FALSE, EBegin());return TRUE;}BOOL CCreditsHolder::H0x00f00005_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f00005
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x00f00006, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CCreditsHolder::H0x00f00006_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f00006
;
#line 363 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(! Credits_On  (m_fnmMessage ))
#line 364 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 365 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CPrintF  ("Error loading credits file '%s'!\n" , (const char  *) m_fnmMessage );
#line 366 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
Credits_Off  ();
#line 367 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
Return(STATE_CURRENT,EVoid());
#line 367 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return TRUE;
#line 368 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 369 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
m_bDataError  = FALSE ;
#line 371 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x00f00007, FALSE, EBegin());return TRUE;}BOOL CCreditsHolder::H0x00f00007_Main_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f00007
switch(__eeInput.ee_slEvent){case(EVENTCODE_EStart):
#line 373 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{const EStart&eStart= (EStart&)__eeInput;

#line 374 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CWorldSettingsController  * pwsc  = GetWSC  (this );
#line 375 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(pwsc  != NULL )
#line 376 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 377 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
m_fMyTimer  = 0;
#line 378 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
m_fMyTimerLast  = 0;
#line 379 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
ECredits  ecr ;
#line 380 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
ecr  . bStart  = TRUE ;
#line 381 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
ecr  . penSender  = this ;
#line 382 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pwsc  -> SendEvent  (ecr );
#line 383 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 384 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
Call(STATE_CURRENT, STATE_CCreditsHolder_WaitScrollingToEnd, TRUE, EVoid());return TRUE;
#line 385 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):
#line 387 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{const EStop&eStop= (EStop&)__eeInput;

#line 388 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
CWorldSettingsController  * pwsc  = GetWSC  (this );
#line 389 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(pwsc  != NULL )
#line 390 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
{
#line 391 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
ECredits  ecr ;
#line 392 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
ecr  . bStart  = FALSE ;
#line 393 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
ecr  . penSender  = this ;
#line 394 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
pwsc  -> SendEvent  (ecr );
#line 395 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 396 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
UnsetTimer();Jump(STATE_CURRENT,0x00f00008, FALSE, EInternal());return TRUE;
#line 397 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 398 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}return TRUE;}BOOL CCreditsHolder::H0x00f00008_Main_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f00008

#line 399 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
Credits_Off  ();
#line 400 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
if(m_penEndCreditsTrigger ){
#line 401 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
SendToTarget  (m_penEndCreditsTrigger  , EET_TRIGGER  , FixupCausedToPlayer  (this  , NULL  , FALSE ));
#line 402 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
}
#line 403 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
Return(STATE_CURRENT,EVoid());
#line 403 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/CreditsHolder.es"
return TRUE; ASSERT(FALSE); return TRUE;};