/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"

#include "EntitiesMP/StdH/StdH.h"
#include "EntitiesMP/Effector.h"
#include <EntitiesMP/BloodSpray.h>

#include <EntitiesMP/Effector.h>
#include <EntitiesMP/Effector_tables.h>
CEntityEvent *ESpawnEffector::MakeCopy(void) { CEntityEvent *peeCopy = new ESpawnEffector(*this); return peeCopy;}
ESpawnEffector::ESpawnEffector() : CEntityEvent(EVENTCODE_ESpawnEffector) {;
 ClearToDefault(eetType);
 ClearToDefault(vDamageDir);
 ClearToDefault(vDestination);
 ClearToDefault(tmLifeTime);
 ClearToDefault(fSize);
 ClearToDefault(ctCount);
 ClearToDefault(penModel);
 ClearToDefault(penModel2);
};
#line 52 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"

void CEffector_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) 
{
  switch ((EffectorEffectType)iUser)
  {
  case ET_MOVING_RING           :
    pdec->PrecacheModel(MODEL_POWER_RING);
    pdec->PrecacheTexture(TEXTURE_POWER_RING);
    break;
  case ET_DESTROY_OBELISK       :
  case ET_DESTROY_PYLON         :
  case ET_HIT_GROUND            :
  case ET_LIGHTNING             :
  case ET_SIZING_BIG_BLUE_FLARE :
  case ET_SIZING_RING_FLARE     :
  case ET_PORTAL_LIGHTNING      :
  case ET_MORPH_MODELS          :
  case ET_DISAPPEAR_MODEL       :
  case ET_APPEAR_MODEL          :
  case ET_DISAPPEAR_MODEL_NOW   :
  case ET_APPEAR_MODEL_NOW      :
    // no precaching needed
    break;
  default:
    ASSERT(FALSE);
  }
}

// array for model vertices in absolute space
CStaticStackArray<FLOAT3D> avModelFXVertices;

void CEffector::SetDefaultProperties(void) {
  m_eetType = ET_NONE ;
  m_tmStarted = 0.0f;
  m_vDamageDir = FLOAT3D(0 , 0 , 0);
  m_vFXDestination = FLOAT3D(0 , 0 , 0);
  m_tmLifeTime = 5.0f;
  m_fSize = 1.0f;
  m_ctCount = 0;
  m_bLightSource = FALSE ;
  m_aoLightAnimation.SetData(NULL);

  m_iLightAnimation = -1;
  m_bAlive = TRUE ;
  m_penModel = NULL;
  m_penModel2 = NULL;
  m_bWaitTrigger = FALSE ;
  CMovableModelEntity::SetDefaultProperties();
}
  
#line 119 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT CEffector::CalculateLifeRatio(FLOAT fFadeInRatio,FLOAT fFadeOutRatio) 
#line 120 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 121 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
TIME  tmDelta  = _pTimer  -> GetLerpedCurrentTick  () - m_tmStarted ;
#line 122 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fLifeRatio  = CalculateRatio  (tmDelta  , 0 , m_tmLifeTime  , fFadeInRatio  , fFadeOutRatio );
#line 123 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
return fLifeRatio ;
#line 124 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
  
#line 126 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
void CEffector::AdjustMipFactor(FLOAT & fMipFactor) 
#line 127 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 128 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_DISAPPEAR_MODEL  || (m_eetType  == ET_DISAPPEAR_MODEL_NOW  && m_penModel  != NULL ))
#line 129 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 130 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
CModelObject * pmo  = m_penModel  -> GetModelObject  ();
#line 131 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
TIME  tmDelta  = _pTimer  -> GetLerpedCurrentTick  () - m_tmStarted ;
#line 132 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fLifeRatio ;
#line 133 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_tmStarted  == - 1)
#line 134 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 135 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fLifeRatio  = 1.0f;
#line 136 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 137 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
else if(tmDelta  >= m_tmLifeTime )
#line 138 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 139 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fLifeRatio  = 0.0f;
#line 140 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 141 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
else 
#line 142 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 143 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fLifeRatio  = CalculateLifeRatio  (0.0f , 1.0f);
#line 144 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 145 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
UBYTE  ubAlpha  = UBYTE  (255.0f * fLifeRatio );
#line 146 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
COLOR col  = C_WHITE  | ubAlpha ;
#line 147 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
pmo  -> mo_colBlendColor  = col ;
#line 148 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 149 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_APPEAR_MODEL  || (m_eetType  == ET_APPEAR_MODEL_NOW  && m_penModel  != NULL ))
#line 150 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 151 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
CModelObject * pmo  = m_penModel  -> GetModelObject  ();
#line 152 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
TIME  tmDelta  = _pTimer  -> GetLerpedCurrentTick  () - m_tmStarted ;
#line 153 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fLifeRatio ;
#line 154 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_tmStarted  == - 1)
#line 155 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 156 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fLifeRatio  = 0.0f;
#line 157 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 158 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
else if(tmDelta  >= m_tmLifeTime )
#line 159 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 160 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fLifeRatio  = 1.0f;
#line 161 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 162 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
else 
#line 163 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 164 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fLifeRatio  = CalculateLifeRatio  (1.0f , 0.0f);
#line 165 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 166 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
UBYTE  ubAlpha  = UBYTE  (255.0f * fLifeRatio );
#line 167 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
COLOR col  = C_WHITE  | ubAlpha ;
#line 168 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
pmo  -> mo_colBlendColor  = col ;
#line 169 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 170 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_MORPH_MODELS  && m_penModel  != NULL  && m_penModel2  != NULL )
#line 171 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 172 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
CModelObject * pmo1  = m_penModel  -> GetModelObject  ();
#line 173 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
CModelObject * pmo2  = m_penModel2  -> GetModelObject  ();
#line 174 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
TIME  tmDelta  = _pTimer  -> GetLerpedCurrentTick  () - m_tmStarted ;
#line 175 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fLifeRatio ;
#line 176 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_tmStarted  == - 1)
#line 177 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 178 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fLifeRatio  = 0.0f;
#line 179 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 180 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
else if(tmDelta  >= m_tmLifeTime )
#line 181 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 182 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fLifeRatio  = 1.0f;
#line 183 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 184 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
else 
#line 185 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 186 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fLifeRatio  = CalculateLifeRatio  (1.0f , 0.0f);
#line 187 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 188 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
UBYTE  ubAlpha1  = UBYTE  (255.0f * (1 - fLifeRatio ));
#line 189 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
UBYTE  ubAlpha2  = 255 - ubAlpha1 ;
#line 190 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
COLOR col1  = C_WHITE  | ubAlpha1 ;
#line 191 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
COLOR col2  = C_WHITE  | ubAlpha2 ;
#line 192 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
pmo1  -> mo_colBlendColor  = col1 ;
#line 193 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
pmo2  -> mo_colBlendColor  = col2 ;
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 195 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
  
#line 197 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
BOOL CEffector::AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient) 
#line 198 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 199 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_MOVING_RING )
#line 200 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 201 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fLifeRatio  = CalculateLifeRatio  (0.2f , 0.1f);
#line 202 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fT  = _pTimer  -> CurrentTick  () - m_tmStarted ;
#line 203 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fPulse  = 1.0f;
#line 204 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
UBYTE  ub  = UBYTE  (255.0f * fPulse  * fLifeRatio );
#line 205 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
COLOR col  = RGBAToColor  (ub  , ub  , ub  , ub );
#line 206 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
GetModelObject  () -> mo_colBlendColor  = col ;
#line 207 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 209 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
return FALSE ;
#line 210 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
  
#line 212 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
void CEffector::RenderMovingLightnings(void) 
#line 213 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 215 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fLifeRatio  = CalculateLifeRatio  (0.1f , 0.1f);
#line 217 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_penModel  -> GetModelVerticesAbsolute  (avModelFXVertices  , 0.05f , 0.0f);
#line 218 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
const FLOATmatrix3D & m  = m_penModel  -> GetRotationMatrix  ();
#line 219 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT3D vOrigin  = m_penModel  -> GetPlacement  () . pl_PositionVector ;
#line 220 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fFXTime  = 0.75f;
#line 221 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fMaxHeight  = 6.0f;
#line 222 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fdh  = 1.0f;
#line 223 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT tmDelta  = _pTimer  -> GetLerpedCurrentTick  () - m_tmStarted ;
#line 224 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fY0  = tmDelta ;
#line 226 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
for(FLOAT fT  = tmDelta ;fT  > 0;fT  -= fFXTime )
#line 227 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 228 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fY  = fT  * 2.0f;
#line 229 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(fY  > fMaxHeight )
#line 230 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 231 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
continue ;
#line 232 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 234 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fHeightRatio  = CalculateRatio  (fY  , 0 , fMaxHeight  , 0.1f , 0.0f);
#line 235 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fMinY  = 1e6f;
#line 236 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fMinY2  = - 1e6f;
#line 237 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
INDEX iLower  = - 1;
#line 238 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
INDEX iUpper  = - 1;
#line 239 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
for(INDEX iVtx  = 0;iVtx  < avModelFXVertices  . Count  ();iVtx  ++)
#line 240 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 242 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT3D v  = (avModelFXVertices  [ iVtx  ] - vOrigin ) * ! m ;
#line 243 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(v  (2) > fY  && v  (2) < fMinY  && v  (1) < 0)
#line 244 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 245 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
iLower  = iVtx ;
#line 246 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fMinY  = v  (2);
#line 247 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 248 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(v  (2) <= fY  && v  (2) > fMinY2  && v  (1) < 0)
#line 249 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 250 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
iUpper  = iVtx ;
#line 251 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fMinY2  = v  (2);
#line 252 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 253 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 255 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(iLower  != - 1 && iUpper  != - 1)
#line 256 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 257 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT3D vRelHi  = (avModelFXVertices  [ iUpper  ] - vOrigin ) * ! m ;
#line 258 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT3D vRelLow  = (avModelFXVertices  [ iLower  ] - vOrigin ) * ! m ;
#line 259 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fLerpFactor  = (fY  - vRelLow  (2)) / (vRelHi  (2) - vRelLow  (2));
#line 260 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT3D vRel  = Lerp  (vRelLow  , vRelHi  , fLerpFactor );
#line 261 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
vRel  (2) = fY ;
#line 262 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT3D vAbs1  = vOrigin  + vRel  * m ;
#line 263 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
vRel  (1) = - vRel  (1);
#line 264 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT3D vAbs2  = vOrigin  + vRel  * m ;
#line 266 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
Particles_Ghostbuster  (vAbs1  , vAbs2  , 16 , 0.325f , fHeightRatio  * fLifeRatio  , 5.0f);
#line 267 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 268 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 269 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
avModelFXVertices  . Clear  ();
#line 270 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
  
#line 273 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
void CEffector::RenderParticles(void) 
#line 274 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 276 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fRatio ;
#line 277 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
TIME  tmNow  = _pTimer  -> GetLerpedCurrentTick  ();
#line 278 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
TIME  tmDelta  = tmNow  - m_tmStarted ;
#line 279 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fLivingRatio  = tmDelta  / m_tmLifeTime ;
#line 280 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(fLivingRatio  < 0.25f){
#line 281 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fRatio  = Clamp  (fLivingRatio  / 0.25f , 0.0f , 1.0f);
#line 282 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}else if(fLivingRatio  > 0.75f){
#line 283 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fRatio  = Clamp  ((- fLivingRatio  + 1.0f) / 0.25f , 0.0f , 1.0f);
#line 284 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}else {
#line 285 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
fRatio  = 1.0f;
#line 286 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 288 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
switch(m_eetType )
#line 289 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 290 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
case ET_DESTROY_OBELISK : 
#line 291 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
Particles_DestroyingObelisk  (this  , m_tmStarted );
#line 292 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
break ;
#line 293 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
case ET_DESTROY_PYLON : 
#line 294 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
Particles_DestroyingPylon  (this  , m_vDamageDir  , m_tmStarted );
#line 295 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
break ;
#line 296 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
case ET_HIT_GROUND : 
#line 297 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
Particles_HitGround  (this  , m_tmStarted  , m_fSize );
#line 298 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
break ;
#line 299 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
case ET_LIGHTNING : 
#line 300 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
Particles_Ghostbuster  (GetPlacement  () . pl_PositionVector  , m_vFXDestination  , m_ctCount  , m_fSize  , fRatio );
#line 301 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
break ;
#line 302 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
case ET_PORTAL_LIGHTNING : 
#line 303 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
RenderMovingLightnings  ();
#line 304 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
break ;
#line 305 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 306 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
  
#line 309 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
void CEffector::Read_t(CTStream * istr) 
#line 310 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 311 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
CMovableModelEntity  :: Read_t  (istr );
#line 313 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_bLightSource ){
#line 314 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
SetupLightSource  ();
#line 315 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 316 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
  
#line 319 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
CLightSource * CEffector::GetLightSource(void) 
#line 320 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 321 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_bLightSource  && ! IsPredictor  ()){
#line 322 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
return & m_lsLightSource ;
#line 323 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}else {
#line 324 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
return NULL ;
#line 325 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 326 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
  
#line 329 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
void CEffector::SetupLightSource(void) 
#line 330 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 331 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_iLightAnimation  >= 0)
#line 332 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 333 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
try {
#line 334 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_aoLightAnimation  . SetData_t  (CTFILENAME  ("Animations\\Effector.ani"));
#line 335 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}catch  (const char  * strError ){
#line 336 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
WarningMessage  (TRANS  ("Cannot load Animations\\Effector.ani: %s") , strError );
#line 337 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 339 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_aoLightAnimation  . GetData  () != NULL ){
#line 340 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_aoLightAnimation  . PlayAnim  (m_iLightAnimation  , 0);
#line 341 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 342 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 345 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
CLightSource  lsNew ;
#line 346 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_ulFlags  = LSF_LENSFLAREONLY ;
#line 347 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_rHotSpot  = 0.0f;
#line 348 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
switch(m_eetType ){
#line 349 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
case ET_SIZING_RING_FLARE : 
#line 350 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_colColor  = C_WHITE  | CT_OPAQUE ;
#line 351 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_rHotSpot  = 100.0f;
#line 352 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_rFallOff  = 300.0f;
#line 353 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStarNG ;
#line 354 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
break ;
#line 356 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
case ET_SIZING_BIG_BLUE_FLARE : 
#line 357 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_colColor  = C_WHITE  | CT_OPAQUE ;
#line 358 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_rHotSpot  = 500.0f * m_fSize ;
#line 359 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_rFallOff  = 1000.0f * m_fSize ;
#line 360 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_plftLensFlare  = & _lftBlueStarBlueReflections ;
#line 361 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
break ;
#line 363 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
default  : 
#line 364 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
ASSERTALWAYS  ("Unknown light source");
#line 365 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 366 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_ubPolygonalMask  = 0;
#line 367 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_paoLightAnimation  = NULL ;
#line 370 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_paoLightAnimation  = NULL ;
#line 371 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_aoLightAnimation  . GetData  () != NULL ){
#line 372 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
lsNew  . ls_paoLightAnimation  = & m_aoLightAnimation ;
#line 373 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 375 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_lsLightSource  . ls_penEntity  = this ;
#line 376 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_lsLightSource  . SetLightSource  (lsNew );
#line 377 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
BOOL CEffector::
#line 384 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEffector_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_ESpawnEffector, "CEffector::Main expects 'ESpawnEffector' as input!");  const ESpawnEffector &eSpawn = (const ESpawnEffector &)__eeInput;
#line 387 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
InitAsEditorModel  ();
#line 389 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL  | EPF_MOVABLE );
#line 390 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
SetCollisionFlags  (ECF_TOUCHMODEL );
#line 391 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
SetFlags  (GetFlags  () | ENF_SEETHROUGH );
#line 393 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
SetModel  (MODEL_MARKER );
#line 394 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
SetModelMainTexture  (TEXTURE_MARKER );
#line 397 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_eetType  = eSpawn  . eetType ;
#line 398 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_vDamageDir  = eSpawn  . vDamageDir ;
#line 399 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_tmStarted  = _pTimer  -> CurrentTick  ();
#line 400 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_tmLifeTime  = eSpawn  . tmLifeTime ;
#line 401 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_vFXDestination  = eSpawn  . vDestination ;
#line 402 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_fSize  = eSpawn  . fSize ;
#line 403 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_ctCount  = eSpawn  . ctCount ;
#line 404 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_bAlive  = TRUE ;
#line 405 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_penModel  = eSpawn  . penModel ;
#line 406 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_penModel2  = eSpawn  . penModel2 ;
#line 407 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_bWaitTrigger  = FALSE ;
#line 409 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
SetTimerAfter(0.1f);
Jump(STATE_CURRENT, 0x02600001, FALSE, EBegin());return TRUE;}BOOL CEffector::H0x02600001_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x02600001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x02600002, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CEffector::H0x02600002_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02600002
;
#line 411 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_MOVING_RING )
#line 412 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 413 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
SetModel  (MODEL_POWER_RING );
#line 414 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
SetModelMainTexture  (TEXTURE_POWER_RING );
#line 415 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
en_fAcceleration  = 1e6f;
#line 416 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fSpeed  = 550.0f;
#line 417 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
SetDesiredTranslation  (FLOAT3D (0 , - fSpeed  , 0));
#line 418 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fPathLen  = GetPlacement  () . pl_PositionVector  (2) - m_vFXDestination  (2);
#line 420 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_tmLifeTime  = fPathLen  / fSpeed ;
#line 421 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
SwitchToModel  ();
#line 422 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT fSize  = 36.0f;
#line 423 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
FLOAT3D vStretch  = FLOAT3D (fSize  , fSize  * 2.0f , fSize );
#line 424 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
GetModelObject  () -> StretchModel  (vStretch );
#line 425 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
ModelChangeNotify  ();
#line 426 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 428 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_SIZING_RING_FLARE )
#line 429 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 430 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_bLightSource  = TRUE ;
#line 431 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_iLightAnimation  = 0;
#line 432 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 433 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_SIZING_BIG_BLUE_FLARE )
#line 434 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 435 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_bLightSource  = TRUE ;
#line 436 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_iLightAnimation  = 1;
#line 437 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 438 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_MORPH_MODELS  || m_eetType  == ET_DISAPPEAR_MODEL  || m_eetType  == ET_APPEAR_MODEL )
#line 439 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 440 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_bWaitTrigger  = TRUE ;
#line 441 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_tmStarted  = - 1;
#line 442 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 443 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_DISAPPEAR_MODEL_NOW  || m_eetType  == ET_APPEAR_MODEL_NOW )
#line 444 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 445 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_bWaitTrigger  = FALSE ;
#line 446 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_tmStarted  = _pTimer  -> CurrentTick  ();
#line 447 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 450 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_bLightSource ){SetupLightSource  ();}
#line 454 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
Jump(STATE_CURRENT,0x02600005, FALSE, EInternal());return TRUE;}BOOL CEffector::H0x02600005_Main_05(const CEntityEvent &__eeInput)
#line 455 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02600005
if(!(((_pTimer  -> CurrentTick  () < m_tmStarted  + m_tmLifeTime ) && m_bAlive ) || m_bWaitTrigger )){ Jump(STATE_CURRENT,0x02600006, FALSE, EInternal());return TRUE;}
#line 456 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
SetTimerAfter(0.25f);
Jump(STATE_CURRENT, 0x02600003, FALSE, EBegin());return TRUE;}BOOL CEffector::H0x02600003_Main_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x02600003
switch(__eeInput.ee_slEvent)
#line 457 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETrigger):
#line 460 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{const ETrigger&e= (ETrigger&)__eeInput;

#line 461 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_MORPH_MODELS  || m_eetType  == ET_DISAPPEAR_MODEL  || m_eetType  == ET_APPEAR_MODEL )
#line 462 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 463 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_tmStarted  = _pTimer  -> CurrentTick  ();
#line 464 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_bWaitTrigger  = FALSE ;
#line 466 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_bAlive  = TRUE ;
#line 467 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 468 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
return TRUE;
#line 469 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x02600004, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 471 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}return TRUE;}BOOL CEffector::H0x02600004_Main_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02600004

#line 473 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_MOVING_RING )
#line 474 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 475 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
if(GetPlacement  () . pl_PositionVector  (2) < m_vFXDestination  (2))
#line 476 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
{
#line 477 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
m_bAlive  = FALSE ;
#line 478 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}
#line 479 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}Jump(STATE_CURRENT,0x02600005, FALSE, EInternal());return TRUE;
#line 480 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
}BOOL CEffector::H0x02600006_Main_06(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02600006

#line 482 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
Destroy  ();
#line 483 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
Return(STATE_CURRENT,EVoid());
#line 483 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Effector.es"
return TRUE; ASSERT(FALSE); return TRUE;};