/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"

#include "EntitiesMP/StdH/StdH.h"

#include <EntitiesMP/EnemyFly.h>
#include <EntitiesMP/EnemyFly_tables.h>
void CEnemyFly::SetDefaultProperties(void) {
  m_EeftType = EFT_FLY_GROUND_AIR ;
  m_bInAir = FALSE ;
  m_bAirAttack = FALSE ;
  m_bStartInAir = FALSE ;
  m_fGroundToAirSpeed = 2.0f;
  m_fAirToGroundSpeed = 4.0f;
  m_fAirToGroundMin = 1.0f;
  m_fAirToGroundMax = 2.0f;
  m_fFlyHeight = 2.0f;
  m_fFlyWalkSpeed = 1.0f;
  m_aFlyWalkRotateSpeed = AngleDeg(10.0f);
  m_fFlyAttackRunSpeed = 1.0f;
  m_aFlyAttackRotateSpeed = AngleDeg(10.0f);
  m_fFlyCloseRunSpeed = 1.0f;
  m_aFlyCloseRotateSpeed = AngleDeg(10.0f);
  m_fFlyAttackDistance = 50.0f;
  m_fFlyCloseDistance = 10.0f;
  m_fFlyAttackFireTime = 2.0f;
  m_fFlyCloseFireTime = 1.0f;
  m_fFlyStopDistance = 0.0f;
  m_fFlyIgnoreRange = 200.0f;
  m_fFlyLockOnEnemyTime = 0.0f;
  m_bFlyToMarker = FALSE ;
  CEnemyBase::SetDefaultProperties();
}
  FLOAT & CEnemyFly::GetProp(FLOAT & m_fBase) 
#line 77 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
{
#line 78 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(m_bInAir ){
#line 79 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return * ((& m_fBase ) + (& m_fFlyWalkSpeed  - & m_fWalkSpeed ));
#line 80 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}else {
#line 81 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return m_fBase ;
#line 82 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
#line 83 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
  FLOAT3D CEnemyFly::PlayerDestinationPos(void) 
#line 87 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
{
#line 89 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(! m_bInAir ){
#line 91 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return CEnemyBase  :: PlayerDestinationPos  ();
#line 92 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
#line 95 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
FLOAT fDist  = CalcDist  (m_penEnemy );
#line 97 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
FLOAT fHeight ;
#line 99 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(fDist  <= m_fFlyCloseDistance ){
#line 101 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
fHeight  = m_fFlyHeight ;
#line 103 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}else {
#line 105 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
fHeight  = m_fFlyHeight  + fDist  / 5.0f;
#line 106 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
#line 109 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return 
#line 110 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_penEnemy  -> GetPlacement  () . pl_PositionVector  
#line 111 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
+ FLOAT3D (m_penEnemy  -> en_mRotation  (1 , 2) , m_penEnemy  -> en_mRotation  (2 , 2) , m_penEnemy  -> en_mRotation  (3 , 2)) 
#line 112 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
* fHeight ;
#line 113 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
  
#line 116 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
void CEnemyFly::StartPathFinding(void) 
#line 117 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
{
#line 118 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(m_bInAir ){
#line 119 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_dtDestination  = DT_PLAYERSPOTTED ;
#line 120 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_vPlayerSpotted  = PlayerDestinationPos  ();
#line 121 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}else {
#line 122 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
CEnemyBase  :: StartPathFinding  ();
#line 123 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
#line 124 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
  void CEnemyFly::AdjustDifficulty(void) 
#line 127 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
{
#line 128 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
FLOAT fMoveSpeed  = GetSP  () -> sp_fEnemyMovementSpeed ;
#line 129 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
FLOAT fAttackSpeed  = GetSP  () -> sp_fEnemyMovementSpeed ;
#line 131 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_fFlyAttackFireTime  *= 1 / fAttackSpeed ;
#line 132 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_fFlyCloseFireTime  *= 1 / fAttackSpeed ;
#line 133 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_fFlyLockOnEnemyTime  *= 1 / fAttackSpeed ;
#line 136 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_fFlyAttackRunSpeed  *= fMoveSpeed ;
#line 137 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_aFlyAttackRotateSpeed  *= fMoveSpeed ;
#line 138 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_fFlyCloseRunSpeed  *= fMoveSpeed ;
#line 139 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_aFlyCloseRotateSpeed  *= fMoveSpeed ;
#line 140 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_fGroundToAirSpeed  *= fMoveSpeed ;
#line 141 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_fAirToGroundSpeed  *= fMoveSpeed ;
#line 143 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
CEnemyBase  :: AdjustDifficulty  ();
#line 144 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
  BOOL CEnemyFly::CanHitEnemy(CEntity * penTarget,FLOAT fCosAngle) {
#line 148 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(IsInPlaneFrustum  (penTarget  , fCosAngle )){
#line 149 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return IsVisibleCheckAll  (penTarget );
#line 150 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
#line 151 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return FALSE ;
#line 152 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
  ULONG CEnemyFly::SetDesiredMovement(void) 
#line 160 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
{
#line 162 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(! m_bInAir ){
#line 164 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return CEnemyBase  :: SetDesiredMovement  ();
#line 165 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
#line 168 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
ULONG  ulFlags  = CEnemyBase  :: SetDesiredMovement  ();
#line 171 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(m_fMoveSpeed  > 0.0f){
#line 173 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
FLOAT3D vTranslation  = (m_vDesiredPosition  - GetPlacement  () . pl_PositionVector ) * ! en_mRotation ;
#line 174 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
vTranslation  (1) = 0.0f;
#line 175 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(vTranslation  (3) > 0){
#line 176 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
vTranslation  (3) = 0.0f;
#line 177 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
#line 178 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
vTranslation  . Normalize  ();
#line 179 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
vTranslation  *= m_fMoveSpeed ;
#line 180 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetDesiredTranslation  (vTranslation );
#line 181 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
#line 183 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return ulFlags ;
#line 184 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
  
#line 190 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
void CEnemyFly::SetEntityPosition() {
#line 191 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
switch(m_EeftType ){
#line 192 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
case EFT_GROUND_ONLY : 
#line 193 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
case EFT_FLY_GROUND_GROUND : 
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bAirAttack  = FALSE ;
#line 195 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bStartInAir  = m_bInAir  = FALSE ;
#line 196 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bFlyToMarker  = FALSE ;
#line 197 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetPhysicsFlags  ((GetPhysicsFlags  () & ~ EPF_MODEL_FLYING ) | EPF_MODEL_WALKING );
#line 198 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
ChangeCollisionToGround  ();
#line 199 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
break ;
#line 201 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
case EFT_FLY_GROUND_AIR : 
#line 202 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bAirAttack  = TRUE ;
#line 203 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bStartInAir  = m_bInAir  = FALSE ;
#line 204 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bFlyToMarker  = FALSE ;
#line 205 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetPhysicsFlags  ((GetPhysicsFlags  () & ~ EPF_MODEL_FLYING ) | EPF_MODEL_WALKING );
#line 206 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
ChangeCollisionToGround  ();
#line 207 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
break ;
#line 209 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
case EFT_FLY_AIR_GROUND : 
#line 210 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bAirAttack  = FALSE ;
#line 211 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bStartInAir  = m_bInAir  = TRUE ;
#line 212 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bFlyToMarker  = TRUE ;
#line 213 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetPhysicsFlags  ((GetPhysicsFlags  () & ~ EPF_MODEL_WALKING ) | EPF_MODEL_FLYING );
#line 214 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
ChangeCollisionToAir  ();
#line 215 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
break ;
#line 217 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
case EFT_FLY_ONLY : 
#line 218 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
case EFT_FLY_AIR_AIR : 
#line 219 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bAirAttack  = TRUE ;
#line 220 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bStartInAir  = m_bInAir  = TRUE ;
#line 221 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bFlyToMarker  = TRUE ;
#line 222 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetPhysicsFlags  ((GetPhysicsFlags  () & ~ EPF_MODEL_WALKING ) | EPF_MODEL_FLYING );
#line 223 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
ChangeCollisionToAir  ();
#line 224 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
break ;
#line 225 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
#line 226 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
StandingAnim  ();
#line 227 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
  FLOAT CEnemyFly::AirToGroundAnim(void) {return _pTimer  -> TickQuantum ;}
  FLOAT CEnemyFly::GroundToAirAnim(void) {return _pTimer  -> TickQuantum ;}
  void CEnemyFly::ChangeCollisionToAir(void) {}
  void CEnemyFly::ChangeCollisionToGround(void) {}
BOOL CEnemyFly::
#line 282 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
ReturnToStartPosition(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_ReturnToStartPosition
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::ReturnToStartPosition expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 284 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_BeIdle, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 320 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
BeWounded(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_BeWounded
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EDamage, "CEnemyFly::BeWounded expects 'EDamage' as input!");  const EDamage &eDamage = (const EDamage &)__eeInput;
#line 322 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(!(! (m_EeftType  != EFT_FLY_ONLY  && m_bInAir  && ((IRnd  () & 3) == 0)))){ Jump(STATE_CURRENT,0x01370006, FALSE, EInternal());return TRUE;}
#line 323 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_BeWounded, FALSE, eDamage );return TRUE;Jump(STATE_CURRENT,0x01370005, FALSE, EInternal());return TRUE;}BOOL CEnemyFly::H0x01370006_BeWounded_05(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370006
if(!(TRUE )){ Jump(STATE_CURRENT,0x01370004, FALSE, EInternal());return TRUE;}
#line 325 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bAirAttack  = FALSE ;
#line 326 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
STATE_CEnemyFly_AirToGround, TRUE;
Jump(STATE_CURRENT, 0x01370002, FALSE, EBegin());return TRUE;}BOOL CEnemyFly::H0x01370002_BeWounded_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370002
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyFly_AirToGround, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01370003, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CEnemyFly::H0x01370003_BeWounded_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370003
const EReturn&__e= (EReturn&)__eeInput;
;Jump(STATE_CURRENT,0x01370004, FALSE, EInternal());return TRUE;}BOOL CEnemyFly::H0x01370004_BeWounded_03(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370004
Jump(STATE_CURRENT,0x01370005, FALSE, EInternal());return TRUE;}
BOOL CEnemyFly::H0x01370005_BeWounded_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370005

#line 328 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Return(STATE_CURRENT,EReturn  ());
#line 328 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 337 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
AirToGround(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_AirToGround
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::AirToGround expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 340 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetDesiredTranslation  (FLOAT3D (0 , - m_fAirToGroundSpeed  , 0));
#line 341 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetDesiredRotation  (ANGLE3D (0 , 0 , 0));
#line 342 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
WalkingAnim  ();
#line 343 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x01370008, FALSE, EBegin());return TRUE;}BOOL CEnemyFly::H0x01370008_AirToGround_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370008
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETouch):{const ETouch&etouch= (ETouch&)__eeInput;

#line 347 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(etouch  . penOther  -> GetRenderType  () & RT_BRUSH ){
#line 348 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetDesiredTranslation  (FLOAT3D (0 , 0 , 0));
#line 349 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
UnsetTimer();Jump(STATE_CURRENT,0x01370009, FALSE, EInternal());return TRUE;
#line 350 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}
#line 351 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return TRUE;
#line 352 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;
return FALSE;}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 355 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}return TRUE;}BOOL CEnemyFly::H0x01370009_AirToGround_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370009

#line 357 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetPhysicsFlags  ((GetPhysicsFlags  () & ~ EPF_MODEL_FLYING ) | EPF_MODEL_WALKING );
#line 358 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bInAir  = FALSE ;
#line 359 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
ChangeCollisionToGround  ();
#line 361 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetTimerAfter(AirToGroundAnim  ());
Jump(STATE_CURRENT, 0x0137000a, FALSE, EBegin());return TRUE;}BOOL CEnemyFly::H0x0137000a_AirToGround_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0137000a
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x0137000b, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;
return FALSE;}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 366 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}return TRUE;}BOOL CEnemyFly::H0x0137000b_AirToGround_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0137000b

#line 367 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Return(STATE_CURRENT,EReturn  ());
#line 367 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 371 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
GroundToAir(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_GroundToAir
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::GroundToAir expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 374 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetPhysicsFlags  ((GetPhysicsFlags  () & ~ EPF_MODEL_WALKING ) | EPF_MODEL_FLYING );
#line 375 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
m_bInAir  = TRUE ;
#line 376 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetDesiredTranslation  (FLOAT3D (0 , m_fGroundToAirSpeed  , 0));
#line 377 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetDesiredRotation  (ANGLE3D (0 , 0 , 0));
#line 378 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
ChangeCollisionToAir  ();
#line 380 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetTimerAfter(GroundToAirAnim  ());
Jump(STATE_CURRENT, 0x0137000d, FALSE, EBegin());return TRUE;}BOOL CEnemyFly::H0x0137000d_GroundToAir_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0137000d
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;
return FALSE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x0137000e, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 385 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}return TRUE;}BOOL CEnemyFly::H0x0137000e_GroundToAir_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0137000e

#line 387 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
WalkingAnim  ();
#line 388 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetTimerAfter(Lerp  (m_fAirToGroundMin  , m_fAirToGroundMax  , FRnd  ()));
Jump(STATE_CURRENT, 0x0137000f, FALSE, EBegin());return TRUE;}BOOL CEnemyFly::H0x0137000f_GroundToAir_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0137000f
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;
return FALSE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01370010, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 393 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}return TRUE;}BOOL CEnemyFly::H0x01370010_GroundToAir_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370010

#line 394 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetDesiredTranslation  (FLOAT3D (0 , 0 , 0));
#line 395 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Return(STATE_CURRENT,EReturn  ());
#line 395 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 404 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
AttackEnemy(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_AttackEnemy
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::AttackEnemy expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 407 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(!(m_bAirAttack )){ Jump(STATE_CURRENT,0x0137001a, FALSE, EInternal());return TRUE;}
#line 409 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(!(! m_bInAir )){ Jump(STATE_CURRENT,0x01370014, FALSE, EInternal());return TRUE;}
#line 410 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
STATE_CEnemyFly_GroundToAir, TRUE;
Jump(STATE_CURRENT, 0x01370012, FALSE, EBegin());return TRUE;}BOOL CEnemyFly::H0x01370012_AttackEnemy_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370012
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyFly_GroundToAir, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01370013, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CEnemyFly::H0x01370013_AttackEnemy_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370013
const EReturn&__e= (EReturn&)__eeInput;
;Jump(STATE_CURRENT,0x01370014, FALSE, EInternal());return TRUE;}BOOL CEnemyFly::H0x01370014_AttackEnemy_03(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370014
Jump(STATE_CURRENT,0x01370019, FALSE, EInternal());return TRUE;}BOOL CEnemyFly::H0x0137001a_AttackEnemy_09(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0137001a
if(!(TRUE )){ Jump(STATE_CURRENT,0x01370018, FALSE, EInternal());return TRUE;}
#line 415 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(!(m_bInAir )){ Jump(STATE_CURRENT,0x01370017, FALSE, EInternal());return TRUE;}
#line 416 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
STATE_CEnemyFly_AirToGround, TRUE;
Jump(STATE_CURRENT, 0x01370015, FALSE, EBegin());return TRUE;}BOOL CEnemyFly::H0x01370015_AttackEnemy_04(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370015
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyFly_AirToGround, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01370016, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CEnemyFly::H0x01370016_AttackEnemy_05(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370016
const EReturn&__e= (EReturn&)__eeInput;
;Jump(STATE_CURRENT,0x01370017, FALSE, EInternal());return TRUE;}BOOL CEnemyFly::H0x01370017_AttackEnemy_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370017
Jump(STATE_CURRENT,0x01370018, FALSE, EInternal());return TRUE;}BOOL CEnemyFly::H0x01370018_AttackEnemy_07(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370018
Jump(STATE_CURRENT,0x01370019, FALSE, EInternal());return TRUE;}
BOOL CEnemyFly::H0x01370019_AttackEnemy_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01370019

#line 420 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_AttackEnemy, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 424 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Hit(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_Hit
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::Hit expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 426 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(m_bInAir ){
#line 427 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Jump(STATE_CURRENT, STATE_CEnemyFly_FlyHit, TRUE, EVoid());return TRUE;
#line 428 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}else {
#line 429 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Jump(STATE_CURRENT, STATE_CEnemyFly_GroundHit, TRUE, EVoid());return TRUE;
#line 430 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
} ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 434 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_Fire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::Fire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 436 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
if(m_bInAir ){
#line 437 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Jump(STATE_CURRENT, STATE_CEnemyFly_FlyFire, TRUE, EVoid());return TRUE;
#line 438 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
}else {
#line 439 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Jump(STATE_CURRENT, STATE_CEnemyFly_GroundFire, TRUE, EVoid());return TRUE;
#line 440 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
} ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 446 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Death(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_Death
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::Death expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 448 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetPhysicsFlags  ((GetPhysicsFlags  () & ~ EPF_MODEL_FLYING ) | EPF_MODEL_WALKING );
#line 449 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
ChangeCollisionToGround  ();
#line 450 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_Death, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 459 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
MainLoop(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_MainLoop
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::MainLoop expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 460 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
SetEntityPosition  ();
#line 461 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 465 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 466 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Return(STATE_CURRENT,EVoid());
#line 466 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 473 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
GroundHit(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_GroundHit
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::GroundHit expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 475 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Return(STATE_CURRENT,EReturn  ());
#line 475 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 478 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
GroundFire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_GroundFire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::GroundFire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 480 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Return(STATE_CURRENT,EReturn  ());
#line 480 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 484 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
FlyHit(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_FlyHit
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::FlyHit expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 486 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Return(STATE_CURRENT,EReturn  ());
#line 486 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemyFly::
#line 490 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
FlyFire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemyFly_FlyFire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemyFly::FlyFire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 492 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Return(STATE_CURRENT,EReturn  ());
#line 492 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnemyFly.es"
return TRUE; ASSERT(FALSE); return TRUE;};