/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"

#include "EntitiesMP/StdH/StdH.h"

#include <EntitiesMP/EnvironmentParticlesHolder.h>
#include <EntitiesMP/EnvironmentParticlesHolder_tables.h>
void CEnvironmentParticlesHolder::SetDefaultProperties(void) {
  m_strName = "Env. particles holder";
  m_strDescription = "";
  m_fnHeightMap = CTString("");
  m_boxHeightMap = FLOATaabbox3D(FLOAT3D (0 , 0 , 0) , FLOAT3D (1 , 1 , 1));
  m_eptType = EPTH_NONE ;
  m_penNextHolder = NULL;
  m_tmRainStart = -1.0f;
  m_tmRainEnd = -1.0f;
  m_tmSnowStart = -1.0f;
  m_tmSnowEnd = -1.0f;
  m_moHeightMapHolder.SetData(NULL);
m_moHeightMapHolder.mo_toTexture.SetData(NULL);
  m_moParticleTextureHolder.SetData(NULL);
m_moParticleTextureHolder.mo_toTexture.SetData(NULL);
  m_fnTexture = CTString("");
  m_fGrowthRenderingStep = 1.0f;
  m_fGrowthRenderingRadius = 50;
  m_fGrowthRenderingRadiusFade = 50;
  m_bGrowthHighresMap = TRUE ;
  m_iGrowthMapX = 1;
  m_iGrowthMapY = 1;
  m_fGrowthMinSize = 1.0f;
  m_fGrowthMaxSize = 1.0f;
  m_fParticlesSinkFactor = 0.0;
  m_fRainAppearLen = 10.0f;
  m_fSnowAppearLen = 10.0f;
  CRationalEntity::SetDefaultProperties();
}
  
#line 83 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
void CEnvironmentParticlesHolder::Precache(void) 
#line 84 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 85 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
CTextureData  * ptdHeightMap  = (CTextureData  *) m_moHeightMapHolder  . mo_toTexture  . GetData  ();
#line 86 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(ptdHeightMap  != NULL ){
#line 87 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
ptdHeightMap  -> Force  (TEX_CONSTANT  | TEX_STATIC  | TEX_KEEPCOLOR );
#line 88 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 89 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
  
#line 92 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
BOOL CEnvironmentParticlesHolder::IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget) 
#line 93 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 94 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(slPropertyOffset  == _offsetof  (CEnvironmentParticlesHolder  , m_penNextHolder ))
#line 95 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 96 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(IsOfClass  (penTarget  , "EnvironmentParticlesHolder")){return TRUE ;}
#line 97 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
else {return FALSE ;}
#line 98 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 99 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return CEntity  :: IsTargetValid  (slPropertyOffset  , penTarget );
#line 100 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
  
#line 103 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
FLOAT CEnvironmentParticlesHolder::GetRainFactor(void) 
#line 104 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 105 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
FLOAT fRainFactor  = 0.0f;
#line 106 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
TIME  tmNow  = _pTimer  -> GetLerpedCurrentTick  ();
#line 108 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(tmNow  > m_tmRainStart  && tmNow  < m_tmRainEnd  + m_fRainAppearLen )
#line 109 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 111 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(tmNow  > m_tmRainStart  + m_fRainAppearLen  && tmNow  < m_tmRainEnd )
#line 112 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 113 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
fRainFactor  = 1.0f;
#line 114 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 116 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
else if(tmNow  > m_tmRainEnd )
#line 117 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 118 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
fRainFactor  = 1.0f - (tmNow  - m_tmRainEnd ) / m_fRainAppearLen ;
#line 119 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 121 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
else 
#line 122 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 123 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
fRainFactor  = (tmNow  - m_tmRainStart ) / m_fRainAppearLen ;
#line 124 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 125 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 126 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return fRainFactor ;
#line 127 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
  
#line 130 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
FLOAT CEnvironmentParticlesHolder::GetSnowFactor(void) 
#line 131 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 132 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
FLOAT fSnowFactor  = 0.0f;
#line 133 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
TIME  tmNow  = _pTimer  -> GetLerpedCurrentTick  ();
#line 135 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(tmNow  > m_tmSnowStart  && tmNow  < m_tmSnowEnd  + m_fSnowAppearLen )
#line 136 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 138 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(tmNow  > m_tmSnowStart  + m_fSnowAppearLen  && tmNow  < m_tmSnowEnd )
#line 139 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 140 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
fSnowFactor  = 1.0f;
#line 141 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 143 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
else if(tmNow  > m_tmSnowEnd )
#line 144 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 145 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
fSnowFactor  = 1.0f - (tmNow  - m_tmSnowEnd ) / m_fSnowAppearLen ;
#line 146 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 148 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
else 
#line 149 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 150 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
fSnowFactor  = (tmNow  - m_tmSnowStart ) / m_fSnowAppearLen ;
#line 151 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 152 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 153 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return fSnowFactor ;
#line 154 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
  
#line 157 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
void CEnvironmentParticlesHolder::GetHeightMapData(CTextureData * & ptdHeightMap,FLOATaabbox3D & boxHeightMap) 
#line 158 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 159 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
ptdHeightMap  = (CTextureData  *) m_moHeightMapHolder  . mo_toTexture  . GetData  ();
#line 160 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(ptdHeightMap  != NULL ){
#line 161 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
ptdHeightMap  -> Force  (TEX_CONSTANT  | TEX_STATIC  | TEX_KEEPCOLOR );
#line 162 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 163 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
boxHeightMap  = m_boxHeightMap ;
#line 164 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
boxHeightMap  += GetPlacement  () . pl_PositionVector ;
#line 165 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
  
#line 167 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
void CEnvironmentParticlesHolder::GetParticleTexture() 
#line 168 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 170 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
BOOL CEnvironmentParticlesHolder::
#line 173 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnvironmentParticlesHolder_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnvironmentParticlesHolder::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 176 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
InitAsEditorModel  ();
#line 177 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 178 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 181 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(m_fnHeightMap  != CTString (""))
#line 182 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 183 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
try 
#line 184 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 185 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_moHeightMapHolder  . mo_toTexture  . SetData_t  (m_fnHeightMap );
#line 186 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}catch  (const char  * strError ){
#line 187 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
WarningMessage  (strError );
#line 188 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 189 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 191 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(m_fnTexture  != CTString (""))
#line 192 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 193 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
try 
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 195 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_moParticleTextureHolder  . mo_toTexture  . SetData_t  (m_fnTexture );
#line 196 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}catch  (const char  * strError ){
#line 197 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
WarningMessage  (strError );
#line 198 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 199 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 203 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(m_fGrowthRenderingRadius  < m_fGrowthRenderingRadiusFade ){
#line 204 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_fGrowthRenderingRadiusFade  = m_fGrowthRenderingRadius ;
#line 205 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 206 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_fParticlesSinkFactor  = Clamp  (m_fParticlesSinkFactor  , 0.0f , 1.0f);
#line 209 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
SetModel  (MODEL_ENVIRONMENT_PARTICLES_HOLDER );
#line 210 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
SetModelMainTexture  (TEXTURE_ENVIRONMENT_PARTICLES_HOLDER );
#line 212 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmRainStart  = 1e5f - 1.0f;
#line 213 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmRainEnd  = 1e5f;
#line 214 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmSnowStart  = 1e5f - 1.0f;
#line 215 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmSnowEnd  = 1e5f;
#line 217 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
switch(m_eptType ){
#line 218 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
case EPTH_GROWTH : 
#line 219 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_strDescription  = "Growth";
#line 220 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
break ;
#line 221 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
case EPTH_RAIN : 
#line 222 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_strDescription  = "Rain";
#line 223 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
break ;
#line 224 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
case EPTH_NONE : 
#line 225 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_strDescription  = "None";
#line 226 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
break ;
#line 227 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 229 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x00ed0000, FALSE, EBegin());return TRUE;}BOOL CEnvironmentParticlesHolder::H0x00ed0000_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00ed0000
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):
#line 232 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{const EBegin&e= (EBegin&)__eeInput;

#line 233 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return TRUE;
#line 234 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStart):
#line 236 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{const EStart&e= (EStart&)__eeInput;

#line 237 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
TIME  tmNow  = _pTimer  -> CurrentTick  ();
#line 238 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmRainStart  = tmNow ;
#line 239 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmRainEnd  = 1e6;
#line 240 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmSnowStart  = tmNow ;
#line 241 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmSnowEnd  = 1e6;
#line 242 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return TRUE;
#line 243 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):
#line 245 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{const EStop&e= (EStop&)__eeInput;

#line 246 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
TIME  tmNow  = _pTimer  -> CurrentTick  ();
#line 247 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmRainEnd  = tmNow ;
#line 248 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmSnowEnd  = tmNow ;
#line 249 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return TRUE;
#line 250 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 251 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}return TRUE;}BOOL CEnvironmentParticlesHolder::H0x00ed0001_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00ed0001

#line 253 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
Return(STATE_CURRENT,EVoid());
#line 253 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return TRUE; ASSERT(FALSE); return TRUE;};