/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"

#include "EntitiesMP/StdH/StdH.h"
#include "Models/Enemies/Gizmo/Gizmo.h"

#include <EntitiesMP/Gizmo.h>
#include <EntitiesMP/Gizmo_tables.h>
#line 25 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"

// info structure
static EntityInfo eiGizmo = {
  EIBT_FLESH, 100.0f,
  0.0f, 1.3f, 0.0f,     // source (eyes)
  0.0f, 1.0f, 0.0f,     // target (body)
};

#define EXPLODE_GIZMO   2.5f

void CGizmo::SetDefaultProperties(void) {
  m_bExploded = FALSE ;
  CEnemyBase::SetDefaultProperties();
}
  CTString CGizmo::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 61 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 62 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
CTString str ;
#line 63 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
str  . PrintF  (TRANSV  ("%s ate a marsh hopper") , (const char  *) strPlayerName );
#line 64 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
return str ;
#line 65 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
  const CTFileName & CGizmo::GetComputerMessageName(void)const {
#line 67 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
static DECLARE_CTFILENAME  (fnm  , "Data\\Messages\\Enemies\\Gizmo.txt");
#line 68 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
return fnm ;
#line 69 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
  
#line 71 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
void * CGizmo::GetEntityInfo(void) 
#line 72 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 73 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
return & eiGizmo ;
#line 74 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
  
#line 76 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
void CGizmo::Precache(void) 
#line 77 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 78 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
CEnemyBase  :: Precache  ();
#line 79 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
PrecacheSound  (SOUND_SIGHT );
#line 80 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
PrecacheSound  (SOUND_IDLE );
#line 81 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
PrecacheSound  (SOUND_JUMP );
#line 82 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
PrecacheSound  (SOUND_DEATH_JUMP );
#line 83 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
PrecacheClass  (CLASS_BASIC_EFFECT  , BET_GIZMO_SPLASH_FX );
#line 84 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
PrecacheClass  (CLASS_BLOOD_SPRAY );
#line 85 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
  
#line 87 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
void CGizmo::SightSound(void) {
#line 88 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
PlaySound  (m_soSound  , SOUND_SIGHT  , SOF_3D );
#line 89 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
  
#line 91 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
void CGizmo::RunningAnim(void) 
#line 92 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 93 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
StartModelAnim  (GIZMO_ANIM_RUN  , 0);
#line 94 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
  
#line 96 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
void CGizmo::MortalJumpAnim(void) 
#line 97 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 98 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
StartModelAnim  (GIZMO_ANIM_RUN  , 0);
#line 99 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
  
#line 101 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
void CGizmo::StandAnim(void) 
#line 102 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 103 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
StartModelAnim  (GIZMO_ANIM_IDLE  , AOF_LOOPING  | AOF_NORESTART );
#line 104 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
  
#line 107 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
void CGizmo::IdleSound(void) {
#line 108 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
PlaySound  (m_soSound  , SOUND_IDLE  , SOF_3D );
#line 109 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
  
#line 114 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
void CGizmo::BlowUpNotify(void) {
#line 115 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
Explode  ();
#line 116 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
  
#line 119 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
void CGizmo::Explode(void) 
#line 120 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 121 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
if(! m_bExploded )
#line 122 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 123 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_bExploded  = TRUE ;
#line 125 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
CPlacement3D plSpray  = GetPlacement  ();
#line 126 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
CEntity  * penSpray  = CreateEntity  (plSpray  , CLASS_BLOOD_SPRAY );
#line 127 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
penSpray  -> SetParent  (this );
#line 128 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
ESpawnSpray  eSpawnSpray ;
#line 129 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
eSpawnSpray  . colBurnColor  = C_WHITE  | CT_OPAQUE ;
#line 130 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
eSpawnSpray  . fDamagePower  = 2.0f;
#line 131 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
eSpawnSpray  . fSizeMultiplier  = 1.0f;
#line 132 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
eSpawnSpray  . sptType  = SPT_SLIME ;
#line 133 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
eSpawnSpray  . vDirection  = en_vCurrentTranslationAbsolute  / 8.0f;
#line 134 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
eSpawnSpray  . penOwner  = this ;
#line 135 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
penSpray  -> Initialize  (eSpawnSpray );
#line 138 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
CPlacement3D plSplash  = GetPlacement  ();
#line 139 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
CEntityPointer penSplash  = CreateEntity  (plSplash  , CLASS_BASIC_EFFECT );
#line 140 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
ESpawnEffect  ese ;
#line 141 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
ese  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 142 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
ese  . betType  = BET_GIZMO_SPLASH_FX ;
#line 143 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
penSplash  -> Initialize  (ese );
#line 144 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
#line 145 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
  
#line 149 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
BOOL CGizmo::ShouldBlowUp(void) 
#line 150 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 151 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
return TRUE ;
#line 152 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
  void CGizmo::LeaveStain(BOOL bGrow) 
#line 157 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 158 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
ESpawnEffect  ese ;
#line 159 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT3D vPoint ;
#line 160 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOATplane3D vPlaneNormal ;
#line 161 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT fDistanceToEdge ;
#line 163 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOATaabbox3D box ;
#line 164 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
GetBoundingBox  (box );
#line 167 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
if(GetNearestPolygon  (vPoint  , vPlaneNormal  , fDistanceToEdge ))
#line 168 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 170 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
if((vPoint  - GetPlacement  () . pl_PositionVector ) . Length  () < 0.5f)
#line 171 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 172 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT fStretch  = box  . Size  () . Length  ();
#line 174 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
ese  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 175 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
ese  . betType  = BET_GIZMOSTAIN ;
#line 176 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
ese  . vStretch  = FLOAT3D (fStretch  * 0.75f , fStretch  * 0.75f , 1.0f);
#line 177 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
ese  . vNormal  = FLOAT3D (vPlaneNormal );
#line 178 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
ese  . vDirection  = FLOAT3D (0 , 0 , 0);
#line 179 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT3D vPos  = vPoint  + ese  . vNormal  / 50.0f * (FRnd  () + 0.5f);
#line 180 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
CEntityPointer penEffect  = CreateEntity  (CPlacement3D (vPos  , ANGLE3D (0 , 0 , 0)) , CLASS_BASIC_EFFECT );
#line 181 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
penEffect  -> Initialize  (ese );
#line 182 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
#line 183 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
#line 184 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
BOOL CGizmo::
#line 191 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
PerformAttack(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGizmo_PerformAttack
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGizmo::PerformAttack expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 193 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
Jump(STATE_CURRENT,0x014f0005, FALSE, EInternal());return TRUE;}BOOL CGizmo::H0x014f0005_PerformAttack_05(const CEntityEvent &__eeInput)
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x014f0005
if(!(TRUE )){ Jump(STATE_CURRENT,0x014f0006, FALSE, EInternal());return TRUE;}
#line 197 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
if(ShouldCeaseAttack  ())
#line 198 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 199 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetTargetNone  ();
#line 200 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
Return(STATE_CURRENT,EReturn  ());
#line 200 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
return TRUE;
#line 201 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
#line 204 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetDesiredTranslation  (FLOAT3D (0.0f , 0.0f , 0.0f));
#line 205 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetDesiredRotation  (ANGLE3D (0 , 0 , 0));
#line 208 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT fWaitTime  = 0.25f + FRnd  () * 0.4f;
#line 209 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetTimerAfter(fWaitTime );
Jump(STATE_CURRENT, 0x014f0001, FALSE, EBegin());return TRUE;}BOOL CGizmo::H0x014f0001_PerformAttack_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x014f0001
switch(__eeInput.ee_slEvent)
#line 210 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ESound):{const ESound&e= (ESound&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EWatch):{const EWatch&e= (EWatch&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x014f0002, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 215 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}return TRUE;}BOOL CGizmo::H0x014f0002_PerformAttack_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x014f0002

#line 217 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
STATE_CGizmo_JumpOnce, TRUE;
Jump(STATE_CURRENT, 0x014f0003, FALSE, EBegin());return TRUE;}BOOL CGizmo::H0x014f0003_PerformAttack_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x014f0003
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CGizmo_JumpOnce, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x014f0004, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CGizmo::H0x014f0004_PerformAttack_04(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x014f0004
const EReturn&__e= (EReturn&)__eeInput;
;Jump(STATE_CURRENT,0x014f0005, FALSE, EInternal());return TRUE;
#line 218 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}BOOL CGizmo::H0x014f0006_PerformAttack_06(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x014f0006
 ASSERT(FALSE); return TRUE;};BOOL CGizmo::
#line 221 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
JumpOnce(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGizmo_JumpOnce
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGizmo::JumpOnce expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 225 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_vDesiredPosition  = m_penEnemy  -> GetPlacement  () . pl_PositionVector ;
#line 226 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fMoveFrequency  = 0.1f;
#line 228 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
if(CalcPlaneDist  (m_penEnemy ) < 10.0f)
#line 229 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 231 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fMoveSpeed  = m_fCloseRunSpeed  * 1.5f;
#line 232 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_aRotateSpeed  = m_aCloseRotateSpeed  * 0.5f;
#line 233 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT fSpeedX  = 0.0f;
#line 234 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT fSpeedY  = 10.0f;
#line 235 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT fSpeedZ  = - m_fMoveSpeed ;
#line 237 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
if(! IsInFrustum  (m_penEnemy  , CosFast  (30.0f)))
#line 238 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 240 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_aRotateSpeed  = m_aCloseRotateSpeed  * 1.5f;
#line 242 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
fSpeedY  /= 2.0f;
#line 243 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
fSpeedZ  /= 4.0f;
#line 244 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
PlaySound  (m_soSound  , SOUND_JUMP  , SOF_3D );
#line 245 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
#line 246 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
else 
#line 247 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 248 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
PlaySound  (m_soSound  , SOUND_DEATH_JUMP  , SOF_3D );
#line 249 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
#line 250 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT3D vTranslation  (fSpeedX  , fSpeedY  , fSpeedZ );
#line 251 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetDesiredTranslation  (vTranslation );
#line 252 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
MortalJumpAnim  ();
#line 253 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
#line 255 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
else 
#line 256 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 257 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fMoveSpeed  = m_fCloseRunSpeed ;
#line 258 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_aRotateSpeed  = m_aCloseRotateSpeed ;
#line 260 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT fSpeedX  = (FRnd  () - 0.5f) * 10.0f;
#line 261 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT fSpeedY  = FRnd  () * 5.0f + 5.0f;
#line 262 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT fSpeedZ  = - m_fMoveSpeed  - FRnd  () * 2.5f;
#line 263 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT3D vTranslation  (fSpeedX  , fSpeedY  , fSpeedZ );
#line 264 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetDesiredTranslation  (vTranslation );
#line 265 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
RunningAnim  ();
#line 266 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
PlaySound  (m_soSound  , SOUND_JUMP  , SOF_3D );
#line 267 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
#line 270 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
Jump(STATE_CURRENT,0x014f000a, FALSE, EInternal());return TRUE;}BOOL CGizmo::H0x014f000a_JumpOnce_03(const CEntityEvent &__eeInput)
#line 271 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x014f000a
if(!(TRUE )){ Jump(STATE_CURRENT,0x014f000b, FALSE, EInternal());return TRUE;}
#line 273 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fMoveSpeed  = 0.0f;
#line 274 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_aRotateSpeed  = m_aCloseRotateSpeed ;
#line 275 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
FLOAT3D vTranslation  = GetDesiredTranslation  ();
#line 276 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetDesiredMovement  ();
#line 277 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetDesiredTranslation  (vTranslation );
#line 279 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetTimerAfter(m_fMoveFrequency );
Jump(STATE_CURRENT, 0x014f0008, FALSE, EBegin());return TRUE;}BOOL CGizmo::H0x014f0008_JumpOnce_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x014f0008
switch(__eeInput.ee_slEvent)
#line 280 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ESound):{const ESound&e= (ESound&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EWatch):{const EWatch&e= (EWatch&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x014f0009, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETouch):
#line 286 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{const ETouch&etouch= (ETouch&)__eeInput;

#line 288 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
if(etouch  . penOther  -> GetRenderType  () & RT_BRUSH )
#line 289 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 290 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
Return(STATE_CURRENT,EReturn  ());
#line 290 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
return TRUE;
#line 291 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
#line 293 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
else if(IsDerivedFromClass  (etouch  . penOther  , "Player"))
#line 294 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
{
#line 295 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
InflictDirectDamage  (etouch  . penOther  , this  , DMT_IMPACT  , 10.0f , 
#line 296 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
GetPlacement  () . pl_PositionVector  , - en_vGravityDir );
#line 297 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetHealth  (- 10000.0f);
#line 298 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_vDamage  = FLOAT3D (0 , 10000 , 0);
#line 299 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SendEvent  (EDeath  ());
#line 300 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}
#line 302 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
return TRUE;
#line 303 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 304 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}return TRUE;}BOOL CGizmo::H0x014f0009_JumpOnce_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x014f0009
Jump(STATE_CURRENT,0x014f000a, FALSE, EInternal());return TRUE;
#line 305 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
}BOOL CGizmo::H0x014f000b_JumpOnce_04(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x014f000b
 ASSERT(FALSE); return TRUE;};BOOL CGizmo::
#line 311 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGizmo_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGizmo::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 313 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
InitAsModel  ();
#line 314 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetPhysicsFlags  (EPF_MODEL_WALKING  | EPF_HASLUNGS );
#line 315 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetCollisionFlags  (ECF_MODEL );
#line 316 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 317 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetHealth  (9.5f);
#line 318 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fMaxHealth  = 9.5f;
#line 319 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
en_tmMaxHoldBreath  = 5.0f;
#line 320 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
en_fDensity  = 2000.0f;
#line 321 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fBlowUpSize  = 2.0f;
#line 324 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetModel  (MODEL_GIZMO );
#line 325 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
SetModelMainTexture  (TEXTURE_GIZMO );
#line 327 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fWalkSpeed  = FRnd  () + 1.5f;
#line 328 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 10.0f + 500.0f);
#line 329 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fAttackRunSpeed  = FRnd  () * 5.0f + 15.0f;
#line 330 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_aAttackRotateSpeed  = AngleDeg  (FRnd  () * 100 + 600.0f);
#line 331 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fCloseRunSpeed  = FRnd  () * 5.0f + 15.0f;
#line 332 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_aCloseRotateSpeed  = AngleDeg  (360.0f);
#line 334 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fAttackDistance  = 400.0f;
#line 335 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fCloseDistance  = 250.0f;
#line 336 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fStopDistance  = 0.0f;
#line 337 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fAttackFireTime  = 2.0f;
#line 338 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fCloseFireTime  = 0.5f;
#line 339 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fIgnoreRange  = 500.0f;
#line 341 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fBlowUpAmount  = 0.0f;
#line 342 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fBodyParts  = 0;
#line 343 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_fDamageWounded  = 0.0f;
#line 344 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_iScore  = 500;
#line 345 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
m_sptType  = SPT_SLIME ;
#line 347 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
en_fDeceleration  = 150.0f;
#line 350 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
GetModelObject  () -> StretchModel  (FLOAT3D (1.25f , 1.25f , 1.25f));
#line 351 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
ModelChangeNotify  ();
#line 352 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
StandingAnim  ();
#line 355 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Gizmo.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};