/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"

#include "EntitiesMP/StdH/StdH.h"
//#include "ModelsMP/Enemies/Grunt/Grunt.h"

#include <EntitiesMP/GruntSka.h>
#include <EntitiesMP/GruntSka_tables.h>
#line 30 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"

#define STRETCH_SOLDIER   1.2f
#define STRETCH_COMMANDER 1.4f
  
// info structure
static EntityInfo eiGruntSoldier = {
  EIBT_FLESH, 200.0f,
  0.0f, 1.9f*STRETCH_SOLDIER, 0.0f,     // source (eyes)
  0.0f, 1.3f*STRETCH_SOLDIER, 0.0f,     // target (body)
};

static EntityInfo eiGruntCommander = {
  EIBT_FLESH, 250.0f,
  0.0f, 1.9f*STRETCH_COMMANDER, 0.0f,     // source (eyes)
  0.0f, 1.3f*STRETCH_COMMANDER, 0.0f,     // target (body)
};

#define FIREPOS_SOLDIER       FLOAT3D(0.07f, 1.36f, -0.78f)*STRETCH_SOLDIER
#define FIREPOS_COMMANDER_UP  FLOAT3D(0.09f, 1.45f, -0.62f)*STRETCH_COMMANDER
#define FIREPOS_COMMANDER_DN  FLOAT3D(0.10f, 1.30f, -0.60f)*STRETCH_COMMANDER

#define COMANDER_SMC_MODEL "ModelsSKA\\Enemies\\Grunt\\Commander.smc"
#define SOLIDER_SMC_MODEL "ModelsSKA\\Enemies\\Grunt\\Grunt.smc"

#define GRUNT_MESH      
#define GRUNT_SKELETON  
#define GRUNT_ANIMSET   
#define GRUNT_TEXTURE   

#define CLEAR_ANIM_TIME   0.2f

static INDEX idGrunt_Wound          = -1;
static INDEX idGrunt_Run            = -1;
static INDEX idGrunt_IdlePatrol     = -1;
static INDEX idGrunt_IdleAttack     = -1;
static INDEX idGrunt_Fire           = -1;
static INDEX idGrunt_Default        = -1;
static INDEX idGrunt_DeathForward   = -1;
static INDEX idGrunt_DeathBackward  = -1;
static INDEX idGrunt_GunModel       = -1;

static INDEX idGrund_NormalBox      = -1;
static INDEX idGrund_DeathBox       = -1;

static CTextureObject _toStar01;

#define SHP_BASE_TEXTURE 0


void CGruntSka::SetDefaultProperties(void) {
  m_gtType = GT_SOLDIER ;
  m_soFire1.SetOwner(this);
m_soFire1.Stop_internal();
  m_soFire2.SetOwner(this);
m_soFire2.Stop_internal();
  m_fMidBoneRot = 0.0f;
  m_miTest.Clear();

  CEnemyBase::SetDefaultProperties();
}
   CGruntSka::CGruntSka(void) 
#line 110 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
{
#line 112 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idGrunt_Wound  = ska_GetIDFromStringTable  ("Grunt_Wound");
#line 113 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idGrunt_Run  = ska_GetIDFromStringTable  ("Grunt_Run");
#line 114 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idGrunt_IdlePatrol  = ska_GetIDFromStringTable  ("Grunt_IdlePatrol");
#line 115 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idGrunt_IdleAttack  = ska_GetIDFromStringTable  ("Grunt_IdleAttack");
#line 116 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idGrunt_Fire  = ska_GetIDFromStringTable  ("Grunt_Fire");
#line 117 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idGrunt_Default  = ska_GetIDFromStringTable  ("Grunt_Default");
#line 118 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idGrunt_DeathForward  = ska_GetIDFromStringTable  ("Grunt_DeathForward");
#line 119 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idGrunt_DeathBackward  = ska_GetIDFromStringTable  ("Grunt_DeathBackward");
#line 120 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idGrunt_GunModel  = ska_GetIDFromStringTable  ("Flamer");
#line 123 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idGrund_NormalBox  = ska_GetIDFromStringTable  ("Normal");
#line 124 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idGrund_DeathBox  = ska_GetIDFromStringTable  ("Death");
#line 125 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 127 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::CreateTestModelInstance() 
#line 128 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
{
#line 129 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
try {
#line 130 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_miTest  . AddMesh_t  ((CTString) "ModelsSKA\\Test\\Arm\\Arm.bm");
#line 131 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_miTest  . AddSkeleton_t  ((CTString) "ModelsSKA\\Test\\Arm\\Arm.bs");
#line 132 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_miTest  . AddAnimSet_t  ((CTString) "ModelsSKA\\Test\\Arm\\Arm.ba");
#line 133 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_miTest  . AddTexture_t  ((CTString) "ModelsSKA\\Test\\Arm\\Objects\\Arm.tex" , "Arm" , NULL );
#line 134 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_miTest  . AddColisionBox  ("Default" , FLOAT3D (- 0.5f , 0.0f , - 0.5f) , FLOAT3D (0.5f , 2.0f , 0.5f));
#line 135 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}catch  (const char  * strErr ){
#line 136 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
FatalError  (strErr );
#line 137 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
#line 138 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 140 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::BuildGruntModel() 
#line 141 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
{
#line 144 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
en_pmiModelInstance  = CreateModelInstance  ("GruntSka");
#line 145 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
CModelInstance * pmi  = GetModelInstance  ();
#line 146 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
try {
#line 148 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddMesh_t  ((CTString) "ModelsSKA\\Enemies\\Grunt\\Grunt.bm");
#line 149 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddSkeleton_t  ((CTString) "ModelsSKA\\Enemies\\Grunt\\Grunt.bs");
#line 150 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddAnimSet_t  ((CTString) "ModelsSKA\\Enemies\\Grunt\\Grunt.ba");
#line 151 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddTexture_t  ((CTString) "ModelsSKA\\Enemies\\Grunt\\Soldier.tex" , "Grunt" , NULL );
#line 152 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddColisionBox  ("Default" , FLOAT3D (- 0.5f , 0.0f , - 0.5f) , FLOAT3D (0.5f , 2.0f , 0.5f));
#line 155 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
CModelInstance * pmiFlamer  = CreateModelInstance  ("Flamer");
#line 156 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> AddMesh_t  ((CTString) "ModelsSKA\\Weapons\\Flamer\\Flamer.bm");
#line 157 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> AddSkeleton_t  ((CTString) "ModelsSKA\\Weapons\\Flamer\\Flamer.bs");
#line 158 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> AddAnimSet_t  ((CTString) "ModelsSKA\\Weapons\\Flamer\\Flamer.ba");
#line 159 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> AddTexture_t  ((CTString) "ModelsSKA\\Weapons\\Flamer\\Flamer.tex" , "Flamer" , NULL );
#line 160 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> AddTexture_t  ((CTString) "ModelsSKA\\Enemies\\Grunt\\Lava04FX.tex" , "Lava04FX" , NULL );
#line 162 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> SetOffsetRot  (ANGLE3D (0 , 0 , 180));
#line 164 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddChild  (pmiFlamer );
#line 167 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
INDEX iParenBoneID  = ska_GetIDFromStringTable  ("R_Hand");
#line 168 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> SetParentBone  (iParenBoneID );
#line 171 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetSkaColisionInfo  ();
#line 172 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}catch  (const char  * strErr ){
#line 173 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
FatalError  (strErr );
#line 174 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
#line 175 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 177 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::BuildCommanderModel(CEntity * penGrunt) 
#line 178 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
{
#line 179 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetSkaModel  ("ModelsSKA\\Enemies\\Grunt\\CommanderNoGun.smc");
#line 180 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
CModelInstance * pmiFlamer  = NULL ;
#line 181 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
try {
#line 182 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  = ParseSmcFile_t  ("ModelsSKA\\Weapons\\Flamer\\Flamer.smc");
#line 183 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}catch  (const char  * strErr ){
#line 184 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
FatalError  (strErr );
#line 185 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
#line 187 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
INDEX iParenBoneID  = ska_GetIDFromStringTable  ("R_Hand");
#line 188 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
CModelInstance * pmi  = GetModelInstance  ();
#line 189 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddChild  (pmiFlamer );
#line 190 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> SetParentBone  (iParenBoneID );
#line 192 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> SetOffsetRot  (ANGLE3D (0 , 0 , 180));
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetSkaColisionInfo  ();
#line 195 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  CTString CGruntSka::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 270 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
{
#line 271 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
CTString str ;
#line 272 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
str  . PrintF  (TRANSV  ("A Grunt sent %s into the halls of Valhalla") , (const char  *) strPlayerName );
#line 273 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
return str ;
#line 274 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 277 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void * CGruntSka::GetEntityInfo(void) {
#line 278 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
if(m_gtType  == GT_SOLDIER ){
#line 279 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
return & eiGruntSoldier ;
#line 280 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}else if(m_gtType  == GT_COMMANDER ){
#line 281 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
return & eiGruntSoldier ;
#line 282 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}else {
#line 283 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
ASSERTALWAYS  ("Unknown grunt type!");
#line 284 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
return NULL ;
#line 285 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
#line 286 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  const CTFileName & CGruntSka::GetComputerMessageName(void)const {
#line 289 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
static DECLARE_CTFILENAME  (fnmSoldier  , "DataMP\\Messages\\Enemies\\GruntSoldier.txt");
#line 290 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
static DECLARE_CTFILENAME  (fnmCommander  , "DataMP\\Messages\\Enemies\\GruntCommander.txt");
#line 291 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
switch(m_gtType ){
#line 292 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
default  : ASSERT  (FALSE );
#line 293 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
case GT_SOLDIER : return fnmSoldier ;
#line 294 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
case GT_COMMANDER : return fnmCommander ;
#line 295 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
#line 296 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 298 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::Precache(void) {
#line 299 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
CEnemyBase  :: Precache  ();
#line 301 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
if(m_gtType  == GT_SOLDIER ){
#line 302 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_GRUNT_PROJECTILE_SOL );
#line 303 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
#line 304 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
if(m_gtType  == GT_COMMANDER ){
#line 305 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_GRUNT_PROJECTILE_COM );
#line 306 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
#line 308 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PrecacheSound  (SOUND_IDLE );
#line 309 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PrecacheSound  (SOUND_SIGHT );
#line 310 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PrecacheSound  (SOUND_WOUND );
#line 311 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PrecacheSound  (SOUND_FIRE );
#line 312 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PrecacheSound  (SOUND_DEATH );
#line 313 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 316 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 317 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 318 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
{
#line 319 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 320 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 323 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
INDEX CGruntSka::AnimForDamage(FLOAT fDamage) {
#line 324 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Wound  , AN_CLEAR  , 1 , 0);
#line 325 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
return idGrunt_Wound ;
#line 326 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 329 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
INDEX CGruntSka::AnimForDeath(void) {
#line 330 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
INDEX idAnimDeath ;
#line 331 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
FLOAT3D vFront ;
#line 332 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetHeadingDirection  (0 , vFront );
#line 333 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
FLOAT fDamageDir  = m_vDamage  % vFront ;
#line 334 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
if(fDamageDir  < 0){
#line 335 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idAnimDeath  = idGrunt_DeathBackward ;
#line 336 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}else {
#line 337 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
idAnimDeath  = idGrunt_DeathForward ;
#line 338 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
#line 340 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idAnimDeath  , AN_CLEAR  , 1 , 0);
#line 342 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
return idAnimDeath ;
#line 343 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 345 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
FLOAT CGruntSka::WaitForDust(FLOAT3D & vStretch) {
#line 347 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
vStretch  = FLOAT3D (1 , 1 , 2);
#line 348 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
if(GetModelInstance  () -> IsAnimationPlaying  (idGrunt_DeathBackward )){
#line 349 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
return 0.5f;
#line 350 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}else if(GetModelInstance  () -> IsAnimationPlaying  (idGrunt_DeathForward )){
#line 351 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
return 1.0f;
#line 352 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
#line 353 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
return - 1.0f;
#line 354 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 356 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::DeathNotify(void) {
#line 357 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
INDEX iBoxIndex  = GetModelInstance  () -> GetColisionBoxIndex  (idGrund_DeathBox );
#line 358 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
ASSERT  (iBoxIndex  >= 0);
#line 359 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
ChangeCollisionBoxIndexWhenPossible  (iBoxIndex );
#line 360 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
en_fDensity  = 500.0f;
#line 361 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 364 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::StandingAnim(void) {
#line 365 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_IdleAttack  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 366 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 371 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::RunningAnim(void) {
#line 372 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Run  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 373 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 374 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::WalkingAnim(void) {
#line 375 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
RunningAnim  ();
#line 376 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 377 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::RotatingAnim(void) {
#line 378 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
RunningAnim  ();
#line 379 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 382 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::IdleSound(void) {
#line 383 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soSound  , SOUND_IDLE  , SOF_3D );
#line 384 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 385 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::SightSound(void) {
#line 386 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soSound  , SOUND_SIGHT  , SOF_3D );
#line 387 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 388 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::WoundSound(void) {
#line 389 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soSound  , SOUND_WOUND  , SOF_3D );
#line 390 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 391 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::DeathSound(void) {
#line 392 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soSound  , SOUND_DEATH  , SOF_3D );
#line 393 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
  
#line 396 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::EnemyPostInit(void) 
#line 397 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
{
#line 399 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_soFire1  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 400 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_soFire2  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 401 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
BOOL CGruntSka::
#line 407 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGruntSka_Fire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGruntSka::Fire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 409 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
if(!(m_gtType  == GT_SOLDIER )){ Jump(STATE_CURRENT,0x01570008, FALSE, EInternal());return TRUE;}
#line 410 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
STATE_CGruntSka_SoldierAttack, TRUE;
Jump(STATE_CURRENT, 0x01570001, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570001_Fire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CGruntSka_SoldierAttack, TRUE, EVoid());return TRUE;case EVENTCODE_EEnd: Jump(STATE_CURRENT,0x01570002, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x01570002_Fire_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570002
const EEnd&__e= (EEnd&)__eeInput;
;Jump(STATE_CURRENT,0x01570007, FALSE, EInternal());return TRUE;}BOOL CGruntSka::H0x01570008_Fire_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570008
if(!(m_gtType  == GT_COMMANDER )){ Jump(STATE_CURRENT,0x01570006, FALSE, EInternal());return TRUE;}
#line 413 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
STATE_CGruntSka_CommanderAttack, TRUE;
Jump(STATE_CURRENT, 0x01570003, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570003_Fire_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570003
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CGruntSka_CommanderAttack, TRUE, EVoid());return TRUE;case EVENTCODE_EEnd: Jump(STATE_CURRENT,0x01570004, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x01570004_Fire_04(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570004
const EEnd&__e= (EEnd&)__eeInput;
;Jump(STATE_CURRENT,0x01570005, FALSE, EInternal());return TRUE;}BOOL CGruntSka::H0x01570006_Fire_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570006
{
#line 416 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
ASSERT  (FALSE );
#line 417 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}Jump(STATE_CURRENT,0x01570005, FALSE, EInternal());return TRUE;}
BOOL CGruntSka::H0x01570005_Fire_05(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570005
Jump(STATE_CURRENT,0x01570007, FALSE, EInternal());return TRUE;}
BOOL CGruntSka::H0x01570007_Fire_07(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570007

#line 418 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
Return(STATE_CURRENT,EReturn  ());
#line 418 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CGruntSka::
#line 422 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SoldierAttack(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGruntSka_SoldierAttack
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGruntSka::SoldierAttack expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 424 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
StandingAnimFight  ();
#line 425 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.2f + FRnd  () * 0.25f);
Jump(STATE_CURRENT, 0x0157000a, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x0157000a_SoldierAttack_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0157000b, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x0157000b_SoldierAttack_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000b
;
#line 427 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1.0f , 0);
#line 429 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_SOL  , FIREPOS_SOLDIER  , ANGLE3D (0 , 0 , 0));
#line 430 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire1  , SOUND_FIRE  , SOF_3D );
#line 432 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.15f + FRnd  () * 0.1f);
Jump(STATE_CURRENT, 0x0157000c, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x0157000c_SoldierAttack_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000c
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0157000d, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x0157000d_SoldierAttack_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000d
;
#line 433 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1.0f , 0);
#line 434 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_SOL  , FIREPOS_SOLDIER  , ANGLE3D (0 , 0 , 0));
#line 435 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire2  , SOUND_FIRE  , SOF_3D );
#line 438 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(FRnd  () * 0.333f);
Jump(STATE_CURRENT, 0x0157000e, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x0157000e_SoldierAttack_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000e
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0157000f, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x0157000f_SoldierAttack_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000f
;
#line 439 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
Return(STATE_CURRENT,EEnd  ());
#line 439 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CGruntSka::
#line 443 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
CommanderAttack(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGruntSka_CommanderAttack
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGruntSka::CommanderAttack expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 444 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
StandingAnimFight  ();
#line 445 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.2f + FRnd  () * 0.25f);
Jump(STATE_CURRENT, 0x01570011, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570011_CommanderAttack_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570011
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01570012, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x01570012_CommanderAttack_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570012
;
#line 455 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1 , 0);
#line 456 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_COM  , FIREPOS_COMMANDER_DN  , ANGLE3D (- 20 , 0 , 0));
#line 457 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire1  , SOUND_FIRE  , SOF_3D );
#line 459 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.035f);
Jump(STATE_CURRENT, 0x01570013, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570013_CommanderAttack_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570013
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01570014, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x01570014_CommanderAttack_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570014
;
#line 460 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1 , 0);
#line 461 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_COM  , FIREPOS_COMMANDER_DN  , ANGLE3D (- 10 , 0 , 0));
#line 462 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire2  , SOUND_FIRE  , SOF_3D );
#line 464 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.035f);
Jump(STATE_CURRENT, 0x01570015, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570015_CommanderAttack_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570015
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01570016, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x01570016_CommanderAttack_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570016
;
#line 465 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1 , 0);
#line 466 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_COM  , FIREPOS_COMMANDER_DN  , ANGLE3D (0 , 0 , 0));
#line 467 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire1  , SOUND_FIRE  , SOF_3D );
#line 469 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.035f);
Jump(STATE_CURRENT, 0x01570017, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570017_CommanderAttack_07(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570017
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01570018, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x01570018_CommanderAttack_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570018
;
#line 470 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1 , 0);
#line 471 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_COM  , FIREPOS_COMMANDER_DN  , ANGLE3D (10 , 0 , 0));
#line 472 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire2  , SOUND_FIRE  , SOF_3D );
#line 474 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.035f);
Jump(STATE_CURRENT, 0x01570019, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570019_CommanderAttack_09(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570019
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0157001a, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x0157001a_CommanderAttack_10(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157001a
;
#line 475 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1 , 0);
#line 476 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_COM  , FIREPOS_COMMANDER_DN  , ANGLE3D (20 , 0 , 0));
#line 477 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire2  , SOUND_FIRE  , SOF_3D );
#line 479 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(FRnd  () * 0.5f);
Jump(STATE_CURRENT, 0x0157001b, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x0157001b_CommanderAttack_11(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157001b
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0157001c, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x0157001c_CommanderAttack_12(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157001c
;
#line 480 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
Return(STATE_CURRENT,EEnd  ());
#line 480 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CGruntSka::
#line 486 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGruntSka_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGruntSka::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 488 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
InitAsSkaModel  ();
#line 489 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetPhysicsFlags  (EPF_MODEL_WALKING  | EPF_HASLUNGS );
#line 490 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetCollisionFlags  (ECF_MODEL );
#line 491 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 492 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
en_tmMaxHoldBreath  = 5.0f;
#line 493 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
en_fDensity  = 2000.0f;
#line 500 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
switch(m_gtType ){
#line 501 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
case GT_SOLDIER : 
#line 502 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetSkaModel  (SOLIDER_SMC_MODEL );
#line 506 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fWalkSpeed  = FRnd  () + 2.5f;
#line 507 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 10.0f + 500.0f);
#line 508 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fAttackRunSpeed  = FRnd  () + 6.5f;
#line 509 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_aAttackRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 510 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fCloseRunSpeed  = FRnd  () + 6.5f;
#line 511 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 513 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fAttackDistance  = 80.0f;
#line 514 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fCloseDistance  = 0.0f;
#line 515 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fStopDistance  = 8.0f;
#line 516 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fAttackFireTime  = 2.0f;
#line 517 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fCloseFireTime  = 1.0f;
#line 518 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fIgnoreRange  = 200.0f;
#line 520 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fBlowUpAmount  = 80.0f;
#line 521 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fBodyParts  = 4;
#line 522 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fDamageWounded  = 0.0f;
#line 523 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_iScore  = 500;
#line 524 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetHealth  (40.0f);
#line 525 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fMaxHealth  = 40.0f;
#line 527 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> StretchModel  (FLOAT3D (STRETCH_SOLDIER  , STRETCH_SOLDIER  , STRETCH_SOLDIER ));
#line 528 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
break ;
#line 530 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
case GT_COMMANDER : 
#line 532 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetSkaModel  (COMANDER_SMC_MODEL );
#line 535 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fWalkSpeed  = FRnd  () + 2.5f;
#line 536 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 10.0f + 500.0f);
#line 537 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fAttackRunSpeed  = FRnd  () + 8.0f;
#line 538 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_aAttackRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 539 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fCloseRunSpeed  = FRnd  () + 8.0f;
#line 540 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 542 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fAttackDistance  = 90.0f;
#line 543 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fCloseDistance  = 0.0f;
#line 544 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fStopDistance  = 15.0f;
#line 545 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fAttackFireTime  = 4.0f;
#line 546 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fCloseFireTime  = 2.0f;
#line 548 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fIgnoreRange  = 200.0f;
#line 550 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fBodyParts  = 5;
#line 551 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fDamageWounded  = 0.0f;
#line 552 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_iScore  = 800;
#line 553 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
SetHealth  (60.0f);
#line 554 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
m_fMaxHealth  = 60.0f;
#line 556 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> StretchModel  (FLOAT3D (STRETCH_COMMANDER  , STRETCH_COMMANDER  , STRETCH_COMMANDER ));
#line 557 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
break ;
#line 558 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
}
#line 560 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
ModelChangeNotify  ();
#line 561 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
StandingAnim  ();
#line 564 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/GruntSka.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};