/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"

#include "EntitiesMP/StdH/StdH.h"

#include <EntitiesMP/ModelDestruction.h>
#include <EntitiesMP/ModelDestruction_tables.h>
CEntityEvent *ERangeModelDestruction::MakeCopy(void) { CEntityEvent *peeCopy = new ERangeModelDestruction(*this); return peeCopy;}
ERangeModelDestruction::ERangeModelDestruction() : CEntityEvent(EVENTCODE_ERangeModelDestruction) {;
};
void CModelDestruction::SetDefaultProperties(void) {
  m_strName = "ModelDestruction";
  m_strDescription = "";
  m_penModel0 = NULL;
  m_penModel1 = NULL;
  m_penModel2 = NULL;
  m_penModel3 = NULL;
  m_penModel4 = NULL;
  m_fHealth = 50.0f;
  m_ddtDebris = DDT_STONE ;
  m_ctDebris = 3;
  m_fDebrisSize = 1.0f;
  m_eibtBodyType = EIBT_ROCK ;
  m_sptType = SPT_NONE ;
  m_fParticleSize = 1.0f;
  m_bRequireExplosion = FALSE ;
  m_fDebrisLaunchPower = 1.0f;
  m_dptParticles = DPT_NONE ;
  m_betStain = BET_NONE ;
  m_fLaunchCone = 45.0f;
  m_fRndRotH = 720.0f;
  m_fRndRotP = 720.0f;
  m_fRndRotB = 720.0f;
  m_fParticleLaunchPower = 1.0f;
  m_colParticles = COLOR(C_WHITE  | CT_OPAQUE );
  m_iStartAnim = -1;
  m_bDebrisImmaterialASAP = TRUE ;
  m_ctDustFall = 1;
  m_fMinDustFallHeightRatio = 0.1f;
  m_fMaxDustFallHeightRatio = 0.6f;
  m_fDustStretch = 1.0f;
  m_fDebrisDustRandom = 0.25f;
  m_fDebrisDustStretch = 1.0f;
  m_penShake = NULL;
  CEntity::SetDefaultProperties();
}
  
#line 100 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
void CModelDestruction::Precache(void) {
#line 101 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
PrecacheClass  (CLASS_BASIC_EFFECT  , BET_EXPLOSIONSTAIN );
#line 102 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
switch(m_ddtDebris ){
#line 103 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
case DDT_STONE : {
#line 104 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
PrecacheModel  (MODEL_STONE );
#line 105 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
PrecacheTexture  (TEXTURE_STONE );
#line 106 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}break ;
#line 107 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
case DDT_WOOD : {
#line 108 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
PrecacheModel  (MODEL_WOOD );
#line 109 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
PrecacheTexture  (TEXTURE_WOOD );
#line 110 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}break ;
#line 111 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
case DDT_PALM : {
#line 112 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
PrecacheModel  (MODEL_WOOD );
#line 113 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
PrecacheTexture  (TEXTURE_WOOD );
#line 114 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}break ;
#line 115 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 116 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
  
#line 119 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CAnimData * CModelDestruction::GetAnimData(SLONG slPropertyOffset) 
#line 120 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 121 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(slPropertyOffset  == _offsetof  (CModelDestruction  , m_iStartAnim ))
#line 122 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 123 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CModelHolder2  * pmh  = GetModel  (0);
#line 124 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(pmh  != NULL )
#line 125 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 126 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
return pmh  -> GetModelObject  () -> GetData  ();
#line 127 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 128 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 129 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
return CEntity  :: GetAnimData  (slPropertyOffset );
#line 130 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
  
#line 132 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
const CTString & CModelDestruction::GetDescription(void)const {
#line 133 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
INDEX ct  = GetModelsCount  ();
#line 134 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(ct  == 0){
#line 135 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
((CTString &) m_strDescription ) . PrintF  ("(%g): no more" , m_fHealth );
#line 136 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}else if(ct  == 1){
#line 137 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
((CTString &) m_strDescription ) . PrintF  ("(%g): %s" , m_fHealth  , (const char  *) m_penModel0  -> GetName  ());
#line 138 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}else if(TRUE ){
#line 139 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
((CTString &) m_strDescription ) . PrintF  ("(%g): %s,...(%d)" , m_fHealth  , (const char  *) m_penModel0  -> GetName  () , ct );
#line 140 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 141 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
return m_strDescription ;
#line 142 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
  
#line 145 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
void CModelDestruction::CheckOneModelTarget(CEntityPointer & pen) 
#line 146 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 147 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(pen  != NULL  && ! IsOfClass  (pen  , "ModelHolder2")){
#line 148 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
WarningMessage  ("Model '%s' is not ModelHolder2!" , (const char  *) pen  -> GetName  ());
#line 149 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
pen  = NULL ;
#line 150 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 151 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
  
#line 154 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
class CModelHolder2 * CModelDestruction::GetNextPhase(void) 
#line 155 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 156 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
INDEX ct  = GetModelsCount  ();
#line 158 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(ct  == 0){
#line 160 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
return NULL ;
#line 162 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}else {
#line 164 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
return GetModel  (IRnd  () % ct );
#line 165 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 166 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
  
#line 169 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
INDEX CModelDestruction::GetModelsCount(void)const 
#line 170 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 172 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(m_penModel0  == NULL ){return 0;};
#line 173 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(m_penModel1  == NULL ){return 1;};
#line 174 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(m_penModel2  == NULL ){return 2;};
#line 175 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(m_penModel3  == NULL ){return 3;};
#line 176 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(m_penModel4  == NULL ){return 4;};
#line 177 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
return 5;
#line 178 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
  
#line 180 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
class CModelHolder2 * CModelDestruction::GetModel(INDEX iModel) 
#line 181 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 182 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
ASSERT  (iModel  <= GetModelsCount  ());
#line 183 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
iModel  = Clamp  (iModel  , INDEX (0) , GetModelsCount  ());
#line 184 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
return (CModelHolder2  *) (& m_penModel0 ) [ iModel  ] . ep_pen ;
#line 185 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
  
#line 187 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
void CModelDestruction::SpawnDebris(CModelHolder2 * penmhDestroyed) 
#line 188 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 189 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOATaabbox3D box ;
#line 190 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
penmhDestroyed  -> GetBoundingBox  (box );
#line 191 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT fEntitySize  = box  . Size  () . MaxNorm  ();
#line 192 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
switch(m_ddtDebris ){
#line 193 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
case DDT_STONE : {
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Begin  (EIBT_ROCK  , DPT_NONE  , BET_NONE  , fEntitySize  , FLOAT3D (0 , 0 , 0) , FLOAT3D (0 , 0 , 0) , 1.0f , 0.0f);
#line 195 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
for(INDEX iDebris  = 0;iDebris  < m_ctDebris ;iDebris  ++){
#line 196 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Spawn  (penmhDestroyed  , this  , MODEL_STONE  , TEXTURE_STONE  , 0 , 0 , 0 , IRnd  () % 4 , m_fDebrisSize  , 
#line 197 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT3D (FRnd  () * 0.8f + 0.1f , FRnd  () * 0.8f + 0.1f , FRnd  () * 0.8f + 0.1f));
#line 198 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 199 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}break ;
#line 200 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
case DDT_WOOD : 
#line 201 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 202 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Begin  (EIBT_WOOD  , DPT_NONE  , BET_NONE  , fEntitySize  , FLOAT3D (0 , 0 , 0) , FLOAT3D (0 , 0 , 0) , 1.0f , 0.0f);
#line 203 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
for(INDEX iDebris  = 0;iDebris  < m_ctDebris ;iDebris  ++)
#line 204 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 205 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Spawn  (penmhDestroyed  , this  , MODEL_WOOD  , TEXTURE_WOOD  , 0 , 0 , 0 , 0 , m_fDebrisSize  , 
#line 206 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT3D (0.5f , 0.5f , 0.5f));
#line 207 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 208 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
break ;
#line 209 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 210 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
case DDT_CHILDREN_CUSTOM : 
#line 211 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 212 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Begin  (EIBT_WOOD  , DPT_NONE  , BET_NONE  , 1.0f , FLOAT3D (10 , 10 , 10) , FLOAT3D (0 , 0 , 0) , 5.0f , 2.0f);
#line 214 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FOREACHINLIST  (CEntity  , en_lnInParent  , en_lhChildren  , iten )
#line 215 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 216 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(IsOfClass  (& * iten  , "ModelHolder2"))
#line 217 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 218 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CModelHolder2  & mhTemplate  = (CModelHolder2  &) * iten ;
#line 219 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(mhTemplate  . GetModelObject  () == NULL  || penmhDestroyed  -> GetModelObject  () == NULL )
#line 220 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 221 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
continue ;
#line 222 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 223 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CModelObject & moNew  = * mhTemplate  . GetModelObject  ();
#line 224 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CModelObject & moOld  = * penmhDestroyed  -> GetModelObject  ();
#line 225 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CPlacement3D plRel  = mhTemplate  . GetPlacement  ();
#line 226 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
plRel  . AbsoluteToRelative  (this  -> GetPlacement  ());
#line 227 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CPlacement3D plLaunch  = plRel ;
#line 228 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT3D vStretch  = moOld  . mo_Stretch ;
#line 229 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
plLaunch  . pl_PositionVector  (1) = plLaunch  . pl_PositionVector  (1) * vStretch  (1);
#line 230 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
plLaunch  . pl_PositionVector  (2) = plLaunch  . pl_PositionVector  (2) * vStretch  (2);
#line 231 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
plLaunch  . pl_PositionVector  (3) = plLaunch  . pl_PositionVector  (3) * vStretch  (3);
#line 232 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
plLaunch  . RelativeToAbsolute  (penmhDestroyed  -> GetPlacement  ());
#line 233 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
ANGLE3D angLaunch  = ANGLE3D (FRnd  () * 360.0f , 90.0f + m_fLaunchCone  * (FRnd  () - 0.5f) , 0);
#line 234 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT3D vLaunchDir ;
#line 235 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT3D vStretchTemplate  = FLOAT3D (
#line 236 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
moOld  . mo_Stretch  (1) * moNew  . mo_Stretch  (1) , 
#line 237 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
moOld  . mo_Stretch  (2) * moNew  . mo_Stretch  (2) , 
#line 238 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
moOld  . mo_Stretch  (3) * moNew  . mo_Stretch  (3));
#line 239 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
AnglesToDirectionVector  (angLaunch  , vLaunchDir );
#line 240 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
vLaunchDir  . Normalize  ();
#line 241 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
vLaunchDir  = vLaunchDir  * m_fDebrisLaunchPower ;
#line 242 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
ANGLE3D angRotSpeed  = ANGLE3D (m_fRndRotH  * 2.0f * (FRnd  () - 0.5f) , m_fRndRotP  * (FRnd  () - 0.5f) , m_fRndRotB  * (FRnd  () - 0.5f));
#line 244 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT fDustSize  = 0.0f;
#line 245 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(FRnd  () < m_fDebrisDustRandom )
#line 246 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 247 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
fDustSize  = m_fDebrisDustStretch ;
#line 248 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 250 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Spawn_Template  (m_eibtBodyType  , m_dptParticles  , m_betStain  , 
#line 251 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
penmhDestroyed  , this  , & mhTemplate  , vStretchTemplate  , mhTemplate  . m_fStretchAll  , plLaunch  , 
#line 252 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
vLaunchDir  , angRotSpeed  , m_bDebrisImmaterialASAP  , fDustSize  , penmhDestroyed  -> m_colBurning );
#line 253 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 254 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(IsOfClass  (& * iten  , "SoundHolder"))
#line 255 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 256 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CSoundHolder  & ensh  = (CSoundHolder  &) * iten ;
#line 258 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CEntity  * penNewSH  = GetWorld  () -> CopyEntityInWorld  (ensh  , penmhDestroyed  -> GetPlacement  ());
#line 259 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
penNewSH  -> SetParent  (NULL );
#line 260 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
penNewSH  -> SendEvent  (EStart  ());
#line 261 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 262 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 263 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
break ;
#line 264 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 265 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
case DDT_PALM : {
#line 266 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Begin  (EIBT_WOOD  , DPT_NONE  , BET_NONE  , fEntitySize  , penmhDestroyed  -> m_vDamage  * 0.3f , FLOAT3D (0 , 0 , 0) , 1.0f , 0.0f);
#line 267 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Spawn  (penmhDestroyed  , this  , MODEL_WOOD  , TEXTURE_WOOD  , 0 , 0 , 0 , 0 , m_fDebrisSize  , 
#line 268 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT3D (0.5f , 0.2f , 0.5f));
#line 269 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Spawn  (penmhDestroyed  , this  , MODEL_WOOD  , TEXTURE_WOOD  , 0 , 0 , 0 , 1 , m_fDebrisSize  , 
#line 270 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT3D (0.5f , 0.3f , 0.5f));
#line 271 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Spawn  (penmhDestroyed  , this  , MODEL_WOOD  , TEXTURE_WOOD  , 0 , 0 , 0 , 2 , m_fDebrisSize  , 
#line 272 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT3D (0.5f , 0.4f , 0.5f));
#line 273 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Spawn  (penmhDestroyed  , this  , MODEL_WOOD  , TEXTURE_WOOD  , 0 , 0 , 0 , 3 , m_fDebrisSize  , 
#line 274 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT3D (0.5f , 0.5f , 0.5f));
#line 275 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Spawn  (penmhDestroyed  , this  , MODEL_WOOD  , TEXTURE_WOOD  , 0 , 0 , 0 , 1 , m_fDebrisSize  , 
#line 276 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT3D (0.5f , 0.6f , 0.5f));
#line 277 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Spawn  (penmhDestroyed  , this  , MODEL_WOOD  , TEXTURE_WOOD  , 0 , 0 , 0 , 2 , m_fDebrisSize  , 
#line 278 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT3D (0.5f , 0.8f , 0.5f));
#line 279 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Debris_Spawn  (penmhDestroyed  , this  , MODEL_WOOD  , TEXTURE_WOOD  , 0 , 0 , 0 , 1 , m_fDebrisSize  , 
#line 280 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT3D (0.5f , 0.9f , 0.5f));
#line 281 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}break ;
#line 282 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
default  :{}break ;
#line 283 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
};
#line 285 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
if(m_ctDustFall  > 0)
#line 286 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 287 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT fHeight  = box  . Size  () (2);
#line 288 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT fMinHeight  = fHeight  * m_fMinDustFallHeightRatio ;
#line 289 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT fMaxHeight  = fHeight  * m_fMaxDustFallHeightRatio ;
#line 290 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT fHeightSteep  = (fMaxHeight  - fMinHeight ) / m_ctDustFall ;
#line 291 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
for(INDEX iDust  = 0;iDust  < m_ctDustFall ;iDust  ++)
#line 292 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
{
#line 293 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
FLOAT fY  = fMinHeight  + iDust  * fHeightSteep ;
#line 294 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CPlacement3D plDust  = penmhDestroyed  -> GetPlacement  ();
#line 295 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
plDust  . pl_PositionVector  = plDust  . pl_PositionVector  + FLOAT3D (0 , fY  , 0);
#line 297 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
ESpawnEffect  ese ;
#line 298 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
ese  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 299 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
ese  . vStretch  = FLOAT3D (m_fDustStretch  , m_fDustStretch  , m_fDustStretch );
#line 300 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
ese  . vNormal  = FLOAT3D (0 , 1 , 0);
#line 301 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
ese  . betType  = BET_DUST_FALL ;
#line 302 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CEntityPointer penFX  = CreateEntity  (plDust  , CLASS_BASIC_EFFECT );
#line 303 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
penFX  -> Initialize  (ese );
#line 304 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 305 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
#line 306 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
}
BOOL CModelDestruction::
#line 309 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CModelDestruction_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CModelDestruction::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 312 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CheckOneModelTarget  (m_penModel0 );
#line 313 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CheckOneModelTarget  (m_penModel1 );
#line 314 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CheckOneModelTarget  (m_penModel2 );
#line 315 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CheckOneModelTarget  (m_penModel3 );
#line 316 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
CheckOneModelTarget  (m_penModel4 );
#line 318 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
InitAsEditorModel  ();
#line 319 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 320 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 323 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
SetModel  (MODEL_MODELDESTRUCTION );
#line 324 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
SetModelMainTexture  (TEXTURE_MODELDESTRUCTION );
#line 326 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
Return(STATE_CURRENT,EVoid());
#line 326 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/ModelDestruction.es"
return TRUE; ASSERT(FALSE); return TRUE;};