/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"

#include "EntitiesMP/StdH/StdH.h"
#include "Models/Enemies/Walker/Walker.h"

#include <EntitiesMP/Walker.h>
#include <EntitiesMP/Walker_tables.h>
#line 30 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"

// info structure
static EntityInfo eiWalker = {
  EIBT_FLESH, 1000.0f,
  0.0f, 5.4f, 0.0f,
  0.0f, 4.5f, 0.0f,
};

#define SIZE_SOLDIER   (0.5f)
#define SIZE_SERGEANT  (1.0f)
#define FIRE_LEFT_ARM   FLOAT3D(-2.5f, 5.0f, 0.0f)
#define FIRE_RIGHT_ARM  FLOAT3D(+2.5f, 5.0f, 0.0f)
#define FIRE_DEATH_LEFT   FLOAT3D( 0.0f, 7.0f, -2.0f)
#define FIRE_DEATH_RIGHT  FLOAT3D(3.75f, 4.2f, -2.5f)

#define WALKERSOUND(soundname) ((m_EwcChar==WLC_SOLDIER)? (SOUND_SOLDIER_##soundname) : (SOUND_SERGEANT_##soundname))

void CWalker::SetDefaultProperties(void) {
  m_EwcChar = WLC_SOLDIER ;
  m_iLoopCounter = 0;
  m_fSize = 1.0f;
  m_bWalkSoundPlaying = FALSE ;
  m_fThreatDistance = 5.0f;
  m_soFeet.SetOwner(this);
m_soFeet.Stop_internal();
  m_soFire1.SetOwner(this);
m_soFire1.Stop_internal();
  m_soFire2.SetOwner(this);
m_soFire2.Stop_internal();
  m_soFire3.SetOwner(this);
m_soFire3.Stop_internal();
  m_soFire4.SetOwner(this);
m_soFire4.Stop_internal();
  CEnemyBase::SetDefaultProperties();
}
  CTString CWalker::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 101 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 102 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
CTString str ;
#line 103 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
str  . PrintF  (TRANSV  ("A Biomech blew %s away") , (const char  *) strPlayerName );
#line 104 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
return str ;
#line 105 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  const CTFileName & CWalker::GetComputerMessageName(void)const {
#line 108 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
static DECLARE_CTFILENAME  (fnmSoldier  , "Data\\Messages\\Enemies\\WalkerSmall.txt");
#line 109 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
static DECLARE_CTFILENAME  (fnmSergeant  , "Data\\Messages\\Enemies\\WalkerBig.txt");
#line 110 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
switch(m_EwcChar ){
#line 111 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
default  : ASSERT  (FALSE );
#line 112 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
case WLC_SOLDIER : return fnmSoldier ;
#line 113 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
case WLC_SERGEANT : return fnmSergeant ;
#line 114 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 115 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 117 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
FLOAT CWalker::GetThreatDistance(void) 
#line 118 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 119 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
return m_fThreatDistance ;
#line 120 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 122 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
BOOL CWalker::ForcesCannonballToExplode(void) 
#line 123 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 124 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(m_EwcChar  == WLC_SERGEANT ){
#line 125 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
return TRUE ;
#line 126 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 127 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
return CEnemyBase  :: ForcesCannonballToExplode  ();
#line 128 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 130 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::Precache(void) {
#line 131 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
CEnemyBase  :: Precache  ();
#line 133 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheModel  (MODEL_WALKER );
#line 135 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(m_EwcChar  == WLC_SOLDIER )
#line 136 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 138 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheSound  (SOUND_SOLDIER_IDLE );
#line 139 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheSound  (SOUND_SOLDIER_SIGHT );
#line 140 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheSound  (SOUND_SOLDIER_DEATH );
#line 141 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheSound  (SOUND_SOLDIER_FIRE_LASER );
#line 142 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheSound  (SOUND_SOLDIER_WALK );
#line 144 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheTexture  (TEXTURE_WALKER_SOLDIER );
#line 146 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheModel  (MODEL_LASER );
#line 147 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheTexture  (TEXTURE_LASER );
#line 149 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_CYBORG_LASER );
#line 150 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 151 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
else 
#line 152 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 154 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheSound  (SOUND_SERGEANT_IDLE );
#line 155 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheSound  (SOUND_SERGEANT_SIGHT );
#line 156 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheSound  (SOUND_SERGEANT_DEATH );
#line 157 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheSound  (SOUND_SERGEANT_FIRE_ROCKET );
#line 158 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheSound  (SOUND_SERGEANT_WALK );
#line 160 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheTexture  (TEXTURE_WALKER_SERGEANT );
#line 162 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheModel  (MODEL_ROCKETLAUNCHER );
#line 163 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheTexture  (TEXTURE_ROCKETLAUNCHER );
#line 165 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_WALKER_ROCKET );
#line 166 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 167 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 169 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void * CWalker::GetEntityInfo(void) {
#line 170 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
return & eiWalker ;
#line 171 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 173 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
FLOAT CWalker::GetCrushHealth(void) 
#line 174 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 175 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(m_EwcChar  == WLC_SERGEANT ){
#line 176 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
return 100.0f;
#line 177 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 178 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
return 0.0f;
#line 179 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 182 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 183 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 184 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 187 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(dmtType  == DMT_BULLET  && fDamageAmmount  > 100.0f)
#line 188 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 189 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
fDamageAmmount  *= 0.666f;
#line 190 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 193 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(! IsOfClass  (penInflictor  , "Walker") || 
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
((CWalker  *) penInflictor ) -> m_EwcChar  != m_EwcChar ){
#line 195 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 196 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 197 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 201 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::StandingAnim(void) {
#line 202 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
DeactivateWalkingSound  ();
#line 203 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StartModelAnim  (WALKER_ANIM_STAND01  , AOF_LOOPING  | AOF_NORESTART );
#line 204 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 205 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::StandingAnimFight(void) 
#line 206 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 207 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
DeactivateWalkingSound  ();
#line 208 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StartModelAnim  (WALKER_ANIM_IDLEFIGHT  , AOF_LOOPING  | AOF_NORESTART );
#line 209 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 210 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::WalkingAnim(void) {
#line 211 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ActivateWalkingSound  ();
#line 212 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(m_EwcChar  == WLC_SERGEANT ){
#line 213 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StartModelAnim  (WALKER_ANIM_WALKBIG  , AOF_LOOPING  | AOF_NORESTART );
#line 214 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}else {
#line 215 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StartModelAnim  (WALKER_ANIM_WALK  , AOF_LOOPING  | AOF_NORESTART );
#line 216 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 217 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 218 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::RunningAnim(void) {
#line 219 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
WalkingAnim  ();
#line 220 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 221 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::RotatingAnim(void) {
#line 222 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
WalkingAnim  ();
#line 223 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 226 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::IdleSound(void) {
#line 227 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PlaySound  (m_soSound  , WALKERSOUND  (IDLE ) , SOF_3D );
#line 228 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 229 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::SightSound(void) {
#line 230 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PlaySound  (m_soSound  , WALKERSOUND  (SIGHT ) , SOF_3D );
#line 231 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 232 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::DeathSound(void) {
#line 233 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PlaySound  (m_soSound  , WALKERSOUND  (DEATH ) , SOF_3D );
#line 234 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 237 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::ActivateWalkingSound(void) 
#line 238 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 239 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(! m_bWalkSoundPlaying ){
#line 240 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PlaySound  (m_soFeet  , WALKERSOUND  (WALK ) , SOF_3D  | SOF_LOOP );
#line 241 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_bWalkSoundPlaying  = TRUE ;
#line 242 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 243 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 244 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::DeactivateWalkingSound(void) 
#line 245 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 246 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_soFeet  . Stop  ();
#line 247 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_bWalkSoundPlaying  = FALSE ;
#line 248 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 251 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::FireDeathRocket(const FLOAT3D & vPos) {
#line 252 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
CPlacement3D plRocket ;
#line 253 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
plRocket  . pl_PositionVector  = vPos ;
#line 254 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
plRocket  . pl_OrientationAngle  = ANGLE3D (0 , - 5.0f - FRnd  () * 10.0f , 0);
#line 255 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
plRocket  . RelativeToAbsolute  (GetPlacement  ());
#line 256 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
CEntityPointer penProjectile  = CreateEntity  (plRocket  , CLASS_PROJECTILE );
#line 257 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ELaunchProjectile  eLaunch ;
#line 258 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
eLaunch  . penLauncher  = this ;
#line 259 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
eLaunch  . prtType  = PRT_WALKER_ROCKET ;
#line 260 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
penProjectile  -> Initialize  (eLaunch );
#line 261 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 263 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::FireDeathLaser(const FLOAT3D & vPos) {
#line 264 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
CPlacement3D plLaser ;
#line 265 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
plLaser  . pl_PositionVector  = vPos ;
#line 266 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
plLaser  . pl_OrientationAngle  = ANGLE3D (0 , - 5.0f - FRnd  () * 10.0f , 0);
#line 267 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
plLaser  . RelativeToAbsolute  (GetPlacement  ());
#line 268 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
CEntityPointer penProjectile  = CreateEntity  (plLaser  , CLASS_PROJECTILE );
#line 269 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ELaunchProjectile  eLaunch ;
#line 270 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
eLaunch  . penLauncher  = this ;
#line 271 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
eLaunch  . prtType  = PRT_CYBORG_LASER ;
#line 272 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
penProjectile  -> Initialize  (eLaunch );
#line 273 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
  
#line 278 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
void CWalker::EnemyPostInit(void) 
#line 279 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 281 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_soSound  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 282 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_soFeet  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 283 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_soFire1  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 284 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_soFire2  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 285 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_soFire3  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 286 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_soFire4  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 287 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
BOOL CWalker::
#line 327 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWalker_Fire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWalker::Fire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 328 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
DeactivateWalkingSound  ();
#line 330 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StartModelAnim  (WALKER_ANIM_TOFIRE  , 0);
#line 331 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fLockOnEnemyTime  = GetModelObject  () -> GetAnimLength  (WALKER_ANIM_TOFIRE );
#line 332 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
STATE_CEnemyBase_LockOnEnemy, FALSE;
Jump(STATE_CURRENT, 0x01440001, FALSE, EBegin());return TRUE;}BOOL CWalker::H0x01440001_Fire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyBase_LockOnEnemy, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01440002, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CWalker::H0x01440002_Fire_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440002
const EReturn&__e= (EReturn&)__eeInput;
;
#line 335 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(!(m_EwcChar  == WLC_SERGEANT )){ Jump(STATE_CURRENT,0x01440005, FALSE, EInternal());return TRUE;}
#line 336 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StartModelAnim  (WALKER_ANIM_FIRERIGHT  , AOF_LOOPING );
#line 337 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ShootProjectile  (PRT_WALKER_ROCKET  , FIRE_RIGHT_ARM  * m_fSize  , ANGLE3D (0 , 0 , 0));
#line 338 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PlaySound  (m_soFire1  , SOUND_SERGEANT_FIRE_ROCKET  , SOF_3D );
#line 339 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(GetSP  () -> sp_gdGameDifficulty  <= CSessionProperties  :: GD_EASY ){
#line 340 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fLockOnEnemyTime  = 1.0f;
#line 341 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}else {
#line 342 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fLockOnEnemyTime  = 0.5f;
#line 343 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 344 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
STATE_CEnemyBase_LockOnEnemy, FALSE;
Jump(STATE_CURRENT, 0x01440003, FALSE, EBegin());return TRUE;}BOOL CWalker::H0x01440003_Fire_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440003
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyBase_LockOnEnemy, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01440004, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CWalker::H0x01440004_Fire_04(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440004
const EReturn&__e= (EReturn&)__eeInput;
;
#line 345 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StartModelAnim  (WALKER_ANIM_FIRELEFT  , AOF_LOOPING );
#line 346 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ShootProjectile  (PRT_WALKER_ROCKET  , FIRE_LEFT_ARM  * m_fSize  , ANGLE3D (0 , 0 , 0));
#line 347 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PlaySound  (m_soFire2  , SOUND_SERGEANT_FIRE_ROCKET  , SOF_3D );Jump(STATE_CURRENT,0x01440005, FALSE, EInternal());return TRUE;}BOOL CWalker::H0x01440005_Fire_05(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440005

#line 352 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(!(m_EwcChar  == WLC_SOLDIER )){ Jump(STATE_CURRENT,0x0144000b, FALSE, EInternal());return TRUE;}
#line 353 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(GetSP  () -> sp_gdGameDifficulty  <= CSessionProperties  :: GD_EASY ){
#line 354 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_iLoopCounter  = 4;
#line 355 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}else {
#line 356 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_iLoopCounter  = 8;
#line 357 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 358 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
Jump(STATE_CURRENT,0x01440009, FALSE, EInternal());return TRUE;}BOOL CWalker::H0x01440009_Fire_09(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440009
if(!(m_iLoopCounter  > 0)){ Jump(STATE_CURRENT,0x0144000a, FALSE, EInternal());return TRUE;}
#line 359 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(m_iLoopCounter  % 2){
#line 360 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StartModelAnim  (WALKER_ANIM_FIRELEFT  , AOF_LOOPING );
#line 361 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ShootProjectile  (PRT_CYBORG_LASER  , FIRE_LEFT_ARM  * m_fSize  , ANGLE3D (0 , 0 , 0));
#line 362 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}else {
#line 363 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StartModelAnim  (WALKER_ANIM_FIRERIGHT  , AOF_LOOPING );
#line 364 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ShootProjectile  (PRT_CYBORG_LASER  , FIRE_RIGHT_ARM  * m_fSize  , ANGLE3D (0 , 0 , 0));
#line 365 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 366 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
INDEX iChannel  = m_iLoopCounter  % 4;
#line 367 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(iChannel  == 0){
#line 368 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PlaySound  (m_soFire1  , SOUND_SOLDIER_FIRE_LASER  , SOF_3D );
#line 369 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}else if(iChannel  == 1){
#line 370 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PlaySound  (m_soFire2  , SOUND_SOLDIER_FIRE_LASER  , SOF_3D );
#line 371 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}else if(iChannel  == 2){
#line 372 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PlaySound  (m_soFire3  , SOUND_SOLDIER_FIRE_LASER  , SOF_3D );
#line 373 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}else if(iChannel  == 3){
#line 374 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PlaySound  (m_soFire4  , SOUND_SOLDIER_FIRE_LASER  , SOF_3D );
#line 375 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 376 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(!(m_iLoopCounter  > 1)){ Jump(STATE_CURRENT,0x01440008, FALSE, EInternal());return TRUE;}
#line 377 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(GetSP  () -> sp_gdGameDifficulty  <= CSessionProperties  :: GD_EASY ){
#line 378 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fLockOnEnemyTime  = 0.4f;
#line 379 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}else {
#line 380 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fLockOnEnemyTime  = 0.1f;
#line 381 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 382 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
STATE_CEnemyBase_LockOnEnemy, FALSE;
Jump(STATE_CURRENT, 0x01440006, FALSE, EBegin());return TRUE;}BOOL CWalker::H0x01440006_Fire_06(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440006
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyBase_LockOnEnemy, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01440007, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CWalker::H0x01440007_Fire_07(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440007
const EReturn&__e= (EReturn&)__eeInput;
;Jump(STATE_CURRENT,0x01440008, FALSE, EInternal());return TRUE;}BOOL CWalker::H0x01440008_Fire_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440008

#line 384 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_iLoopCounter  --;Jump(STATE_CURRENT,0x01440009, FALSE, EInternal());return TRUE;
#line 385 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}BOOL CWalker::H0x0144000a_Fire_10(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0144000a
Jump(STATE_CURRENT,0x0144000b, FALSE, EInternal());return TRUE;}BOOL CWalker::H0x0144000b_Fire_11(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0144000b

#line 387 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StopMoving  ();
#line 389 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
MaybeSwitchToAnotherPlayer  ();
#line 392 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StartModelAnim  (WALKER_ANIM_FROMFIRE  , 0);
#line 393 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (WALKER_ANIM_FROMFIRE ));
Jump(STATE_CURRENT, 0x0144000c, FALSE, EBegin());return TRUE;}BOOL CWalker::H0x0144000c_Fire_12(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0144000c
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0144000d, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWalker::H0x0144000d_Fire_13(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0144000d
;
#line 396 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StandingAnimFight  ();
#line 397 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetTimerAfter(FRnd  () * 0.1f + 0.1f);
Jump(STATE_CURRENT, 0x0144000e, FALSE, EBegin());return TRUE;}BOOL CWalker::H0x0144000e_Fire_14(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0144000e
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0144000f, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWalker::H0x0144000f_Fire_15(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0144000f
;
#line 399 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
Return(STATE_CURRENT,EReturn  ());
#line 399 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CWalker::
#line 407 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
Death(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWalker_Death
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWalker::Death expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 409 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StopMoving  ();
#line 410 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
DeathSound  ();
#line 411 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
DeactivateWalkingSound  ();
#line 414 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetCollisionFlags  (ECF_MODEL );
#line 415 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetFlags  (GetFlags  () | ENF_SEETHROUGH );
#line 418 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ChangeCollisionBoxIndexWhenPossible  (WALKER_COLLISION_BOX_DEATH );
#line 421 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StartModelAnim  (WALKER_ANIM_DEATH  , 0);
#line 422 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetTimerAfter(0.9f);
Jump(STATE_CURRENT, 0x01440011, FALSE, EBegin());return TRUE;}BOOL CWalker::H0x01440011_Death_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440011
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01440012, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWalker::H0x01440012_Death_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440012
;
#line 425 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(m_EwcChar  == WLC_SERGEANT ){
#line 426 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(IRnd  () & 1){
#line 427 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
FireDeathRocket  (FIRE_DEATH_RIGHT  * m_fSize );
#line 428 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}else {
#line 429 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
FireDeathRocket  (FIRE_DEATH_LEFT  * m_fSize );
#line 430 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 431 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PlaySound  (m_soSound  , SOUND_SERGEANT_FIRE_ROCKET  , SOF_3D );
#line 432 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 433 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(m_EwcChar  == WLC_SOLDIER ){
#line 434 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(IRnd  () & 1){
#line 435 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
FireDeathLaser  (FIRE_DEATH_RIGHT  * m_fSize );
#line 436 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}else {
#line 437 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
FireDeathLaser  (FIRE_DEATH_LEFT  * m_fSize );
#line 438 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 439 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
PlaySound  (m_soFire2  , SOUND_SOLDIER_FIRE_LASER  , SOF_3D );
#line 440 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 441 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetTimerAfter(0.25f);
Jump(STATE_CURRENT, 0x01440013, FALSE, EBegin());return TRUE;}BOOL CWalker::H0x01440013_Death_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440013
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01440014, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWalker::H0x01440014_Death_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440014
;
#line 443 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
FLOAT fStretch  = 2.0f;
#line 444 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(m_EwcChar  == WLC_SERGEANT )
#line 445 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
{
#line 446 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
fStretch  = 4.0f;
#line 447 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 449 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
CPlacement3D plFX  = GetPlacement  ();
#line 450 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ESpawnEffect  ese ;
#line 451 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ese  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 452 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ese  . vStretch  = FLOAT3D (1.5 , 1 , 1) * fStretch ;
#line 453 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ese  . vNormal  = FLOAT3D (0 , 1 , 0);
#line 454 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ese  . betType  = BET_DUST_FALL ;
#line 455 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
CPlacement3D plSmoke  = plFX ;
#line 456 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
plSmoke  . pl_PositionVector  += FLOAT3D (0 , 0.35f * ese  . vStretch  (2) , 0);
#line 457 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
CEntityPointer penFX  = CreateEntity  (plSmoke  , CLASS_BASIC_EFFECT );
#line 458 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
penFX  -> Initialize  (ese );
#line 460 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetTimerAfter(0.35f);
Jump(STATE_CURRENT, 0x01440015, FALSE, EBegin());return TRUE;}BOOL CWalker::H0x01440015_Death_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440015
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01440016, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWalker::H0x01440016_Death_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01440016
;
#line 462 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
Return(STATE_CURRENT,EEnd  ());
#line 462 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CWalker::
#line 468 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWalker_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWalker::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 470 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
InitAsModel  ();
#line 471 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetPhysicsFlags  (EPF_MODEL_WALKING );
#line 472 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetCollisionFlags  (ECF_MODEL );
#line 473 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 474 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(m_EwcChar  == WLC_SERGEANT ){
#line 475 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetHealth  (750.0f);
#line 476 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fMaxHealth  = 750.0f;
#line 477 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}else {
#line 478 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetHealth  (150.0f);
#line 479 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fMaxHealth  = 150.0f;
#line 480 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 481 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
en_fDensity  = 3000.0f;
#line 483 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_sptType  = SPT_ELECTRICITY_SPARKS ;
#line 486 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetModel  (MODEL_WALKER );
#line 487 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(m_EwcChar  == WLC_SERGEANT ){
#line 488 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fSize  = 1.0f;
#line 489 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetModelMainTexture  (TEXTURE_WALKER_SERGEANT );
#line 490 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
AddAttachment  (WALKER_ATTACHMENT_ROCKETLAUNCHER_LT  , MODEL_ROCKETLAUNCHER  , TEXTURE_ROCKETLAUNCHER );
#line 491 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
AddAttachment  (WALKER_ATTACHMENT_ROCKETLAUNCHER_RT  , MODEL_ROCKETLAUNCHER  , TEXTURE_ROCKETLAUNCHER );
#line 492 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
GetModelObject  () -> StretchModel  (FLOAT3D (1 , 1 , 1));
#line 493 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ModelChangeNotify  ();
#line 494 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
CModelObject * pmoRight  = & GetModelObject  () -> GetAttachmentModel  (WALKER_ATTACHMENT_ROCKETLAUNCHER_RT ) -> amo_moModelObject ;
#line 495 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
pmoRight  -> StretchModel  (FLOAT3D (- 1 , 1 , 1));
#line 496 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fBlowUpAmount  = 1E10f;
#line 497 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_iScore  = 7500;
#line 498 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fThreatDistance  = 15;
#line 499 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}else {
#line 500 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fSize  = 0.5f;
#line 501 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
SetModelMainTexture  (TEXTURE_WALKER_SOLDIER );
#line 502 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
AddAttachment  (WALKER_ATTACHMENT_LASER_LT  , MODEL_LASER  , TEXTURE_LASER );
#line 503 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
AddAttachment  (WALKER_ATTACHMENT_LASER_RT  , MODEL_LASER  , TEXTURE_LASER );
#line 504 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
GetModelObject  () -> StretchModel  (FLOAT3D (0.5f , 0.5f , 0.5f));
#line 505 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
ModelChangeNotify  ();
#line 506 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
CModelObject * pmoRight  = & GetModelObject  () -> GetAttachmentModel  (WALKER_ATTACHMENT_LASER_RT ) -> amo_moModelObject ;
#line 507 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
pmoRight  -> StretchModel  (FLOAT3D (- 0.5f , 0.5f , 0.5f));
#line 508 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fBlowUpAmount  = 1E10f;
#line 511 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_iScore  = 2000;
#line 512 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fThreatDistance  = 5;
#line 513 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 514 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
if(m_fStepHeight  == - 1){
#line 515 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fStepHeight  = 4.0f;
#line 516 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
}
#line 518 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
StandingAnim  ();
#line 520 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fWalkSpeed  = FRnd  () * 1.5f + 9.0f;
#line 521 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 50.0f + 500.0f);
#line 522 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fAttackRunSpeed  = m_fWalkSpeed ;
#line 523 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_aAttackRotateSpeed  = m_aWalkRotateSpeed  / 2;
#line 524 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fCloseRunSpeed  = m_fWalkSpeed ;
#line 525 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_aCloseRotateSpeed  = m_aWalkRotateSpeed  / 2;
#line 526 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fWalkSpeed  /= 2.0f;
#line 528 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fAttackDistance  = 150.0f;
#line 529 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fCloseDistance  = 0.0f;
#line 530 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fStopDistance  = 15.0f;
#line 531 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fAttackFireTime  = 3.0f;
#line 532 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fCloseFireTime  = 1.0f;
#line 533 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fIgnoreRange  = 300.0f;
#line 535 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fBodyParts  = 8;
#line 536 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
m_fDamageWounded  = 100000.0f;
#line 539 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Walker.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};