/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"

#include "EntitiesMP/StdH/StdH.h"
#include "Models/Items/ItemHolder/ItemHolder.h"
#include "Models/Weapons/Colt/ColtItem.h"
#include "Models/Weapons/SingleShotgun/SingleShotgunItem.h"
#include "Models/Weapons/DoubleShotgun/DoubleShotgunItem.h"
#include "Models/Weapons/TommyGun/TommyGunItem.h"
#include "Models/Weapons/MiniGun/MiniGunItem.h"
#include "Models/Weapons/GrenadeLauncher/GrenadeLauncherItem.h"
#include "Models/Weapons/RocketLauncher/RocketLauncherItem.h"
#include "ModelsMP/Weapons/Sniper/SniperItem.h"
#include "ModelsMP/Weapons/Sniper/Body.h"
#include "ModelsMP/Weapons/Flamer/FlamerItem.h"
#include "ModelsMP/Weapons/ChainSaw/ChainsawItem.h"
#include "ModelsMP/Weapons/ChainSaw/BladeForPlayer.h"
#include "Models/Weapons/Laser/LaserItem.h"
#include "Models/Weapons/Cannon/Cannon.h"

#include "EntitiesMP/PlayerWeapons.h"


#include <EntitiesMP/WeaponItem.h>
#include <EntitiesMP/WeaponItem_tables.h>
CEntityEvent *EWeaponItem::MakeCopy(void) { CEntityEvent *peeCopy = new EWeaponItem(*this); return peeCopy;}
EWeaponItem::EWeaponItem() : CEntityEvent(EVENTCODE_EWeaponItem) {;
 ClearToDefault(iWeapon);
 ClearToDefault(iAmmo);
 ClearToDefault(bDropped);
};
#line 65 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"

extern void CPlayerWeapons_Precache(ULONG ulAvailable);

void CWeaponItem::SetDefaultProperties(void) {
  m_EwitType = WIT_COLT ;
  CItem::SetDefaultProperties();
}
  
#line 193 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
void CWeaponItem::Precache(void) {
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
PrecacheSound  (SOUND_PICK );
#line 195 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
switch(m_EwitType ){
#line 196 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_COLT : CPlayerWeapons_Precache  (1 << (INDEX (WEAPON_COLT ) - 1));break ;
#line 197 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_SINGLESHOTGUN : CPlayerWeapons_Precache  (1 << (INDEX (WEAPON_SINGLESHOTGUN ) - 1));break ;
#line 198 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_DOUBLESHOTGUN : CPlayerWeapons_Precache  (1 << (INDEX (WEAPON_DOUBLESHOTGUN ) - 1));break ;
#line 199 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_TOMMYGUN : CPlayerWeapons_Precache  (1 << (INDEX (WEAPON_TOMMYGUN ) - 1));break ;
#line 200 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_MINIGUN : CPlayerWeapons_Precache  (1 << (INDEX (WEAPON_MINIGUN ) - 1));break ;
#line 201 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_ROCKETLAUNCHER : CPlayerWeapons_Precache  (1 << (INDEX (WEAPON_ROCKETLAUNCHER ) - 1));break ;
#line 202 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_GRENADELAUNCHER : CPlayerWeapons_Precache  (1 << (INDEX (WEAPON_GRENADELAUNCHER ) - 1));break ;
#line 203 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_SNIPER : CPlayerWeapons_Precache  (1 << (INDEX (WEAPON_SNIPER ) - 1));break ;
#line 204 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_FLAMER : CPlayerWeapons_Precache  (1 << (INDEX (WEAPON_FLAMER ) - 1));break ;
#line 205 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_CHAINSAW : CPlayerWeapons_Precache  (1 << (INDEX (WEAPON_CHAINSAW ) - 1));break ;
#line 206 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_LASER : CPlayerWeapons_Precache  (1 << (INDEX (WEAPON_LASER ) - 1));break ;
#line 207 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_CANNON : CPlayerWeapons_Precache  (1 << (INDEX (WEAPON_IRONCANNON ) - 1));break ;
#line 208 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
#line 209 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
  
#line 211 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
BOOL CWeaponItem::FillEntityStatistics(EntityStats * pes) 
#line 212 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
{
#line 213 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
pes  -> es_strName  = m_strDescription ;
#line 214 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
pes  -> es_ctCount  = 1;
#line 215 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
pes  -> es_ctAmmount  = 1;
#line 216 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
pes  -> es_fValue  = 1;
#line 217 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
pes  -> es_iScore  = 0;
#line 218 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
return TRUE ;
#line 219 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
  
#line 222 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
void CWeaponItem::RenderParticles(void) {
#line 224 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
if(GetRenderType  () != CEntity  :: RT_MODEL  || GetSP  () -> sp_gmGameMode  > CSessionProperties  :: GM_COOPERATIVE  
#line 225 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
|| ! ShowItemParticles  ())
#line 226 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
{
#line 227 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
return ;
#line 228 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
#line 229 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
switch(m_EwitType ){
#line 230 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_COLT : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 231 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_SINGLESHOTGUN : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 232 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_DOUBLESHOTGUN : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 233 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_TOMMYGUN : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 234 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_MINIGUN : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 235 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_ROCKETLAUNCHER : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 236 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_GRENADELAUNCHER : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 237 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_SNIPER : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 238 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_FLAMER : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 239 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_CHAINSAW : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 240 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_LASER : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 241 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_GHOSTBUSTER : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 242 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_CANNON : Particles_Atomic  (this  , 1.5f , 1.5f , PT_STAR07  , 12);break ;
#line 243 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
#line 244 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
  
#line 248 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
void CWeaponItem::SetProperties(void) 
#line 249 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
{
#line 250 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
BOOL bDM  = FALSE ;
#line 251 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
FLOAT3D vDMStretch  = FLOAT3D (2.0f , 2.0f , 2.0f);
#line 253 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
switch(m_EwitType ){
#line 255 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_COLT : 
#line 256 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 10.0f;
#line 257 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_strDescription  . PrintF  ("Colt");
#line 258 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItem  (MODEL_COLT  , TEXTURE_COLTMAIN  , 0 , 0 , 0);
#line 259 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (COLTITEM_ATTACHMENT_BULLETS  , MODEL_COLTBULLETS  , TEXTURE_COLTBULLETS  , TEX_REFL_LIGHTBLUEMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 260 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (COLTITEM_ATTACHMENT_COCK  , MODEL_COLTCOCK  , TEXTURE_COLTCOCK  , TEX_REFL_LIGHTBLUEMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 261 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (COLTITEM_ATTACHMENT_BODY  , MODEL_COLTMAIN  , TEXTURE_COLTMAIN  , TEX_REFL_LIGHTBLUEMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 262 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StretchItem  (bDM  ? vDMStretch  : FLOAT3D (4.5f , 4.5f , 4.5f));
#line 263 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
break ;
#line 266 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_SINGLESHOTGUN : 
#line 267 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 10.0f;
#line 268 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_strDescription  . PrintF  ("Single Shotgun");
#line 269 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItem  (MODEL_SINGLESHOTGUN  , TEXTURE_SS_HANDLE  , 0 , 0 , 0);
#line 270 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (SINGLESHOTGUNITEM_ATTACHMENT_BARRELS  , MODEL_SS_BARRELS  , TEXTURE_SS_BARRELS  , TEX_REFL_DARKMETAL  , TEX_SPEC_WEAK  , 0);
#line 271 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (SINGLESHOTGUNITEM_ATTACHMENT_HANDLE  , MODEL_SS_HANDLE  , TEXTURE_SS_HANDLE  , TEX_REFL_DARKMETAL  , TEX_SPEC_MEDIUM  , 0);
#line 272 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (SINGLESHOTGUNITEM_ATTACHMENT_SLIDER  , MODEL_SS_SLIDER  , TEXTURE_SS_BARRELS  , TEX_REFL_DARKMETAL  , TEX_SPEC_MEDIUM  , 0);
#line 273 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StretchItem  (bDM  ? vDMStretch  : (FLOAT3D (3.5f , 3.5f , 3.5f)));
#line 274 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
break ;
#line 277 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_DOUBLESHOTGUN : 
#line 278 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 10.0f;
#line 279 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_strDescription  . PrintF  ("Double Shotgun");
#line 280 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItem  (MODEL_DOUBLESHOTGUN  , TEXTURE_DS_HANDLE  , 0 , 0 , 0);
#line 281 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (DOUBLESHOTGUNITEM_ATTACHMENT_BARRELS  , MODEL_DS_BARRELS  , TEXTURE_DS_BARRELS  , TEX_REFL_BWRIPLES01  , TEX_SPEC_MEDIUM  , 0);
#line 282 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (DOUBLESHOTGUNITEM_ATTACHMENT_HANDLE  , MODEL_DS_HANDLE  , TEXTURE_DS_HANDLE  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 283 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (DOUBLESHOTGUNITEM_ATTACHMENT_SWITCH  , MODEL_DS_SWITCH  , TEXTURE_DS_SWITCH  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 284 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StretchItem  (bDM  ? vDMStretch  : (FLOAT3D (3.0f , 3.0f , 3.0f)));
#line 285 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
break ;
#line 289 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_TOMMYGUN : 
#line 290 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 10.0f;
#line 291 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_strDescription  . PrintF  ("Tommygun");
#line 292 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItem  (MODEL_TOMMYGUN  , TEXTURE_TG_BODY  , 0 , 0 , 0);
#line 293 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (TOMMYGUNITEM_ATTACHMENT_BODY  , MODEL_TG_BODY  , TEXTURE_TG_BODY  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 294 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (TOMMYGUNITEM_ATTACHMENT_SLIDER  , MODEL_TG_SLIDER  , TEXTURE_TG_BODY  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 295 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StretchItem  (bDM  ? vDMStretch  : (FLOAT3D (3.0f , 3.0f , 3.0f)));
#line 296 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
break ;
#line 299 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_MINIGUN : 
#line 300 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 10.0f;
#line 301 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_strDescription  . PrintF  ("Minigun");
#line 302 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItem  (MODEL_MINIGUN  , TEXTURE_MG_BODY  , 0 , 0 , 0);
#line 303 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (MINIGUNITEM_ATTACHMENT_BARRELS  , MODEL_MG_BARRELS  , TEXTURE_MG_BARRELS  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 304 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (MINIGUNITEM_ATTACHMENT_BODY  , MODEL_MG_BODY  , TEXTURE_MG_BODY  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 305 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (MINIGUNITEM_ATTACHMENT_ENGINE  , MODEL_MG_ENGINE  , TEXTURE_MG_BARRELS  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 306 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StretchItem  (bDM  ? vDMStretch  : (FLOAT3D (1.75f , 1.75f , 1.75f)));
#line 307 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
break ;
#line 310 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_ROCKETLAUNCHER : 
#line 311 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 10.0f;
#line 312 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_strDescription  . PrintF  ("Rocket launcher");
#line 313 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItem  (MODEL_ROCKETLAUNCHER  , TEXTURE_RL_BODY  , 0 , 0 , 0);
#line 314 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (ROCKETLAUNCHERITEM_ATTACHMENT_BODY  , MODEL_RL_BODY  , TEXTURE_RL_BODY  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 315 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (ROCKETLAUNCHERITEM_ATTACHMENT_ROTATINGPART  , MODEL_RL_ROTATINGPART  , TEXTURE_RL_ROTATINGPART  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 316 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (ROCKETLAUNCHERITEM_ATTACHMENT_ROCKET1  , MODEL_RL_ROCKET  , TEXTURE_RL_ROCKET  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 317 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (ROCKETLAUNCHERITEM_ATTACHMENT_ROCKET2  , MODEL_RL_ROCKET  , TEXTURE_RL_ROCKET  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 318 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (ROCKETLAUNCHERITEM_ATTACHMENT_ROCKET3  , MODEL_RL_ROCKET  , TEXTURE_RL_ROCKET  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 319 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (ROCKETLAUNCHERITEM_ATTACHMENT_ROCKET4  , MODEL_RL_ROCKET  , TEXTURE_RL_ROCKET  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 320 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StretchItem  (bDM  ? vDMStretch  : (FLOAT3D (2.5f , 2.5f , 2.5f)));
#line 321 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
break ;
#line 324 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_GRENADELAUNCHER : 
#line 325 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 10.0f;
#line 326 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_strDescription  . PrintF  ("Grenade launcher");
#line 327 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItem  (MODEL_GRENADELAUNCHER  , TEXTURE_GL_BODY  , 0 , 0 , 0);
#line 328 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (GRENADELAUNCHERITEM_ATTACHMENT_BODY  , MODEL_GL_BODY  , TEXTURE_GL_BODY  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 329 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (GRENADELAUNCHERITEM_ATTACHMENT_MOVING_PART  , MODEL_GL_MOVINGPART  , TEXTURE_GL_MOVINGPART  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 330 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (GRENADELAUNCHERITEM_ATTACHMENT_GRENADE  , MODEL_GL_GRENADE  , TEXTURE_GL_MOVINGPART  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 331 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StretchItem  (bDM  ? vDMStretch  : (FLOAT3D (2.5f , 2.5f , 2.5f)));
#line 332 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
break ;
#line 335 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_SNIPER : 
#line 336 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 10.0f;
#line 337 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_strDescription  . PrintF  ("Sniper");
#line 338 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItem  (MODEL_SNIPER  , TEXTURE_SNIPER_BODY  , 0 , 0 , 0);
#line 339 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (SNIPERITEM_ATTACHMENT_BODY  , MODEL_SNIPER_BODY  , TEXTURE_SNIPER_BODY  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 340 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
SetItemAttachmentAnim  (SNIPERITEM_ATTACHMENT_BODY  , BODY_ANIM_FORITEM1 );
#line 341 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StretchItem  (bDM  ? vDMStretch  : (FLOAT3D (3.0f , 3.0f , 3.0f)));
#line 342 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
break ;
#line 345 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_FLAMER : 
#line 346 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 10.0f;
#line 347 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_strDescription  . PrintF  ("Flamer");
#line 348 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItem  (MODEL_FLAMER  , TEXTURE_FL_BODY  , 0 , 0 , 0);
#line 349 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (FLAMERITEM_ATTACHMENT_BODY  , MODEL_FL_BODY  , 
#line 350 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
TEXTURE_FL_BODY  , TEX_REFL_BWRIPLES02  , TEX_SPEC_MEDIUM  , 0);
#line 351 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (FLAMERITEM_ATTACHMENT_FUEL  , MODEL_FL_RESERVOIR  , 
#line 352 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
TEXTURE_FL_FUELRESERVOIR  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 353 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (FLAMERITEM_ATTACHMENT_FLAME  , MODEL_FL_FLAME  , 
#line 354 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
TEXTURE_FL_FLAME  , 0 , 0 , 0);
#line 355 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StretchItem  (bDM  ? vDMStretch  : (FLOAT3D (2.5f , 2.5f , 2.5f)));
#line 356 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
break ;
#line 359 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_CHAINSAW : {
#line 360 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 10.0f;
#line 361 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_strDescription  . PrintF  ("Chainsaw");
#line 362 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItem  (MODEL_CHAINSAW  , TEXTURE_CS_BODY  , 0 , 0 , 0);
#line 363 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (CHAINSAWITEM_ATTACHMENT_CHAINSAW  , MODEL_CS_BODY  , TEXTURE_CS_BODY  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 364 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (CHAINSAWITEM_ATTACHMENT_BLADE  , MODEL_CS_BLADE  , TEXTURE_CS_BLADE  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 365 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
CModelObject * pmoMain  , * pmo ;
#line 366 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
pmoMain  = & (GetModelObject  () -> GetAttachmentModel  (ITEMHOLDER_ATTACHMENT_ITEM ) -> amo_moModelObject );
#line 367 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
pmo  = & (pmoMain  -> GetAttachmentModel  (CHAINSAWITEM_ATTACHMENT_BLADE ) -> amo_moModelObject );
#line 368 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddAttachmentToModel  (this  , * pmo  , BLADEFORPLAYER_ATTACHMENT_TEETH  , MODEL_CS_TEETH  , TEXTURE_CS_TEETH  , 0 , 0 , 0);
#line 370 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StretchItem  (bDM  ? vDMStretch  : (FLOAT3D (2.0f , 2.0f , 2.0f)));
#line 371 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
break ;}
#line 374 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_LASER : 
#line 375 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 10.0f;
#line 376 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_strDescription  . PrintF  ("Laser");
#line 377 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItem  (MODEL_LASER  , TEXTURE_LS_BODY  , 0 , 0 , 0);
#line 378 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (LASERITEM_ATTACHMENT_BODY  , MODEL_LS_BODY  , TEXTURE_LS_BODY  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 379 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (LASERITEM_ATTACHMENT_LEFTUP  , MODEL_LS_BARREL  , TEXTURE_LS_BARREL  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 380 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (LASERITEM_ATTACHMENT_LEFTDOWN  , MODEL_LS_BARREL  , TEXTURE_LS_BARREL  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 381 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (LASERITEM_ATTACHMENT_RIGHTUP  , MODEL_LS_BARREL  , TEXTURE_LS_BARREL  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 382 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (LASERITEM_ATTACHMENT_RIGHTDOWN  , MODEL_LS_BARREL  , TEXTURE_LS_BARREL  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 383 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StretchItem  (bDM  ? vDMStretch  : (FLOAT3D (2.5f , 2.5f , 2.5f)));
#line 384 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
break ;
#line 387 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
case WIT_CANNON : 
#line 388 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 30.0f;
#line 389 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_strDescription  . PrintF  ("Cannon");
#line 390 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItem  (MODEL_CANNON  , TEXTURE_CANNON  , 0 , 0 , 0);
#line 391 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddItemAttachment  (CANNON_ATTACHMENT_BODY  , MODEL_CN_BODY  , TEXTURE_CANNON  , TEX_REFL_LIGHTMETAL01  , TEX_SPEC_MEDIUM  , 0);
#line 394 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StretchItem  (bDM  ? vDMStretch  : (FLOAT3D (3.0f , 3.0f , 3.0f)));
#line 395 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
break ;
#line 396 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
#line 398 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
AddFlare  (MODEL_FLARE  , TEXTURE_FLARE  , FLOAT3D (0 , 0.6f , 0) , FLOAT3D (3 , 3 , 0.3f));
#line 399 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
BOOL CWeaponItem::
#line 402 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
ItemCollected(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWeaponItem_ItemCollected
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EPass, "CWeaponItem::ItemCollected expects 'EPass' as input!");  const EPass &epass = (const EPass &)__eeInput;
#line 403 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
ASSERT  (epass  . penOther  != NULL );
#line 406 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
if(GetSP  () -> sp_bWeaponsStay  && ! (m_bPickupOnce  || m_bRespawn )){
#line 408 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
BOOL bWasPicked  = MarkPickedBy  (epass  . penOther );
#line 409 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
if(bWasPicked ){
#line 411 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
Return(STATE_CURRENT,EVoid());
#line 411 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
return TRUE;
#line 412 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
#line 413 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
#line 416 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
EWeaponItem  eWeapon ;
#line 417 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
eWeapon  . iWeapon  = m_EwitType ;
#line 418 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
eWeapon  . iAmmo  = - 1;
#line 419 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
eWeapon  . bDropped  = m_bDropped ;
#line 421 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
if(epass  . penOther  -> ReceiveItem  (eWeapon )){
#line 422 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
if(_pNetwork  -> IsPlayerLocal  (epass  . penOther )){IFeel_PlayEffect  ("PU_Weapon");}
#line 424 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_soPick  . Set3DParameters  (50.0f , 1.0f , 1.0f , 1.0f);
#line 425 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
PlaySound  (m_soPick  , SOUND_PICK  , SOF_3D );
#line 426 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_fPickSoundLen  = GetSoundLength  (SOUND_PICK );
#line 427 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
if(! GetSP  () -> sp_bWeaponsStay  || m_bDropped  || (m_bPickupOnce  || m_bRespawn )){
#line 428 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
Jump(STATE_CURRENT, STATE_CItem_ItemReceived, FALSE, EVoid());return TRUE;
#line 429 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
#line 430 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
#line 431 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
Return(STATE_CURRENT,EVoid());
#line 431 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CWeaponItem::
#line 434 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWeaponItem_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWeaponItem::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 436 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
if(m_EwitType  == WIT_GHOSTBUSTER ){
#line 437 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
m_EwitType  = WIT_LASER ;
#line 438 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}
#line 440 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
Initialize  ();
#line 441 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
StartModelAnim  (ITEMHOLDER_ANIM_BIGOSCILATION  , AOF_LOOPING  | AOF_NORESTART );
#line 442 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
ForceCollisionBoxIndexChange  (ITEMHOLDER_COLLISION_BOX_BIG );
#line 443 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
SetProperties  ();
#line 445 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
if(!(! m_bDropped )){ Jump(STATE_CURRENT,0x03220006, FALSE, EInternal());return TRUE;}
#line 446 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
Jump(STATE_CURRENT, STATE_CItem_ItemLoop, FALSE, EVoid());return TRUE;Jump(STATE_CURRENT,0x03220005, FALSE, EInternal());return TRUE;}BOOL CWeaponItem::H0x03220006_Main_05(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03220006
if(!(TRUE )){ Jump(STATE_CURRENT,0x03220004, FALSE, EInternal());return TRUE;}
#line 448 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x03220002, FALSE, EBegin());return TRUE;}BOOL CWeaponItem::H0x03220002_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x03220002
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;

#line 450 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
SpawnReminder  (this  , m_fRespawnTime  , 0);
#line 451 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
Call(STATE_CURRENT, STATE_CItem_ItemLoop, FALSE, EVoid());return TRUE;
#line 452 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}ASSERT(FALSE);break;case(EVENTCODE_EReminder):{const EReminder&e= (EReminder&)__eeInput;

#line 454 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
SendEvent  (EEnd  ());
#line 455 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
return TRUE;
#line 456 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 457 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/WeaponItem.es"
}return TRUE;}BOOL CWeaponItem::H0x03220003_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03220003
Jump(STATE_CURRENT,0x03220004, FALSE, EInternal());return TRUE;}BOOL CWeaponItem::H0x03220004_Main_03(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03220004
Jump(STATE_CURRENT,0x03220005, FALSE, EInternal());return TRUE;}
BOOL CWeaponItem::H0x03220005_Main_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03220005
 ASSERT(FALSE); return TRUE;};