/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"

#include "EntitiesMP/StdH/StdH.h"
#include "Models/Enemies/WereBull/WereBull.h"

#include <EntitiesMP/Werebull.h>
#include <EntitiesMP/Werebull_tables.h>
#line 30 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"

// info structure
static EntityInfo eiWerebull = {
  EIBT_FLESH, 500.0f,
  0.0f, 3.0f, 0.0f,     // source (eyes)
  0.0f, 1.5f, 0.0f,     // target (body)
};

#define HIT_DISTANCE 5.0f

void CWerebull::SetDefaultProperties(void) {
  m_bRunAttack = FALSE ;
  m_bHornHit = FALSE ;
  m_penLastTouched = NULL;
  m_soFeet.SetOwner(this);
m_soFeet.Stop_internal();
  m_bRunSoundPlaying = FALSE ;
  CEnemyRunInto::SetDefaultProperties();
}
  CTString CWerebull::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 71 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
{
#line 72 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
CTString str ;
#line 73 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
str  . PrintF  (TRANSV  ("Sirian werebull sent %s flying") , (const char  *) strPlayerName );
#line 74 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
return str ;
#line 75 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 77 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::Precache(void) {
#line 78 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
CEnemyBase  :: Precache  ();
#line 79 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
PrecacheSound  (SOUND_IDLE );
#line 80 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
PrecacheSound  (SOUND_SIGHT );
#line 81 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
PrecacheSound  (SOUND_KICKHORN );
#line 82 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
PrecacheSound  (SOUND_IMPACT );
#line 83 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
PrecacheSound  (SOUND_DEATH );
#line 84 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
PrecacheSound  (SOUND_RUN );
#line 85 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 88 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void * CWerebull::GetEntityInfo(void) {
#line 89 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
return & eiWerebull ;
#line 90 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 92 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
FLOAT CWerebull::GetCrushHealth(void) 
#line 93 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
{
#line 94 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
return 60.0f;
#line 95 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  const CTFileName & CWerebull::GetComputerMessageName(void)const {
#line 98 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
static DECLARE_CTFILENAME  (fnm  , "Data\\Messages\\Enemies\\Bull.txt");
#line 99 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
return fnm ;
#line 100 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 103 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::RenderParticles(void) 
#line 104 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
{
#line 105 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
Particles_RunningDust  (this );
#line 106 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
CEnemyBase  :: RenderParticles  ();
#line 107 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 110 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 111 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 112 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
{
#line 114 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(! IsOfClass  (penInflictor  , "Werebull")){
#line 115 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 116 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
#line 117 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 119 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::AdjustDifficulty(void) 
#line 120 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
{
#line 122 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 125 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
INDEX CWerebull::AnimForDeath(void) {
#line 126 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
INDEX iAnim ;
#line 127 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(en_vCurrentTranslationAbsolute  . Length  () > 5.0f){
#line 128 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
iAnim  = WEREBULL_ANIM_DEATHRUN ;
#line 129 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}else {
#line 130 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
iAnim  = WEREBULL_ANIM_DEATH ;
#line 131 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
#line 132 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
StartModelAnim  (iAnim  , 0);
#line 133 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
DeactivateRunningSound  ();
#line 134 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
return iAnim ;
#line 135 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 137 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
FLOAT CWerebull::WaitForDust(FLOAT3D & vStretch) {
#line 138 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(GetModelObject  () -> GetAnim  () == WEREBULL_ANIM_DEATHRUN )
#line 139 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
{
#line 140 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
vStretch  = FLOAT3D (1 , 1 , 2) * 2.0f;
#line 141 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
return 0.6f;
#line 142 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
#line 143 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
else if(GetModelObject  () -> GetAnim  () == WEREBULL_ANIM_DEATH )
#line 144 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
{
#line 145 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
vStretch  = FLOAT3D (1 , 1 , 2) * 2.0f;
#line 146 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
return 0.7f;
#line 147 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
#line 148 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
return - 1.0f;
#line 149 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 151 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::DeathNotify() {
#line 152 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
ChangeCollisionBoxIndexWhenPossible  (WEREBULL_COLLISION_BOX_DEATH );
#line 153 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
SetCollisionFlags  (ECF_MODEL );
#line 154 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 157 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::StandingAnim(void) {
#line 158 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
StartModelAnim  (WEREBULL_ANIM_IDLE  , AOF_LOOPING  | AOF_NORESTART );
#line 159 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
DeactivateRunningSound  ();
#line 160 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 161 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::WalkingAnim(void) {
#line 162 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
StartModelAnim  (WEREBULL_ANIM_WALK  , AOF_LOOPING  | AOF_NORESTART );
#line 163 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
DeactivateRunningSound  ();
#line 164 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 165 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::RunningAnim(void) {
#line 166 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
StartModelAnim  (WEREBULL_ANIM_RUN  , AOF_LOOPING  | AOF_NORESTART );
#line 167 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
ActivateRunningSound  ();
#line 168 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 169 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::RotatingAnim(void) {
#line 170 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
StartModelAnim  (WEREBULL_ANIM_RUN  , AOF_LOOPING  | AOF_NORESTART );
#line 172 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
ActivateRunningSound  ();
#line 173 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 176 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::IdleSound(void) {
#line 177 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
PlaySound  (m_soSound  , SOUND_IDLE  , SOF_3D );
#line 178 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 179 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::SightSound(void) {
#line 180 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
PlaySound  (m_soSound  , SOUND_SIGHT  , SOF_3D );
#line 181 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 182 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::WoundSound(void) {
#line 183 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 184 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::DeathSound(void) {
#line 185 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
PlaySound  (m_soSound  , SOUND_DEATH  , SOF_3D );
#line 186 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 190 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::ActivateRunningSound(void) 
#line 191 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
{
#line 192 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(! m_bRunSoundPlaying ){
#line 193 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
PlaySound  (m_soFeet  , SOUND_RUN  , SOF_3D  | SOF_LOOP );
#line 194 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_bRunSoundPlaying  = TRUE ;
#line 195 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
#line 196 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 197 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::DeactivateRunningSound(void) 
#line 198 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
{
#line 199 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_soFeet  . Stop  ();
#line 200 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_bRunSoundPlaying  = FALSE ;
#line 201 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 208 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::LiveEntityTouched(ETouch etouch) {
#line 209 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(m_penLastTouched  != etouch  . penOther  || _pTimer  -> CurrentTick  () >= m_fLastTouchedTime  + 0.25f){
#line 211 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
FLOAT3D vDirection  = en_vCurrentTranslationAbsolute ;
#line 212 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
vDirection  . Normalize  ();
#line 213 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
ANGLE aHitAngle  = FLOAT3D (etouch  . plCollision ) % vDirection ;
#line 215 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(aHitAngle  < 0.0f){
#line 217 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(! IsOfSameClass  (this  , etouch  . penOther )){
#line 218 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
IncreaseKickedMass  (etouch  . penOther );
#line 219 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
#line 220 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
PlaySound  (m_soSound  , SOUND_IMPACT  , SOF_3D );
#line 222 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_penLastTouched  = etouch  . penOther ;
#line 223 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fLastTouchedTime  = _pTimer  -> CurrentTick  ();
#line 225 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
FLOAT3D vDirection  = m_penEnemy  -> GetPlacement  () . pl_PositionVector  - GetPlacement  () . pl_PositionVector ;
#line 226 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
vDirection  . Normalize  ();
#line 227 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
InflictDirectDamage  (etouch  . penOther  , this  , DMT_CLOSERANGE  , - aHitAngle  * 40.0f , 
#line 228 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
FLOAT3D (0 , 0 , 0) , vDirection );
#line 230 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
FLOAT3D vSpeed  = - FLOAT3D (etouch  . plCollision );
#line 231 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
vSpeed  = vSpeed  * 10.0f;
#line 232 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
const FLOATmatrix3D & m  = GetRotationMatrix  ();
#line 233 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
FLOAT3D vSpeedRel  = vSpeed  * ! m ;
#line 234 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(vSpeedRel  (1) < - 0.1f){
#line 235 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
vSpeedRel  (1) -= 15.0f;
#line 236 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}else {
#line 237 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
vSpeedRel  (1) += 15.0f;
#line 238 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
#line 239 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
vSpeedRel  (2) = 15.0f;
#line 241 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
vSpeed  = vSpeedRel  * m ;
#line 242 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
KickEntity  (etouch  . penOther  , vSpeed );
#line 243 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
#line 244 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
#line 245 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 248 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
BOOL CWerebull::HigherMass(void) {
#line 249 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
return (m_fMassKicked  > 500.0f);
#line 250 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
  
#line 253 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
void CWerebull::EnemyPostInit(void) 
#line 254 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
{
#line 256 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_soFeet  . Set3DParameters  (500.0f , 50.0f , 1.0f , 1.0f);
#line 257 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_bRunSoundPlaying  = FALSE ;
#line 258 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_soSound  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 259 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
BOOL CWerebull::
#line 266 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
Hit(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWerebull_Hit
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWerebull::Hit expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 267 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(!(CalcDist  (m_penEnemy ) < HIT_DISTANCE )){ Jump(STATE_CURRENT,0x01330007, FALSE, EInternal());return TRUE;}
#line 269 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
StartModelAnim  (WEREBULL_ANIM_ATTACKHORNS  , 0);
#line 270 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
DeactivateRunningSound  ();
#line 271 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_bHornHit  = FALSE ;
#line 272 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
SetTimerAfter(0.4f);
Jump(STATE_CURRENT, 0x01330001, FALSE, EBegin());return TRUE;}BOOL CWerebull::H0x01330001_Hit_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01330001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01330002, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWerebull::H0x01330002_Hit_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01330002
;
#line 273 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
PlaySound  (m_soSound  , SOUND_KICKHORN  , SOF_3D );
#line 274 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(CalcDist  (m_penEnemy ) < HIT_DISTANCE ){m_bHornHit  = TRUE ;}
#line 275 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
SetTimerAfter(0.1f);
Jump(STATE_CURRENT, 0x01330003, FALSE, EBegin());return TRUE;}BOOL CWerebull::H0x01330003_Hit_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01330003
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01330004, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWerebull::H0x01330004_Hit_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01330004
;
#line 276 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(CalcDist  (m_penEnemy ) < HIT_DISTANCE ){m_bHornHit  = TRUE ;}
#line 277 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
SetTimerAfter(0.1f);
Jump(STATE_CURRENT, 0x01330005, FALSE, EBegin());return TRUE;}BOOL CWerebull::H0x01330005_Hit_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01330005
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01330006, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWerebull::H0x01330006_Hit_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01330006
;
#line 278 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(CalcDist  (m_penEnemy ) < HIT_DISTANCE ){m_bHornHit  = TRUE ;}
#line 279 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(m_bHornHit ){
#line 280 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
FLOAT3D vDirection  = m_penEnemy  -> GetPlacement  () . pl_PositionVector  - GetPlacement  () . pl_PositionVector ;
#line 281 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
vDirection  . Normalize  ();
#line 282 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
InflictDirectDamage  (m_penEnemy  , this  , DMT_CLOSERANGE  , 20.0f , FLOAT3D (0 , 0 , 0) , vDirection );
#line 283 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
FLOAT3D vSpeed ;
#line 284 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
GetPitchDirection  (AngleDeg  (90.0f) , vSpeed );
#line 285 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
vSpeed  = vSpeed  * 10.0f;
#line 286 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
KickEntity  (m_penEnemy  , vSpeed );
#line 287 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}Jump(STATE_CURRENT,0x01330007, FALSE, EInternal());return TRUE;}BOOL CWerebull::H0x01330007_Hit_07(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01330007

#line 291 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fShootTime  = _pTimer  -> CurrentTick  () + 0.5f;
#line 292 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
Return(STATE_CURRENT,EReturn  ());
#line 292 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CWerebull::
#line 300 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWerebull_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWerebull::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 302 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
InitAsModel  ();
#line 303 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
SetPhysicsFlags  (EPF_MODEL_WALKING );
#line 304 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
SetCollisionFlags  (ECF_MODEL );
#line 305 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 306 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
SetHealth  (250.0f);
#line 307 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fMaxHealth  = 250.0f;
#line 308 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
en_fDensity  = 2000.0f;
#line 311 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
SetModel  (MODEL_WEREBULL );
#line 313 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
SetModelMainTexture  (TEXTURE_WEREBULL_SUMMER );
#line 317 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
StandingAnim  ();
#line 319 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fWalkSpeed  = FRnd  () + 2.5f;
#line 320 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 25.0f + 45.0f);
#line 321 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fAttackRunSpeed  = FRnd  () * 5.0f + 22.5f;
#line 322 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fAttackRotateRunInto  = AngleDeg  (FRnd  () * 60 + 100.0f);
#line 323 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_aAttackRotateSpeed  = m_fAttackRotateRunInto ;
#line 324 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fCloseRunSpeed  = FRnd  () * 5.0f + 15.0f;
#line 325 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 50 + 500.0f);
#line 327 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fAttackDistance  = 100.0f;
#line 328 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fCloseDistance  = 7.0f;
#line 329 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fStopDistance  = 0.0f;
#line 330 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fAttackFireTime  = 0.05f;
#line 331 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fCloseFireTime  = 1.0f;
#line 332 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fIgnoreRange  = 250.0f;
#line 334 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fBlowUpAmount  = 1E10f;
#line 335 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fBodyParts  = 12;
#line 336 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fDamageWounded  = 100000.0f;
#line 337 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_iScore  = 2000;
#line 338 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
if(m_fStepHeight  == - 1){
#line 339 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
m_fStepHeight  = 4.0f;
#line 340 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
}
#line 342 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
Particles_RunningDust_Prepare  (this );
#line 345 "/home/claude/serioussamclassic/SamTSE/Sources/EntitiesMP/Werebull.es"
Jump(STATE_CURRENT, STATE_CEnemyRunInto_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};